// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Odin Loch
#include "ms/linalg/linalg.hpp"
#include "detail.hpp"
#include <algorithm>
#include <cmath>
#include <functional>
#include <limits>
#include <vector>

namespace ms {

namespace {

using namespace linalg_detail;

// f(A) = V * diag(f(lambda)) * V^T. Exact only when V is orthogonal, i.e. when
// A is symmetric; every caller guards this behind is_symmetric().
Matrix<double> spectral_symmetric(
    const Matrix<double>& values,
    const Matrix<double>& V,
    const std::function<double(double)>& fn) {
    const size_t n = V.rows();
    Matrix<double> D = zeros<double>(n, n);
    for (size_t i = 0; i < n; ++i) {
        D(i, i) = fn(values(i, 0));
    }
    auto Vt = transpose_copy(V);
    return multiply(V, multiply(D, Vt));
}

// True when the real Schur factor holds a 2x2 block, i.e. a complex-conjugate
// eigenvalue pair that a real-arithmetic Parlett recurrence cannot serve.
bool has_complex_block(const Matrix<double>& T) {
    for (size_t i = 1; i < T.rows(); ++i) {
        if (T(i, i - 1) != 0.0) {
            return true;
        }
    }
    return false;
}

// ---------------------------------------------------------------------------
// Blocked Schur-Parlett (Davies-Higham) for clustered / repeated eigenvalues.
//
// The plain Parlett recurrence divides by T(j,j) - T(i,i), so it breaks down the
// moment two eigenvalues coincide -- and there f(A) genuinely depends on the
// DERIVATIVES of f, so no rearrangement of a formula that only samples f on the
// spectrum can recover it. The standard example is the defective
// J = [[2,1],[0,2]], whose logarithm is [[ln 2, 1/2],[0, ln 2]]: that 1/2 is
// (d/dx) ln x at 2.
//
// Given the Taylor coefficients of f the repair is standard:
//   * group eigenvalues lying within kBlockDelta of one another and reorder T,
//     by Givens swaps of adjacent 1x1 blocks, so each group is contiguous;
//   * evaluate each diagonal block by its Taylor series about the group mean
//     sigma, F_ii = sum_k c_k(sigma) * (T_ii - sigma I)^k, which TERMINATES when
//     the group is one repeated eigenvalue because T_ii - sigma I is then
//     strictly upper triangular, hence nilpotent;
//   * fill the off-diagonal blocks from the block form of the same commutation
//     relation F*T == T*F,
//       T_ii F_ij - F_ij T_jj = F_ii T_ij - T_ij F_jj
//                               + sum_{k=i+1}^{j-1} (F_ik T_kj - T_ik F_kj),
//     a triangular Sylvester equation whose coefficients are separated by
//     construction.
//
// Only reached when the spectrum actually has a numerically repeated pair; a
// separated spectrum still takes the plain recurrence above, unchanged.
// ---------------------------------------------------------------------------

// Eigenvalues within this multiple of ||T||_F share a block. 0.1 is the
// Davies-Higham default: large enough to keep the Sylvester solves well
// conditioned, small enough to keep the Taylor series short.
constexpr double kBlockDelta = 0.1;

// Swap the adjacent 1x1 diagonal blocks at (k,k) and (k+1,k+1) of the upper
// triangular T, accumulating the rotation into Q so that Q*T*Q^T is preserved.
// With a = T(k,k), b = T(k+1,k+1), c = T(k,k+1), the eigenvector of the 2x2
// block for b is (c, b-a), so the Givens rotation generated by that pair brings
// b to the top. Exact when a == b and c == 0, where the entries already commute.
void swap_adjacent(Matrix<double>& T, Matrix<double>& Q, size_t k) {
    const size_t n = T.rows();
    const double c = T(k, k + 1);
    const double d = T(k + 1, k + 1) - T(k, k);
    const double r = std::hypot(c, d);
    if (r == 0.0) {
        return;
    }
    const double cs = c / r;
    const double sn = d / r;

    for (size_t j = 0; j < n; ++j) {           // rows: G^T * T
        const double t1 = T(k, j);
        const double t2 = T(k + 1, j);
        T(k, j) = cs * t1 + sn * t2;
        T(k + 1, j) = -sn * t1 + cs * t2;
    }
    for (size_t i = 0; i < n; ++i) {           // columns: (...) * G
        const double t1 = T(i, k);
        const double t2 = T(i, k + 1);
        T(i, k) = cs * t1 + sn * t2;
        T(i, k + 1) = -sn * t1 + cs * t2;
    }
    for (size_t i = 0; i < n; ++i) {           // Q * G
        const double q1 = Q(i, k);
        const double q2 = Q(i, k + 1);
        Q(i, k) = cs * q1 + sn * q2;
        Q(i, k + 1) = -sn * q1 + cs * q2;
    }
    T(k + 1, k) = 0.0;  // restore exact triangularity
}

// Block id per diagonal position: entries within kBlockDelta*scale of each other
// share an id, numbered by first appearance so an already-grouped diagonal needs
// no swaps at all.
std::vector<size_t> cluster_diagonal(const Matrix<double>& T, double scale) {
    const size_t n = T.rows();
    std::vector<size_t> owner(n);
    for (size_t i = 0; i < n; ++i) {
        owner[i] = i;
    }
    const std::function<size_t(size_t)> find = [&owner, &find](size_t x) {
        return owner[x] == x ? x : (owner[x] = find(owner[x]));
    };
    const double delta = kBlockDelta * scale;
    for (size_t i = 0; i < n; ++i) {
        for (size_t j = i + 1; j < n; ++j) {
            if (std::abs(T(i, i) - T(j, j)) <= delta) {
                const size_t ri = find(i);
                const size_t rj = find(j);
                if (ri != rj) {
                    owner[rj] = ri;
                }
            }
        }
    }
    constexpr size_t kNone = static_cast<size_t>(-1);
    std::vector<size_t> label(n, 0);
    std::vector<size_t> id_of_root(n, kNone);
    size_t next = 0;
    for (size_t i = 0; i < n; ++i) {
        const size_t r = find(i);
        if (id_of_root[r] == kNone) {
            id_of_root[r] = next++;
        }
        label[i] = id_of_root[r];
    }
    return label;
}

// f(M) for an upper triangular M whose eigenvalues all lie in one cluster, by the
// Taylor series about their mean. `coeff(x, k)` returns the k-th Taylor
// coefficient f^(k)(x)/k!; taking the coefficient rather than the bare derivative
// is what keeps logm usable, since its k-th derivative carries a (k-1)! that
// overflows long before the series has converged.
bool atomic_block(const Matrix<double>& M,
                  const std::function<double(double, unsigned)>& coeff,
                  Matrix<double>& out) {
    const size_t m = M.rows();
    double sigma = 0.0;
    for (size_t i = 0; i < m; ++i) {
        sigma += M(i, i);
    }
    sigma /= static_cast<double>(m);

    Matrix<double> N = M;
    for (size_t i = 0; i < m; ++i) {
        N(i, i) -= sigma;
    }

    const double c0 = coeff(sigma, 0);
    if (!std::isfinite(c0)) {
        return false;
    }
    out = zeros<double>(m, m);
    for (size_t i = 0; i < m; ++i) {
        out(i, i) = c0;
    }

    Matrix<double> power = eye<double>(m);  // N^k
    const double base = std::max(std::abs(c0), 1.0);
    constexpr unsigned kMaxTerms = 250;
    constexpr double kPowerCeiling = 1e250;
    unsigned settled = 0;
    for (unsigned k = 1; k <= kMaxTerms; ++k) {
        power = multiply(power, N);
        const double pnorm = frobenius_norm(power);
        if (pnorm == 0.0) {
            return true;  // N nilpotent and exhausted: the series is exact
        }
        if (!std::isfinite(pnorm) || pnorm > kPowerCeiling) {
            return settled >= 2;
        }
        const double ck = coeff(sigma, k);
        if (!std::isfinite(ck)) {
            return settled >= 2;
        }
        for (size_t i = 0; i < m; ++i) {
            for (size_t j = i; j < m; ++j) {
                out(i, j) += ck * power(i, j);
            }
        }
        // Two consecutive negligible terms, so that an isolated zero coefficient
        // (cos at a multiple of pi/2) does not end the sum early.
        if (std::abs(ck) * pnorm <=
            std::numeric_limits<double>::epsilon() * std::max(base, frobenius_norm(out))) {
            if (++settled == 2) {
                return true;
            }
        } else {
            settled = 0;
        }
    }
    return false;
}

// Solve A*X - X*B = C for upper triangular A (p x p) and B (q x q) with separated
// spectra, by back-substitution from the bottom-left corner.
bool triangular_sylvester(const Matrix<double>& A, const Matrix<double>& B,
                          const Matrix<double>& C, double sep_tol, Matrix<double>& X) {
    const size_t p = A.rows();
    const size_t q = B.rows();
    X = zeros<double>(p, q);
    for (size_t j = 0; j < q; ++j) {
        for (size_t ii = 0; ii < p; ++ii) {
            const size_t i = p - 1 - ii;
            double rhs = C(i, j);
            for (size_t k = i + 1; k < p; ++k) {
                rhs -= A(i, k) * X(k, j);
            }
            for (size_t k = 0; k < j; ++k) {
                rhs += X(i, k) * B(k, j);
            }
            const double den = A(i, i) - B(j, j);
            if (std::abs(den) <= sep_tol) {
                return false;
            }
            X(i, j) = rhs / den;
        }
    }
    return true;
}

Result<Matrix<double>> blocked_parlett(Matrix<double> T, Matrix<double> Q,
                                       const std::function<double(double, unsigned)>& coeff,
                                       const char* fname) {
    const size_t n = T.rows();
    const double tnorm = std::max(frobenius_norm(T), 1.0);
    std::vector<size_t> label = cluster_diagonal(T, tnorm);

    // Bubble the diagonal into block order; each pass removes at least one
    // inversion, so n passes always suffice.
    for (size_t pass = 0; pass < n; ++pass) {
        bool swapped = false;
        for (size_t k = 0; k + 1 < n; ++k) {
            if (label[k] > label[k + 1]) {
                swap_adjacent(T, Q, k);
                std::swap(label[k], label[k + 1]);
                swapped = true;
            }
        }
        if (!swapped) {
            break;
        }
    }
    for (size_t k = 0; k + 1 < n; ++k) {
        if (label[k] > label[k + 1]) {
            return std::unexpected(DomainError{
                fname, "could not reorder the Schur form into separated blocks"});
        }
    }

    std::vector<size_t> start;
    for (size_t i = 0; i < n; ++i) {
        if (i == 0 || label[i] != label[i - 1]) {
            start.push_back(i);
        }
    }
    start.push_back(n);
    const size_t nb = start.size() - 1;

    const auto sub = [&T](size_t r0, size_t r1, size_t c0, size_t c1) {
        Matrix<double> S = zeros<double>(r1 - r0, c1 - c0);
        for (size_t i = r0; i < r1; ++i) {
            for (size_t j = c0; j < c1; ++j) {
                S(i - r0, j - c0) = T(i, j);
            }
        }
        return S;
    };

    Matrix<double> F = zeros<double>(n, n);
    const auto put = [&F](const Matrix<double>& S, size_t r0, size_t c0) {
        for (size_t i = 0; i < S.rows(); ++i) {
            for (size_t j = 0; j < S.cols(); ++j) {
                F(r0 + i, c0 + j) = S(i, j);
            }
        }
    };
    const auto get = [&F](size_t r0, size_t r1, size_t c0, size_t c1) {
        Matrix<double> S = zeros<double>(r1 - r0, c1 - c0);
        for (size_t i = r0; i < r1; ++i) {
            for (size_t j = c0; j < c1; ++j) {
                S(i - r0, j - c0) = F(i, j);
            }
        }
        return S;
    };

    for (size_t b = 0; b < nb; ++b) {
        Matrix<double> Fb;
        if (!atomic_block(sub(start[b], start[b + 1], start[b], start[b + 1]), coeff, Fb)) {
            return std::unexpected(DomainError{
                fname,
                "the Taylor series for a clustered diagonal block did not "
                "converge, or f is not finite at the block's eigenvalue"});
        }
        put(Fb, start[b], start[b]);
    }

    const double sep_tol = 1e-12 * tnorm;
    for (size_t d = 1; d < nb; ++d) {
        for (size_t i = 0; i + d < nb; ++i) {
            const size_t j = i + d;
            const size_t r0 = start[i], r1 = start[i + 1];
            const size_t c0 = start[j], c1 = start[j + 1];

            Matrix<double> C = multiply(get(r0, r1, r0, r1), sub(r0, r1, c0, c1));
            const Matrix<double> minus = multiply(sub(r0, r1, c0, c1), get(c0, c1, c0, c1));
            const size_t cells = C.rows() * C.cols();
            for (size_t x = 0; x < cells; ++x) {
                C.data()[x] -= minus.data()[x];
            }
            for (size_t k = i + 1; k < j; ++k) {
                const size_t m0 = start[k], m1 = start[k + 1];
                const Matrix<double> t1 = multiply(get(r0, r1, m0, m1), sub(m0, m1, c0, c1));
                const Matrix<double> t2 = multiply(sub(r0, r1, m0, m1), get(m0, m1, c0, c1));
                for (size_t x = 0; x < cells; ++x) {
                    C.data()[x] += t1.data()[x] - t2.data()[x];
                }
            }

            Matrix<double> X;
            if (!triangular_sylvester(sub(r0, r1, r0, r1), sub(c0, c1, c0, c1), C, sep_tol, X)) {
                return std::unexpected(DomainError{
                    fname,
                    "two eigenvalue clusters are not separated enough to solve "
                    "the block Parlett recurrence"});
            }
            put(X, r0, c0);
        }
    }

    auto Qt = transpose_copy(Q);
    return multiply(Q, multiply(F, Qt));
}

// Schur-Parlett: f(A) = Q * F * Q^T where F = f(T) is built from the diagonal
// outwards by the Parlett recurrence
//   F(i,j) = ( T(i,j)*(F(j,j)-F(i,i))
//              + sum_{k=i+1}^{j-1} (T(i,k)F(k,j) - F(i,k)T(k,j)) )
//            / (T(j,j) - T(i,i)),
// which is the (i,j) entry of the commutation relation F*T == T*F.
// The recurrence is only usable when the diagonal entries are separated. A
// clustered pair goes to the blocked algorithm above when `coeff` supplies f's
// Taylor coefficients, and is reported otherwise -- never divided through and
// never silently zeroed.
Result<Matrix<double>> schur_parlett(
    const Matrix<double>& A,
    const std::function<double(double)>& fn,
    const char* fname,
    const std::function<double(double, unsigned)>& coeff = {}) {
    auto sr = linalg_detail::real_schur(A);
    if (!sr) {
        return std::unexpected(sr.error());
    }
    const Matrix<double>& T = sr->T;
    const Matrix<double>& Q = sr->Q;
    const size_t n = T.rows();

    if (has_complex_block(T)) {
        return std::unexpected(DomainError{
            fname,
            "matrix has complex-conjugate eigenvalues; a real Schur-Parlett "
            "evaluation of f(A) would need complex arithmetic"});
    }

    const double tnorm = std::max(frobenius_norm(T), 1.0);
    const double sep_tol = 1e-8 * tnorm;

    Matrix<double> F = zeros<double>(n, n);
    double fscale = 1.0;
    for (size_t i = 0; i < n; ++i) {
        F(i, i) = fn(T(i, i));
        if (!std::isfinite(F(i, i))) {
            return std::unexpected(DomainError{
                fname, "f is not finite at an eigenvalue of the matrix"});
        }
        fscale = std::max(fscale, std::abs(F(i, i)));
    }

    // A repeated or clustered eigenvalue makes the Parlett denominator vanish.
    // f(A) then depends on f's derivatives, so it is answerable only with the
    // Taylor coefficients: with them, take the blocked algorithm; without them,
    // say so.
    for (size_t i = 0; i < n; ++i) {
        for (size_t j = i + 1; j < n; ++j) {
            if (std::abs(T(j, j) - T(i, i)) <= sep_tol) {
                if (!coeff) {
                    return std::unexpected(DomainError{
                        fname,
                        "repeated or clustered eigenvalues: f(A) depends on the "
                        "derivatives of f there, which this overload does not "
                        "have (see funm_taylor)"});
                }
                return blocked_parlett(T, Q, coeff, fname);
            }
        }
    }

    for (size_t d = 1; d < n; ++d) {
        for (size_t i = 0; i + d < n; ++i) {
            const size_t j = i + d;
            double num = T(i, j) * (F(j, j) - F(i, i));
            for (size_t k = i + 1; k < j; ++k) {
                num += T(i, k) * F(k, j) - F(i, k) * T(k, j);
            }
            // Separation was established above, so the denominator is safe.
            const double den = T(j, j) - T(i, i);
            F(i, j) = num / den;
            fscale = std::max(fscale, std::abs(F(i, j)));
        }
    }

    auto Qt = transpose_copy(Q);
    return multiply(Q, multiply(F, Qt));
}

// Taylor coefficients c_k = f^(k)(x)/k! for the functions whose derivatives are
// known in closed form. Returning the COEFFICIENT rather than the derivative
// keeps logm representable: its k-th derivative carries a (k-1)! that overflows
// at k = 172, while the coefficient (-1)^(k+1)/(k x^k) never does.
double log_taylor(double x, unsigned k) {
    if (k == 0) {
        return std::log(x);
    }
    const double sign = (k % 2 == 1) ? 1.0 : -1.0;
    return sign / (static_cast<double>(k) * std::pow(x, static_cast<double>(k)));
}

constexpr double kHalfPi = 1.57079632679489661923;

double sin_taylor(double x, unsigned k) {
    return std::sin(x + static_cast<double>(k) * kHalfPi) *
           std::exp(-std::lgamma(static_cast<double>(k) + 1.0));
}

double cos_taylor(double x, unsigned k) {
    return std::cos(x + static_cast<double>(k) * kHalfPi) *
           std::exp(-std::lgamma(static_cast<double>(k) + 1.0));
}

// Schur square root (Bjorck-Hammarling): R upper triangular with R*R == T,
//   R(i,i) = sqrt(T(i,i)),
//   R(i,j) = (T(i,j) - sum_{k=i+1}^{j-1} R(i,k)R(k,j)) / (R(i,i)+R(j,j)).
// Unlike the Parlett recurrence this stays well defined for repeated
// eigenvalues; it only fails when two diagonal square roots cancel, which for
// nonnegative eigenvalues means both are zero.
Result<Matrix<double>> schur_sqrt(const Matrix<double>& A) {
    auto sr = linalg_detail::real_schur(A);
    if (!sr) {
        return std::unexpected(sr.error());
    }
    const Matrix<double>& T = sr->T;
    const Matrix<double>& Q = sr->Q;
    const size_t n = T.rows();

    if (has_complex_block(T)) {
        return std::unexpected(DomainError{
            "sqrtm",
            "matrix has complex-conjugate eigenvalues; its real square root "
            "is not computed by this implementation"});
    }

    const double tnorm = std::max(frobenius_norm(T), 1.0);
    const double neg_tol = static_cast<double>(n) * tnorm
                         * std::numeric_limits<double>::epsilon() * 16.0;

    Matrix<double> R = zeros<double>(n, n);
    for (size_t i = 0; i < n; ++i) {
        const double t = T(i, i);
        if (t < -neg_tol) {
            return std::unexpected(DomainError{
                "sqrtm",
                "matrix has a negative eigenvalue; its square root is not real"});
        }
        R(i, i) = std::sqrt(t > 0.0 ? t : 0.0);
    }
    for (size_t d = 1; d < n; ++d) {
        for (size_t i = 0; i + d < n; ++i) {
            const size_t j = i + d;
            double num = T(i, j);
            for (size_t k = i + 1; k < j; ++k) {
                num -= R(i, k) * R(k, j);
            }
            const double den = R(i, i) + R(j, j);
            if (std::abs(den) <= std::numeric_limits<double>::epsilon() * tnorm) {
                if (std::abs(num) <= std::numeric_limits<double>::epsilon() * tnorm) {
                    R(i, j) = 0.0;
                    continue;
                }
                return std::unexpected(DomainError{
                    "sqrtm",
                    "matrix is singular and defective at a zero eigenvalue; it "
                    "has no square root"});
            }
            R(i, j) = num / den;
        }
    }

    auto Qt = transpose_copy(Q);
    return multiply(Q, multiply(R, Qt));
}

} // namespace

template<typename S, StorageOrder OA, template<typename> class Alloc>
Result<Matrix<S, OA, Alloc>> logm(const Matrix<S, OA, Alloc>& A) {
    if (A.rows() != A.cols()) {
        return std::unexpected(DimensionMismatch{A.rows(), A.cols()});
    }

    if (is_symmetric(A)) {
        auto er = eig_sym(A);
        if (!er) {
            return std::unexpected(er.error());
        }
        for (size_t i = 0; i < er->values.rows(); ++i) {
            if (er->values(i, 0) <= 0.0) {
                return std::unexpected(DomainError{
                    "logm",
                    "symmetric matrix is not positive definite; its logarithm "
                    "is not real"});
            }
        }
        return spectral_symmetric(er->values, er->vectors,
                                  [](double x) { return std::log(x); });
    }

    return schur_parlett(to_col_major(A),
                         [](double x) { return std::log(x); }, "logm", log_taylor);
}

template<typename S, StorageOrder OA, template<typename> class Alloc>
Result<Matrix<S, OA, Alloc>> sqrtm(const Matrix<S, OA, Alloc>& A) {
    if (A.rows() != A.cols()) {
        return std::unexpected(DimensionMismatch{A.rows(), A.cols()});
    }

    if (is_symmetric(A)) {
        auto er = eig_sym(A);
        if (!er) {
            return std::unexpected(er.error());
        }
        double scale = 1.0;
        for (size_t i = 0; i < er->values.rows(); ++i) {
            scale = std::max(scale, std::abs(er->values(i, 0)));
        }
        const double neg_tol = scale * static_cast<double>(A.rows())
                             * std::numeric_limits<double>::epsilon() * 16.0;
        for (size_t i = 0; i < er->values.rows(); ++i) {
            if (er->values(i, 0) < -neg_tol) {
                return std::unexpected(DomainError{
                    "sqrtm",
                    "symmetric matrix has a negative eigenvalue; its square "
                    "root is not real"});
            }
        }
        return spectral_symmetric(er->values, er->vectors, [](double x) {
            return x > 0.0 ? std::sqrt(x) : 0.0;
        });
    }

    return schur_sqrt(to_col_major(A));
}

template auto logm<double>(const Matrix<double>&) -> Result<Matrix<double>>;
template auto sqrtm<double>(const Matrix<double>&) -> Result<Matrix<double>>;

template<typename S, StorageOrder OA, template<typename> class Alloc>
Result<Matrix<S, OA, Alloc>> sinm(const Matrix<S, OA, Alloc>& A) {
    if (A.rows() != A.cols()) {
        return std::unexpected(DimensionMismatch{A.rows(), A.cols()});
    }
    if (is_symmetric(A)) {
        auto er = eig_sym(A);
        if (!er) return std::unexpected(er.error());
        return spectral_symmetric(er->values, er->vectors,
                                  [](double x) { return std::sin(x); });
    }
    return schur_parlett(to_col_major(A),
                         [](double x) { return std::sin(x); }, "sinm", sin_taylor);
}

template<typename S, StorageOrder OA, template<typename> class Alloc>
Result<Matrix<S, OA, Alloc>> cosm(const Matrix<S, OA, Alloc>& A) {
    if (A.rows() != A.cols()) {
        return std::unexpected(DimensionMismatch{A.rows(), A.cols()});
    }
    if (is_symmetric(A)) {
        auto er = eig_sym(A);
        if (!er) return std::unexpected(er.error());
        return spectral_symmetric(er->values, er->vectors,
                                  [](double x) { return std::cos(x); });
    }
    return schur_parlett(to_col_major(A),
                         [](double x) { return std::cos(x); }, "cosm", cos_taylor);
}

template<typename S, StorageOrder OA, template<typename> class Alloc>
Result<Matrix<S, OA, Alloc>> funm(const Matrix<S, OA, Alloc>& A,
                                   std::function<S(S)> func) {
    if (A.rows() != A.cols()) {
        return std::unexpected(DimensionMismatch{A.rows(), A.cols()});
    }
    if (!func) {
        return std::unexpected(DomainError{"funm", "empty function object"});
    }
    const std::function<double(double)> fn = [&func](double x) {
        return static_cast<double>(func(static_cast<S>(x)));
    };
    if (is_symmetric(A)) {
        auto er = eig_sym(A);
        if (!er) return std::unexpected(er.error());
        return Matrix<S, OA, Alloc>(
            spectral_symmetric(er->values, er->vectors, fn));
    }
    auto res = schur_parlett(to_col_major(A), fn, "funm");
    if (!res) {
        return std::unexpected(res.error());
    }
    return Matrix<S, OA, Alloc>(*res);
}

template<typename S, StorageOrder OA, template<typename> class Alloc>
Result<Matrix<S, OA, Alloc>> funm_taylor(const Matrix<S, OA, Alloc>& A,
                                          std::function<S(S, unsigned)> coefficients) {
    if (A.rows() != A.cols()) {
        return std::unexpected(DimensionMismatch{A.rows(), A.cols()});
    }
    if (!coefficients) {
        return std::unexpected(DomainError{"funm_taylor", "empty function object"});
    }
    const std::function<double(double, unsigned)> coeff =
        [&coefficients](double x, unsigned k) {
            return static_cast<double>(coefficients(static_cast<S>(x), k));
        };
    const std::function<double(double)> fn = [&coeff](double x) { return coeff(x, 0); };
    if (is_symmetric(A)) {
        auto er = eig_sym(A);
        if (!er) return std::unexpected(er.error());
        return Matrix<S, OA, Alloc>(spectral_symmetric(er->values, er->vectors, fn));
    }
    auto res = schur_parlett(to_col_major(A), fn, "funm_taylor", coeff);
    if (!res) {
        return std::unexpected(res.error());
    }
    return Matrix<S, OA, Alloc>(*res);
}

template auto sinm<double>(const Matrix<double>&) -> Result<Matrix<double>>;
template auto cosm<double>(const Matrix<double>&) -> Result<Matrix<double>>;
template auto funm<double>(const Matrix<double>&,
                            std::function<double(double)>) -> Result<Matrix<double>>;
template auto funm_taylor<double>(const Matrix<double>&,
                                   std::function<double(double, unsigned)>)
    -> Result<Matrix<double>>;

} // namespace ms
