#!/usr/bin/env bash
# Run benchmark smoke (or full JSON export) and compare against stored baselines.
# MS_BENCH_REGRESSION=off  — smoke only, skip baseline compare.
# MS_BENCH_TOLERANCE=10    — allowed slowdown percent before failing (default 10).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD_DIR="build-bench"
WRITE_BASELINE=0
BASELINE="${ROOT}/tests/performance/baselines/linux-gcc13.json"
TOLERANCE="${MS_BENCH_TOLERANCE:-10}"
REGRESSION="${MS_BENCH_REGRESSION:-on}"

usage() {
    echo "Usage: $0 [--write-baseline] [BUILD_DIR]" >&2
    echo "  --write-baseline  Run calibrated benchmarks and overwrite ${BASELINE##*/}" >&2
    exit 1
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --write-baseline)
            WRITE_BASELINE=1
            shift
            ;;
        -h|--help)
            usage
            ;;
        *)
            BUILD_DIR="$1"
            shift
            ;;
    esac
done

if [[ -d "${BUILD_DIR}" ]]; then
    BUILD_PATH="${BUILD_DIR}"
else
    BUILD_PATH="${ROOT}/${BUILD_DIR}"
fi

if [[ ! -d "${BUILD_PATH}" ]]; then
    echo "Build directory not found: ${BUILD_DIR}" >&2
    exit 1
fi

bench_path() {
    local name="$1"
    echo "${BUILD_PATH}/tests/performance/${name}"
}

run_smoke() {
    bash "${ROOT}/scripts/bench_smoke.sh" "${BUILD_DIR}"
}

BENCH_JSON_DIR=""

run_json_suite() {
    local min_time="$1"
    local repetitions="$2"
    local aggregates_only="${3:-false}"
    BENCH_JSON_DIR="$(mktemp -d)"

    local merged="${BENCH_JSON_DIR}/bench_results.json"
    echo '{"benchmarks":[]}' > "${merged}"

    for bench in bench_matmul bench_fft bench_linalg bench_repl; do
        local path
        path="$(bench_path "${bench}")"
        if [[ ! -x "${path}" ]]; then
            echo "Missing benchmark executable: ${path}" >&2
            exit 1
        fi
        local bench_json="${BENCH_JSON_DIR}/${bench}.json"
        "${path}" \
            --benchmark_min_time="${min_time}" \
            --benchmark_repetitions="${repetitions}" \
            --benchmark_report_aggregates_only="${aggregates_only}" \
            --benchmark_out="${bench_json}" \
            --benchmark_out_format=json \
            1>&2
        python3 - "${merged}" "${bench_json}" <<'PY'
import json, sys
merged_path, bench_path = sys.argv[1], sys.argv[2]
with open(merged_path) as f:
    merged = json.load(f)
with open(bench_path) as f:
    data = json.load(f)
merged["benchmarks"].extend(data.get("benchmarks", []))
with open(merged_path, "w") as f:
    json.dump(merged, f)
PY
    done
}

if [[ "${REGRESSION}" == "off" && "${WRITE_BASELINE}" -eq 0 ]]; then
    run_smoke
    exit 0
fi

cleanup_json_suite() {
    if [[ -n "${BENCH_JSON_DIR}" && -d "${BENCH_JSON_DIR}" ]]; then
        rm -rf "${BENCH_JSON_DIR}"
        BENCH_JSON_DIR=""
    fi
}

read_baseline_profile() {
    python3 - "${BASELINE}" <<'PY'
import json, sys
with open(sys.argv[1]) as f:
    data = json.load(f)
profile = data.get("profile", {})
print(profile.get("benchmark_min_time", "0.1s"))
print(profile.get("benchmark_repetitions", 5))
PY
}

if [[ "${WRITE_BASELINE}" -eq 1 ]]; then
    # Individual runs (not aggregates); median per benchmark name is stored in baseline.
    run_json_suite "0.1s" 5 false
    results_json="${BENCH_JSON_DIR}/bench_results.json"
    python3 - "${results_json}" "${BASELINE}" <<'PY'
import json, statistics, sys

results_path, baseline_path = sys.argv[1], sys.argv[2]
with open(results_path) as f:
    data = json.load(f)

by_name = {}
for entry in data.get("benchmarks", []):
    name = entry.get("name") or entry.get("run_name")
    if not name:
        continue
    unit = entry.get("time_unit", "s")
    real = float(entry["real_time"])
    if unit == "s":
        ns = real * 1e9
    elif unit == "ms":
        ns = real * 1e6
    elif unit == "us":
        ns = real * 1e3
    elif unit == "ns":
        ns = real
    else:
        raise SystemExit(f"Unsupported time_unit: {unit}")
    by_name.setdefault(name, []).append(ns)

baseline = {
    "_comment": "Generated by scripts/bench_regression.sh --write-baseline",
    "_generate": "bash scripts/bench_regression.sh --write-baseline build-bench",
    "profile": {
        "os": "linux",
        "compiler": "gcc-13",
        "build_type": "Release",
        "benchmark_min_time": "0.1s",
        "benchmark_repetitions": 5,
    },
    "benchmarks": {
        name: {"median_time_ns": int(statistics.median(samples))}
        for name, samples in sorted(by_name.items())
    },
}
with open(baseline_path, "w") as f:
    json.dump(baseline, f, indent=2)
    f.write("\n")
print(f"Wrote baseline: {baseline_path}")
for name, spec in baseline["benchmarks"].items():
    print(f"  {name}: {spec['median_time_ns']} ns")
PY
    cleanup_json_suite
    exit 0
fi

mapfile -t _profile < <(read_baseline_profile)
MIN_TIME="${_profile[0]:-0.1s}"
REPETITIONS="${_profile[1]:-5}"
run_json_suite "${MIN_TIME}" "${REPETITIONS}" false
results_json="${BENCH_JSON_DIR}/bench_results.json"
python3 - "${results_json}" "${BASELINE}" "${TOLERANCE}" <<'PY'
import json, statistics, sys

results_path, baseline_path, tolerance = sys.argv[1], sys.argv[2], float(sys.argv[3])
with open(results_path) as f:
    results = json.load(f)
with open(baseline_path) as f:
    baseline = json.load(f)

baseline_ns = {
    name: float(spec["median_time_ns"])
    for name, spec in baseline.get("benchmarks", {}).items()
}

def to_ns(entry):
    unit = entry.get("time_unit", "s")
    real = float(entry["real_time"])
    if unit == "s":
        return real * 1e9
    if unit == "ms":
        return real * 1e6
    if unit == "us":
        return real * 1e3
    if unit == "ns":
        return real
    raise SystemExit(f"Unsupported time_unit: {unit}")

by_name = {}
for entry in results.get("benchmarks", []):
    name = entry.get("name") or entry.get("run_name")
    if not name:
        continue
    by_name.setdefault(name, []).append(to_ns(entry))

current = {
    name: statistics.median(samples)
    for name, samples in by_name.items()
}

missing = sorted(set(baseline_ns) - set(current))
if missing:
    print("ERROR: benchmark results missing baseline entries:", ", ".join(missing), file=sys.stderr)
    sys.exit(1)

regressions = []
for name, base in sorted(baseline_ns.items()):
    measured = current[name]
    limit = base * (1.0 + tolerance / 100.0)
    pct = ((measured / base) - 1.0) * 100.0
    if measured > limit:
        regressions.append((name, measured, base, pct))

if regressions:
    print(f"WARN: performance regression detected (>{tolerance:.0f}% slower than baseline):", file=sys.stderr)
    for name, measured, base, pct in regressions:
        print(
            f"  {name}: {measured:.0f} ns vs baseline {base:.0f} ns ({pct:+.1f}%)",
            file=sys.stderr,
        )
    sys.exit(1)

print("Benchmark regression check OK")
for name, base in sorted(baseline_ns.items()):
    measured = current[name]
    pct = ((measured / base) - 1.0) * 100.0
    print(f"  {name}: {measured:.0f} ns (baseline {base:.0f} ns, {pct:+.1f}%)")
PY
cleanup_json_suite
