#!/usr/bin/env python3
"""Emit a dispatch test for every matrix-call handler, from the manifest.

478 handlers reached v1.0.0 with no test that any of them was registered. A
handler whose registration is missing is not a compile error and not a link
error: `dispatch_matrix_call` reports "unsupported matrix call" and the failure
reads like a typo in the user's script. Nothing in the tree would have noticed.

    python3 scripts/extract_manifest.py
    python3 scripts/gen_matrix_call_tests.py
    python3 scripts/gen_matrix_call_tests.py --check   # fail if stale (CI)

Three properties per handler, all of them mechanical, none of them requiring
knowledge of what the callee computes:

  registration        the callee resolves to a handler
  wrong arity         an argument count the guard does not accept is rejected
                      rather than acted on -- the guard is what stands between a
                      miscount and an out-of-range assign.args[i]
  undefined operand   an accepted count with names that do not exist fails
                      cleanly, and does not fail as "unsupported matrix call"

Happy paths are deliberately not generated. What a valid call should return is
per-callee semantics; a generator that invented inputs would assert whatever the
implementation currently does, which is how a test suite comes to certify its own
bugs. Those belong in the hand-written REPL suites.

Output is one translation unit per domain directory (29 of them) plus a CMake
fragment listing them, so adding a domain wires itself up.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "tests" / "unit" / "matrix_calls"
MANIFEST = OUT_DIR / "matrix_calls_manifest.json"
SOURCES_CMAKE = OUT_DIR / "generated_sources.cmake"

BANNER = """// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Odin Loch
//
// GENERATED by scripts/gen_matrix_call_tests.py from matrix_calls_manifest.json.
// Do not edit: run the two scripts. CI regenerates both and fails on a dirty
// tree, so a handler cannot land without its dispatch tests.
"""


def cpp_str(s: str) -> str:
    """Escape a manifest string for a C++ string literal.

    The messages come from the handlers' own source, where they were already C++
    literals, so this is mostly a no-op -- but emitting them unescaped would make
    the generator depend on that staying true.
    """
    return s.replace("\\", "\\\\").replace('"', '\\"')


def ident(name: str) -> str:
    """A C++ identifier fragment from a callee or directory name."""
    return re.sub(r"[^0-9A-Za-z_]", "_", name)


def rejected_arity(arities: list[int], open_ended: bool, probed: int) -> int | None:
    """An argument count this handler must refuse.

    One above the largest accepted count is the mistake a caller actually makes,
    so prefer it; fall back to the smallest gap when the guard happens to accept
    that one too. A guard with no upper bound has no such count and gets no test
    rather than a guessed one.
    """
    if open_ended:
        return None
    candidate = max(arities) + 1
    if candidate not in arities and candidate <= probed:
        return candidate
    for n in range(probed + 1):
        if n not in arities:
            return n
    return None


def render_domain(domain: str, handlers: list[dict]) -> tuple[str, int]:
    suite = ident(domain)
    lines = [BANNER, '#include "matrix_call_test_support.hpp"', "",
             "using namespace ms::interp::testing;", ""]
    count = 0

    for h in handlers:
        callee = h["callee"]
        sym = ident(callee)
        lines.append(f'TEST(MatrixCallRegistration_{suite}, {sym}) {{')
        lines.append(f'    expect_registered("{callee}");')
        lines.append("}")
        lines.append("")
        count += 1

    for h in handlers:
        bad = rejected_arity(h["arities"], h["open_ended"], h["max_arity_probed"])
        if bad is None:
            continue
        sym = ident(h["callee"])
        accepted = ", ".join(str(a) for a in h["arities"])
        rej = h["rejection"]
        lines.append(f'// accepts {accepted}')
        lines.append(f'TEST(MatrixCallArity_{suite}, {sym}_rejects_{bad}) {{')
        lines.append(f'    expect_arity_rejected("{h["callee"]}", {bad},')
        lines.append(f'                          "{cpp_str(rej["fn"])}",')
        lines.append(f'                          "{cpp_str(rej["message"])}");')
        lines.append("}")
        lines.append("")
        count += 1

    for h in handlers:
        # Only handlers that resolve their first argument as a matrix operand can
        # be relied on to fail: one that ignores its arguments would legitimately
        # succeed, and asserting failure there would be asserting a lie.
        if not h["resolves_first"]:
            continue
        arity = min(a for a in h["arities"] if a >= 1) if any(
            a >= 1 for a in h["arities"]) else None
        if arity is None:
            continue
        sym = ident(h["callee"])
        lines.append(f'TEST(MatrixCallUndefinedOperand_{suite}, {sym}) {{')
        lines.append(f'    expect_undefined_operand_propagates("{h["callee"]}", {arity});')
        lines.append("}")
        lines.append("")
        count += 1

    return "\n".join(lines).rstrip("\n") + "\n", count


def build() -> tuple[dict[pathlib.Path, str], int]:
    if not MANIFEST.is_file():
        print(f"{MANIFEST} is missing; run scripts/extract_manifest.py first",
              file=sys.stderr)
        raise SystemExit(1)
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    probed = manifest["max_arity_probed"]

    by_domain: dict[str, list[dict]] = {}
    for h in manifest["handlers"]:
        h["max_arity_probed"] = probed
        # src/interp/matrix_calls/<domain>/<file>.cpp
        domain = h["file"].split("/")[3]
        by_domain.setdefault(domain, []).append(h)

    files: dict[pathlib.Path, str] = {}
    total = 0
    for domain in sorted(by_domain):
        handlers = sorted(by_domain[domain], key=lambda h: h["callee"])
        text, count = render_domain(domain, handlers)
        files[OUT_DIR / f"test_matrix_calls_{ident(domain)}.cpp"] = text
        total += count

    listing = "".join(
        f"    unit/matrix_calls/{p.name}\n" for p in sorted(files))
    files[SOURCES_CMAKE] = (
        "# GENERATED by scripts/gen_matrix_call_tests.py. Do not edit.\n"
        "set(MS_MATRIX_CALL_TEST_SOURCES\n" + listing + ")\n")
    return files, total


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="fail if any output is stale")
    args = ap.parse_args()

    files, total = build()

    if args.check:
        stale = [p for p, text in files.items()
                 if not p.is_file() or p.read_text(encoding="utf-8") != text]
        # A file left behind by a domain that no longer exists would keep
        # compiling tests for handlers that are gone.
        known = set(files)
        orphans = [p for p in OUT_DIR.glob("test_matrix_calls_*.cpp") if p not in known]
        if stale or orphans:
            for p in stale:
                print(f"stale: {p.relative_to(ROOT)}", file=sys.stderr)
            for p in orphans:
                print(f"orphan: {p.relative_to(ROOT)}", file=sys.stderr)
            print("\nrun: python3 scripts/extract_manifest.py && "
                  "python3 scripts/gen_matrix_call_tests.py", file=sys.stderr)
            return 1
        print(f"{len(files) - 1} generated suites are up to date ({total} tests)")
        return 0

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    known = set(files)
    for p in OUT_DIR.glob("test_matrix_calls_*.cpp"):
        if p not in known:
            p.unlink()
            print(f"removed orphan {p.relative_to(ROOT)}")
    for p, text in files.items():
        p.write_text(text, encoding="utf-8")
    print(f"wrote {len(files) - 1} suites under {OUT_DIR.relative_to(ROOT)}: {total} tests")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
