if(MS_ENABLE_COVERAGE)
    if(MS_COMPILER STREQUAL "clang" OR MS_COMPILER STREQUAL "gcc")
        add_compile_options(-O0 -g --coverage -fprofile-arcs -ftest-coverage)
        add_link_options(--coverage)
        message(STATUS "Coverage instrumentation enabled (gcov/llvm-cov)")
    elseif(MSVC)
        message(STATUS "Coverage instrumentation: use OpenCppCoverage or clang-cl with -fprofile-instr-generate on MSVC builds")
    endif()
endif()
