// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Odin Loch
//
// GENERATED by scripts/gen_matrix_call_tests.py from matrix_calls_manifest.json.
// Do not edit: run the two scripts. CI regenerates both and fails on a dirty
// tree, so a handler cannot land without its dispatch tests.

#include "matrix_call_test_support.hpp"

using namespace ms::interp::testing;

TEST(MatrixCallRegistration_linalg, bicgstab) {
    expect_registered("bicgstab");
}

TEST(MatrixCallRegistration_linalg, bidiag) {
    expect_registered("bidiag");
}

TEST(MatrixCallRegistration_linalg, cg) {
    expect_registered("cg");
}

TEST(MatrixCallRegistration_linalg, chol) {
    expect_registered("chol");
}

TEST(MatrixCallRegistration_linalg, cosm) {
    expect_registered("cosm");
}

TEST(MatrixCallRegistration_linalg, diag) {
    expect_registered("diag");
}

TEST(MatrixCallRegistration_linalg, eig) {
    expect_registered("eig");
}

TEST(MatrixCallRegistration_linalg, expm) {
    expect_registered("expm");
}

TEST(MatrixCallRegistration_linalg, eye) {
    expect_registered("eye");
}

TEST(MatrixCallRegistration_linalg, funm) {
    expect_registered("funm");
}

TEST(MatrixCallRegistration_linalg, gmres) {
    expect_registered("gmres");
}

TEST(MatrixCallRegistration_linalg, hess) {
    expect_registered("hess");
}

TEST(MatrixCallRegistration_linalg, inv) {
    expect_registered("inv");
}

TEST(MatrixCallRegistration_linalg, jacobi) {
    expect_registered("jacobi");
}

TEST(MatrixCallRegistration_linalg, kron) {
    expect_registered("kron");
}

TEST(MatrixCallRegistration_linalg, ldl) {
    expect_registered("ldl");
}

TEST(MatrixCallRegistration_linalg, linspace) {
    expect_registered("linspace");
}

TEST(MatrixCallRegistration_linalg, logm) {
    expect_registered("logm");
}

TEST(MatrixCallRegistration_linalg, lsmr) {
    expect_registered("lsmr");
}

TEST(MatrixCallRegistration_linalg, lsqr) {
    expect_registered("lsqr");
}

TEST(MatrixCallRegistration_linalg, matmul) {
    expect_registered("matmul");
}

TEST(MatrixCallRegistration_linalg, minres) {
    expect_registered("minres");
}

TEST(MatrixCallRegistration_linalg, null) {
    expect_registered("null");
}

TEST(MatrixCallRegistration_linalg, ones) {
    expect_registered("ones");
}

TEST(MatrixCallRegistration_linalg, orth) {
    expect_registered("orth");
}

TEST(MatrixCallRegistration_linalg, pinv) {
    expect_registered("pinv");
}

TEST(MatrixCallRegistration_linalg, precond_diag) {
    expect_registered("precond_diag");
}

TEST(MatrixCallRegistration_linalg, precond_ssor) {
    expect_registered("precond_ssor");
}

TEST(MatrixCallRegistration_linalg, qmr) {
    expect_registered("qmr");
}

TEST(MatrixCallRegistration_linalg, rand) {
    expect_registered("rand");
}

TEST(MatrixCallRegistration_linalg, randn) {
    expect_registered("randn");
}

TEST(MatrixCallRegistration_linalg, repmat) {
    expect_registered("repmat");
}

TEST(MatrixCallRegistration_linalg, schur) {
    expect_registered("schur");
}

TEST(MatrixCallRegistration_linalg, sinm) {
    expect_registered("sinm");
}

TEST(MatrixCallRegistration_linalg, solve) {
    expect_registered("solve");
}

TEST(MatrixCallRegistration_linalg, solve_sylvester) {
    expect_registered("solve_sylvester");
}

TEST(MatrixCallRegistration_linalg, sqrtm) {
    expect_registered("sqrtm");
}

TEST(MatrixCallRegistration_linalg, tfqmr) {
    expect_registered("tfqmr");
}

TEST(MatrixCallRegistration_linalg, transpose) {
    expect_registered("transpose");
}

TEST(MatrixCallRegistration_linalg, tril) {
    expect_registered("tril");
}

TEST(MatrixCallRegistration_linalg, triu) {
    expect_registered("triu");
}

TEST(MatrixCallRegistration_linalg, zeros) {
    expect_registered("zeros");
}

// accepts 2
TEST(MatrixCallArity_linalg, bicgstab_rejects_3) {
    expect_arity_rejected("bicgstab", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_linalg, bidiag_rejects_2) {
    expect_arity_rejected("bidiag", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_linalg, cg_rejects_3) {
    expect_arity_rejected("cg", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_linalg, chol_rejects_2) {
    expect_arity_rejected("chol", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_linalg, cosm_rejects_2) {
    expect_arity_rejected("cosm", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_linalg, diag_rejects_2) {
    expect_arity_rejected("diag", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_linalg, eig_rejects_2) {
    expect_arity_rejected("eig", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_linalg, expm_rejects_2) {
    expect_arity_rejected("expm", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1, 2
TEST(MatrixCallArity_linalg, eye_rejects_3) {
    expect_arity_rejected("eye", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_linalg, funm_rejects_3) {
    expect_arity_rejected("funm", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_linalg, gmres_rejects_3) {
    expect_arity_rejected("gmres", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_linalg, hess_rejects_2) {
    expect_arity_rejected("hess", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_linalg, inv_rejects_2) {
    expect_arity_rejected("inv", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_linalg, jacobi_rejects_3) {
    expect_arity_rejected("jacobi", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_linalg, kron_rejects_3) {
    expect_arity_rejected("kron", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_linalg, ldl_rejects_2) {
    expect_arity_rejected("ldl", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3
TEST(MatrixCallArity_linalg, linspace_rejects_4) {
    expect_arity_rejected("linspace", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_linalg, logm_rejects_2) {
    expect_arity_rejected("logm", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_linalg, lsmr_rejects_3) {
    expect_arity_rejected("lsmr", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_linalg, lsqr_rejects_3) {
    expect_arity_rejected("lsqr", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_linalg, matmul_rejects_3) {
    expect_arity_rejected("matmul", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_linalg, minres_rejects_3) {
    expect_arity_rejected("minres", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_linalg, null_rejects_2) {
    expect_arity_rejected("null", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1, 2
TEST(MatrixCallArity_linalg, ones_rejects_3) {
    expect_arity_rejected("ones", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_linalg, orth_rejects_2) {
    expect_arity_rejected("orth", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_linalg, pinv_rejects_2) {
    expect_arity_rejected("pinv", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_linalg, precond_diag_rejects_2) {
    expect_arity_rejected("precond_diag", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1, 2
TEST(MatrixCallArity_linalg, precond_ssor_rejects_3) {
    expect_arity_rejected("precond_ssor", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_linalg, qmr_rejects_3) {
    expect_arity_rejected("qmr", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_linalg, rand_rejects_3) {
    expect_arity_rejected("rand", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_linalg, randn_rejects_3) {
    expect_arity_rejected("randn", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3
TEST(MatrixCallArity_linalg, repmat_rejects_4) {
    expect_arity_rejected("repmat", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_linalg, schur_rejects_2) {
    expect_arity_rejected("schur", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_linalg, sinm_rejects_2) {
    expect_arity_rejected("sinm", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_linalg, solve_rejects_3) {
    expect_arity_rejected("solve", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3
TEST(MatrixCallArity_linalg, solve_sylvester_rejects_4) {
    expect_arity_rejected("solve_sylvester", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_linalg, sqrtm_rejects_2) {
    expect_arity_rejected("sqrtm", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_linalg, tfqmr_rejects_3) {
    expect_arity_rejected("tfqmr", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_linalg, transpose_rejects_2) {
    expect_arity_rejected("transpose", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1, 2
TEST(MatrixCallArity_linalg, tril_rejects_3) {
    expect_arity_rejected("tril", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1, 2
TEST(MatrixCallArity_linalg, triu_rejects_3) {
    expect_arity_rejected("triu", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1, 2
TEST(MatrixCallArity_linalg, zeros_rejects_3) {
    expect_arity_rejected("zeros", 3,
                          "assign",
                          "unsupported matrix call");
}

TEST(MatrixCallUndefinedOperand_linalg, bicgstab) {
    expect_undefined_operand_propagates("bicgstab", 2);
}

TEST(MatrixCallUndefinedOperand_linalg, bidiag) {
    expect_undefined_operand_propagates("bidiag", 1);
}

TEST(MatrixCallUndefinedOperand_linalg, cg) {
    expect_undefined_operand_propagates("cg", 2);
}

TEST(MatrixCallUndefinedOperand_linalg, chol) {
    expect_undefined_operand_propagates("chol", 1);
}

TEST(MatrixCallUndefinedOperand_linalg, cosm) {
    expect_undefined_operand_propagates("cosm", 1);
}

TEST(MatrixCallUndefinedOperand_linalg, diag) {
    expect_undefined_operand_propagates("diag", 1);
}

TEST(MatrixCallUndefinedOperand_linalg, eig) {
    expect_undefined_operand_propagates("eig", 1);
}

TEST(MatrixCallUndefinedOperand_linalg, expm) {
    expect_undefined_operand_propagates("expm", 1);
}

TEST(MatrixCallUndefinedOperand_linalg, funm) {
    expect_undefined_operand_propagates("funm", 2);
}

TEST(MatrixCallUndefinedOperand_linalg, gmres) {
    expect_undefined_operand_propagates("gmres", 2);
}

TEST(MatrixCallUndefinedOperand_linalg, hess) {
    expect_undefined_operand_propagates("hess", 1);
}

TEST(MatrixCallUndefinedOperand_linalg, inv) {
    expect_undefined_operand_propagates("inv", 1);
}

TEST(MatrixCallUndefinedOperand_linalg, jacobi) {
    expect_undefined_operand_propagates("jacobi", 2);
}

TEST(MatrixCallUndefinedOperand_linalg, kron) {
    expect_undefined_operand_propagates("kron", 2);
}

TEST(MatrixCallUndefinedOperand_linalg, ldl) {
    expect_undefined_operand_propagates("ldl", 1);
}

TEST(MatrixCallUndefinedOperand_linalg, logm) {
    expect_undefined_operand_propagates("logm", 1);
}

TEST(MatrixCallUndefinedOperand_linalg, lsmr) {
    expect_undefined_operand_propagates("lsmr", 2);
}

TEST(MatrixCallUndefinedOperand_linalg, lsqr) {
    expect_undefined_operand_propagates("lsqr", 2);
}

TEST(MatrixCallUndefinedOperand_linalg, matmul) {
    expect_undefined_operand_propagates("matmul", 2);
}

TEST(MatrixCallUndefinedOperand_linalg, minres) {
    expect_undefined_operand_propagates("minres", 2);
}

TEST(MatrixCallUndefinedOperand_linalg, null) {
    expect_undefined_operand_propagates("null", 1);
}

TEST(MatrixCallUndefinedOperand_linalg, orth) {
    expect_undefined_operand_propagates("orth", 1);
}

TEST(MatrixCallUndefinedOperand_linalg, pinv) {
    expect_undefined_operand_propagates("pinv", 1);
}

TEST(MatrixCallUndefinedOperand_linalg, precond_diag) {
    expect_undefined_operand_propagates("precond_diag", 1);
}

TEST(MatrixCallUndefinedOperand_linalg, precond_ssor) {
    expect_undefined_operand_propagates("precond_ssor", 1);
}

TEST(MatrixCallUndefinedOperand_linalg, qmr) {
    expect_undefined_operand_propagates("qmr", 2);
}

TEST(MatrixCallUndefinedOperand_linalg, repmat) {
    expect_undefined_operand_propagates("repmat", 3);
}

TEST(MatrixCallUndefinedOperand_linalg, schur) {
    expect_undefined_operand_propagates("schur", 1);
}

TEST(MatrixCallUndefinedOperand_linalg, sinm) {
    expect_undefined_operand_propagates("sinm", 1);
}

TEST(MatrixCallUndefinedOperand_linalg, solve) {
    expect_undefined_operand_propagates("solve", 2);
}

TEST(MatrixCallUndefinedOperand_linalg, solve_sylvester) {
    expect_undefined_operand_propagates("solve_sylvester", 3);
}

TEST(MatrixCallUndefinedOperand_linalg, sqrtm) {
    expect_undefined_operand_propagates("sqrtm", 1);
}

TEST(MatrixCallUndefinedOperand_linalg, tfqmr) {
    expect_undefined_operand_propagates("tfqmr", 2);
}

TEST(MatrixCallUndefinedOperand_linalg, transpose) {
    expect_undefined_operand_propagates("transpose", 1);
}

TEST(MatrixCallUndefinedOperand_linalg, tril) {
    expect_undefined_operand_propagates("tril", 1);
}

TEST(MatrixCallUndefinedOperand_linalg, triu) {
    expect_undefined_operand_propagates("triu", 1);
}

TEST(MatrixCallBadOperandAt_linalg, bicgstab_arg1) {
    expect_bad_operand_at("bicgstab", 2, 1);
}

TEST(MatrixCallBadOperandAt_linalg, cg_arg1) {
    expect_bad_operand_at("cg", 2, 1);
}

TEST(MatrixCallBadOperandAt_linalg, gmres_arg1) {
    expect_bad_operand_at("gmres", 2, 1);
}

TEST(MatrixCallBadOperandAt_linalg, jacobi_arg1) {
    expect_bad_operand_at("jacobi", 2, 1);
}

TEST(MatrixCallBadOperandAt_linalg, kron_arg1) {
    expect_bad_operand_at("kron", 2, 1);
}

TEST(MatrixCallBadOperandAt_linalg, lsmr_arg1) {
    expect_bad_operand_at("lsmr", 2, 1);
}

TEST(MatrixCallBadOperandAt_linalg, lsqr_arg1) {
    expect_bad_operand_at("lsqr", 2, 1);
}

TEST(MatrixCallBadOperandAt_linalg, matmul_arg1) {
    expect_bad_operand_at("matmul", 2, 1);
}

TEST(MatrixCallBadOperandAt_linalg, minres_arg1) {
    expect_bad_operand_at("minres", 2, 1);
}

TEST(MatrixCallBadOperandAt_linalg, qmr_arg1) {
    expect_bad_operand_at("qmr", 2, 1);
}

TEST(MatrixCallBadOperandAt_linalg, solve_arg1) {
    expect_bad_operand_at("solve", 2, 1);
}

TEST(MatrixCallBadOperandAt_linalg, solve_sylvester_arg1) {
    expect_bad_operand_at("solve_sylvester", 3, 1);
}

TEST(MatrixCallBadOperandAt_linalg, solve_sylvester_arg2) {
    expect_bad_operand_at("solve_sylvester", 3, 2);
}

TEST(MatrixCallBadOperandAt_linalg, tfqmr_arg1) {
    expect_bad_operand_at("tfqmr", 2, 1);
}

TEST(MatrixCallDegenerateOperand_linalg, bicgstab_empty) {
    expect_degenerate_operand_survives("bicgstab", 2,
                                       {0, 1}, "[]");
}

TEST(MatrixCallDegenerateOperand_linalg, bidiag_empty) {
    expect_degenerate_operand_survives("bidiag", 1,
                                       {0}, "[]");
}

TEST(MatrixCallDegenerateOperand_linalg, cg_empty) {
    expect_degenerate_operand_survives("cg", 2,
                                       {0, 1}, "[]");
}

TEST(MatrixCallDegenerateOperand_linalg, chol_empty) {
    expect_degenerate_operand_survives("chol", 1,
                                       {0}, "[]");
}

TEST(MatrixCallDegenerateOperand_linalg, cosm_empty) {
    expect_degenerate_operand_survives("cosm", 1,
                                       {0}, "[]");
}

TEST(MatrixCallDegenerateOperand_linalg, diag_empty) {
    expect_degenerate_operand_survives("diag", 1,
                                       {0}, "[]");
}

TEST(MatrixCallDegenerateOperand_linalg, eig_empty) {
    expect_degenerate_operand_survives("eig", 1,
                                       {0}, "[]");
}

TEST(MatrixCallDegenerateOperand_linalg, expm_empty) {
    expect_degenerate_operand_survives("expm", 1,
                                       {0}, "[]");
}

TEST(MatrixCallDegenerateOperand_linalg, funm_empty) {
    expect_degenerate_operand_survives("funm", 2,
                                       {0}, "[]");
}

TEST(MatrixCallDegenerateOperand_linalg, gmres_empty) {
    expect_degenerate_operand_survives("gmres", 2,
                                       {0, 1}, "[]");
}

TEST(MatrixCallDegenerateOperand_linalg, hess_empty) {
    expect_degenerate_operand_survives("hess", 1,
                                       {0}, "[]");
}

TEST(MatrixCallDegenerateOperand_linalg, inv_empty) {
    expect_degenerate_operand_survives("inv", 1,
                                       {0}, "[]");
}

TEST(MatrixCallDegenerateOperand_linalg, jacobi_empty) {
    expect_degenerate_operand_survives("jacobi", 2,
                                       {0, 1}, "[]");
}

TEST(MatrixCallDegenerateOperand_linalg, kron_empty) {
    expect_degenerate_operand_survives("kron", 2,
                                       {0, 1}, "[]");
}

TEST(MatrixCallDegenerateOperand_linalg, ldl_empty) {
    expect_degenerate_operand_survives("ldl", 1,
                                       {0}, "[]");
}

TEST(MatrixCallDegenerateOperand_linalg, logm_empty) {
    expect_degenerate_operand_survives("logm", 1,
                                       {0}, "[]");
}

TEST(MatrixCallDegenerateOperand_linalg, lsmr_empty) {
    expect_degenerate_operand_survives("lsmr", 2,
                                       {0, 1}, "[]");
}

TEST(MatrixCallDegenerateOperand_linalg, lsqr_empty) {
    expect_degenerate_operand_survives("lsqr", 2,
                                       {0, 1}, "[]");
}

TEST(MatrixCallDegenerateOperand_linalg, matmul_empty) {
    expect_degenerate_operand_survives("matmul", 2,
                                       {0, 1}, "[]");
}

TEST(MatrixCallDegenerateOperand_linalg, minres_empty) {
    expect_degenerate_operand_survives("minres", 2,
                                       {0, 1}, "[]");
}

TEST(MatrixCallDegenerateOperand_linalg, null_empty) {
    expect_degenerate_operand_survives("null", 1,
                                       {0}, "[]");
}

TEST(MatrixCallDegenerateOperand_linalg, orth_empty) {
    expect_degenerate_operand_survives("orth", 1,
                                       {0}, "[]");
}

TEST(MatrixCallDegenerateOperand_linalg, pinv_empty) {
    expect_degenerate_operand_survives("pinv", 1,
                                       {0}, "[]");
}

TEST(MatrixCallDegenerateOperand_linalg, precond_diag_empty) {
    expect_degenerate_operand_survives("precond_diag", 1,
                                       {0}, "[]");
}

TEST(MatrixCallDegenerateOperand_linalg, precond_ssor_empty) {
    expect_degenerate_operand_survives("precond_ssor", 1,
                                       {0}, "[]");
}

TEST(MatrixCallDegenerateOperand_linalg, qmr_empty) {
    expect_degenerate_operand_survives("qmr", 2,
                                       {0, 1}, "[]");
}

TEST(MatrixCallDegenerateOperand_linalg, repmat_empty) {
    expect_degenerate_operand_survives("repmat", 3,
                                       {0}, "[]");
}

TEST(MatrixCallDegenerateOperand_linalg, schur_empty) {
    expect_degenerate_operand_survives("schur", 1,
                                       {0}, "[]");
}

TEST(MatrixCallDegenerateOperand_linalg, sinm_empty) {
    expect_degenerate_operand_survives("sinm", 1,
                                       {0}, "[]");
}

TEST(MatrixCallDegenerateOperand_linalg, solve_empty) {
    expect_degenerate_operand_survives("solve", 2,
                                       {0, 1}, "[]");
}

TEST(MatrixCallDegenerateOperand_linalg, solve_sylvester_empty) {
    expect_degenerate_operand_survives("solve_sylvester", 3,
                                       {0, 1, 2}, "[]");
}

TEST(MatrixCallDegenerateOperand_linalg, sqrtm_empty) {
    expect_degenerate_operand_survives("sqrtm", 1,
                                       {0}, "[]");
}

TEST(MatrixCallDegenerateOperand_linalg, tfqmr_empty) {
    expect_degenerate_operand_survives("tfqmr", 2,
                                       {0, 1}, "[]");
}

TEST(MatrixCallDegenerateOperand_linalg, transpose_empty) {
    expect_degenerate_operand_survives("transpose", 1,
                                       {0}, "[]");
}

TEST(MatrixCallDegenerateOperand_linalg, tril_empty) {
    expect_degenerate_operand_survives("tril", 1,
                                       {0}, "[]");
}

TEST(MatrixCallDegenerateOperand_linalg, triu_empty) {
    expect_degenerate_operand_survives("triu", 1,
                                       {0}, "[]");
}
