// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Odin Loch
//
// GENERATED by scripts/gen_matrix_call_tests.py from matrix_calls_manifest.json.
// Do not edit: run the two scripts. CI regenerates both and fails on a dirty
// tree, so a handler cannot land without its dispatch tests.

#include "matrix_call_test_support.hpp"

using namespace ms::interp::testing;

TEST(MatrixCallRegistration_special, sph_harm) {
    expect_registered("sph_harm");
}

// accepts 4
TEST(MatrixCallArity_special, sph_harm_rejects_5) {
    expect_arity_rejected("sph_harm", 5,
                          "assign",
                          "unsupported matrix call");
}
