// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Odin Loch
//
// GENERATED by scripts/gen_matrix_call_tests.py from matrix_calls_manifest.json.
// Do not edit: run the two scripts. CI regenerates both and fails on a dirty
// tree, so a handler cannot land without its dispatch tests.

#include "matrix_call_test_support.hpp"

using namespace ms::interp::testing;

TEST(MatrixCallRegistration_graph, graph_adjacency_spectrum) {
    expect_registered("graph_adjacency_spectrum");
}

TEST(MatrixCallRegistration_graph, graph_articulation_points) {
    expect_registered("graph_articulation_points");
}

TEST(MatrixCallRegistration_graph, graph_bellman_ford) {
    expect_registered("graph_bellman_ford");
}

TEST(MatrixCallRegistration_graph, graph_betweenness) {
    expect_registered("graph_betweenness");
}

TEST(MatrixCallRegistration_graph, graph_biconnected_components) {
    expect_registered("graph_biconnected_components");
}

TEST(MatrixCallRegistration_graph, graph_bridges) {
    expect_registered("graph_bridges");
}

TEST(MatrixCallRegistration_graph, graph_closeness) {
    expect_registered("graph_closeness");
}

TEST(MatrixCallRegistration_graph, graph_connected_components) {
    expect_registered("graph_connected_components");
}

TEST(MatrixCallRegistration_graph, graph_degree_centrality) {
    expect_registered("graph_degree_centrality");
}

TEST(MatrixCallRegistration_graph, graph_dijkstra) {
    expect_registered("graph_dijkstra");
}

TEST(MatrixCallRegistration_graph, graph_eccentricity) {
    expect_registered("graph_eccentricity");
}

TEST(MatrixCallRegistration_graph, graph_eigenvector_centrality) {
    expect_registered("graph_eigenvector_centrality");
}

TEST(MatrixCallRegistration_graph, graph_euler_circuit) {
    expect_registered("graph_euler_circuit");
}

TEST(MatrixCallRegistration_graph, graph_eulerian_path) {
    expect_registered("graph_eulerian_path");
}

TEST(MatrixCallRegistration_graph, graph_floyd_warshall) {
    expect_registered("graph_floyd_warshall");
}

TEST(MatrixCallRegistration_graph, graph_greedy_colour) {
    expect_registered("graph_greedy_colour");
}

TEST(MatrixCallRegistration_graph, graph_hamiltonian_path) {
    expect_registered("graph_hamiltonian_path");
}

TEST(MatrixCallRegistration_graph, graph_k_core_decomposition) {
    expect_registered("graph_k_core_decomposition");
}

TEST(MatrixCallRegistration_graph, graph_katz_centrality) {
    expect_registered("graph_katz_centrality");
}

TEST(MatrixCallRegistration_graph, graph_kuratowski_subgraph) {
    expect_registered("graph_kuratowski_subgraph");
}

TEST(MatrixCallRegistration_graph, graph_laplacian) {
    expect_registered("graph_laplacian");
}

TEST(MatrixCallRegistration_graph, graph_louvain) {
    expect_registered("graph_louvain");
}

TEST(MatrixCallRegistration_graph, graph_max_weight_matching) {
    expect_registered("graph_max_weight_matching");
}

TEST(MatrixCallRegistration_graph, graph_maximum_matching) {
    expect_registered("graph_maximum_matching");
}

TEST(MatrixCallRegistration_graph, graph_min_arborescence) {
    expect_registered("graph_min_arborescence");
}

TEST(MatrixCallRegistration_graph, graph_mst_kruskal) {
    expect_registered("graph_mst_kruskal");
}

TEST(MatrixCallRegistration_graph, graph_mst_prim) {
    expect_registered("graph_mst_prim");
}

TEST(MatrixCallRegistration_graph, graph_normalised_laplacian) {
    expect_registered("graph_normalised_laplacian");
}

TEST(MatrixCallRegistration_graph, graph_pagerank) {
    expect_registered("graph_pagerank");
}

TEST(MatrixCallRegistration_graph, graph_planar_embedding) {
    expect_registered("graph_planar_embedding");
}

TEST(MatrixCallRegistration_graph, graph_scc) {
    expect_registered("graph_scc");
}

TEST(MatrixCallRegistration_graph, graph_topological_sort) {
    expect_registered("graph_topological_sort");
}

TEST(MatrixCallRegistration_graph, graph_transitive_closure) {
    expect_registered("graph_transitive_closure");
}

TEST(MatrixCallRegistration_graph, graph_tsp_heuristic) {
    expect_registered("graph_tsp_heuristic");
}

// accepts 1
TEST(MatrixCallArity_graph, graph_adjacency_spectrum_rejects_2) {
    expect_arity_rejected("graph_adjacency_spectrum", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_graph, graph_articulation_points_rejects_2) {
    expect_arity_rejected("graph_articulation_points", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_graph, graph_bellman_ford_rejects_3) {
    expect_arity_rejected("graph_bellman_ford", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_graph, graph_betweenness_rejects_2) {
    expect_arity_rejected("graph_betweenness", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_graph, graph_biconnected_components_rejects_2) {
    expect_arity_rejected("graph_biconnected_components", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_graph, graph_bridges_rejects_2) {
    expect_arity_rejected("graph_bridges", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_graph, graph_closeness_rejects_2) {
    expect_arity_rejected("graph_closeness", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_graph, graph_connected_components_rejects_2) {
    expect_arity_rejected("graph_connected_components", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_graph, graph_degree_centrality_rejects_2) {
    expect_arity_rejected("graph_degree_centrality", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_graph, graph_dijkstra_rejects_3) {
    expect_arity_rejected("graph_dijkstra", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_graph, graph_eccentricity_rejects_2) {
    expect_arity_rejected("graph_eccentricity", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_graph, graph_eigenvector_centrality_rejects_2) {
    expect_arity_rejected("graph_eigenvector_centrality", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_graph, graph_euler_circuit_rejects_2) {
    expect_arity_rejected("graph_euler_circuit", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_graph, graph_eulerian_path_rejects_2) {
    expect_arity_rejected("graph_eulerian_path", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_graph, graph_floyd_warshall_rejects_2) {
    expect_arity_rejected("graph_floyd_warshall", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_graph, graph_greedy_colour_rejects_2) {
    expect_arity_rejected("graph_greedy_colour", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_graph, graph_hamiltonian_path_rejects_2) {
    expect_arity_rejected("graph_hamiltonian_path", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_graph, graph_k_core_decomposition_rejects_2) {
    expect_arity_rejected("graph_k_core_decomposition", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_graph, graph_katz_centrality_rejects_2) {
    expect_arity_rejected("graph_katz_centrality", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_graph, graph_kuratowski_subgraph_rejects_2) {
    expect_arity_rejected("graph_kuratowski_subgraph", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_graph, graph_laplacian_rejects_2) {
    expect_arity_rejected("graph_laplacian", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_graph, graph_louvain_rejects_2) {
    expect_arity_rejected("graph_louvain", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1, 2
TEST(MatrixCallArity_graph, graph_max_weight_matching_rejects_3) {
    expect_arity_rejected("graph_max_weight_matching", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_graph, graph_maximum_matching_rejects_2) {
    expect_arity_rejected("graph_maximum_matching", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_graph, graph_min_arborescence_rejects_3) {
    expect_arity_rejected("graph_min_arborescence", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_graph, graph_mst_kruskal_rejects_2) {
    expect_arity_rejected("graph_mst_kruskal", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_graph, graph_mst_prim_rejects_2) {
    expect_arity_rejected("graph_mst_prim", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_graph, graph_normalised_laplacian_rejects_2) {
    expect_arity_rejected("graph_normalised_laplacian", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_graph, graph_pagerank_rejects_2) {
    expect_arity_rejected("graph_pagerank", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_graph, graph_planar_embedding_rejects_2) {
    expect_arity_rejected("graph_planar_embedding", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_graph, graph_scc_rejects_2) {
    expect_arity_rejected("graph_scc", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_graph, graph_topological_sort_rejects_2) {
    expect_arity_rejected("graph_topological_sort", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_graph, graph_transitive_closure_rejects_2) {
    expect_arity_rejected("graph_transitive_closure", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_graph, graph_tsp_heuristic_rejects_2) {
    expect_arity_rejected("graph_tsp_heuristic", 2,
                          "assign",
                          "unsupported matrix call");
}

TEST(MatrixCallUndefinedOperand_graph, graph_adjacency_spectrum) {
    expect_undefined_operand_propagates("graph_adjacency_spectrum", 1);
}

TEST(MatrixCallUndefinedOperand_graph, graph_articulation_points) {
    expect_undefined_operand_propagates("graph_articulation_points", 1);
}

TEST(MatrixCallUndefinedOperand_graph, graph_bellman_ford) {
    expect_undefined_operand_propagates("graph_bellman_ford", 2);
}

TEST(MatrixCallUndefinedOperand_graph, graph_betweenness) {
    expect_undefined_operand_propagates("graph_betweenness", 1);
}

TEST(MatrixCallUndefinedOperand_graph, graph_biconnected_components) {
    expect_undefined_operand_propagates("graph_biconnected_components", 1);
}

TEST(MatrixCallUndefinedOperand_graph, graph_bridges) {
    expect_undefined_operand_propagates("graph_bridges", 1);
}

TEST(MatrixCallUndefinedOperand_graph, graph_closeness) {
    expect_undefined_operand_propagates("graph_closeness", 1);
}

TEST(MatrixCallUndefinedOperand_graph, graph_connected_components) {
    expect_undefined_operand_propagates("graph_connected_components", 1);
}

TEST(MatrixCallUndefinedOperand_graph, graph_degree_centrality) {
    expect_undefined_operand_propagates("graph_degree_centrality", 1);
}

TEST(MatrixCallUndefinedOperand_graph, graph_dijkstra) {
    expect_undefined_operand_propagates("graph_dijkstra", 2);
}

TEST(MatrixCallUndefinedOperand_graph, graph_eccentricity) {
    expect_undefined_operand_propagates("graph_eccentricity", 1);
}

TEST(MatrixCallUndefinedOperand_graph, graph_eigenvector_centrality) {
    expect_undefined_operand_propagates("graph_eigenvector_centrality", 1);
}

TEST(MatrixCallUndefinedOperand_graph, graph_euler_circuit) {
    expect_undefined_operand_propagates("graph_euler_circuit", 1);
}

TEST(MatrixCallUndefinedOperand_graph, graph_eulerian_path) {
    expect_undefined_operand_propagates("graph_eulerian_path", 1);
}

TEST(MatrixCallUndefinedOperand_graph, graph_floyd_warshall) {
    expect_undefined_operand_propagates("graph_floyd_warshall", 1);
}

TEST(MatrixCallUndefinedOperand_graph, graph_greedy_colour) {
    expect_undefined_operand_propagates("graph_greedy_colour", 1);
}

TEST(MatrixCallUndefinedOperand_graph, graph_hamiltonian_path) {
    expect_undefined_operand_propagates("graph_hamiltonian_path", 1);
}

TEST(MatrixCallUndefinedOperand_graph, graph_k_core_decomposition) {
    expect_undefined_operand_propagates("graph_k_core_decomposition", 1);
}

TEST(MatrixCallUndefinedOperand_graph, graph_katz_centrality) {
    expect_undefined_operand_propagates("graph_katz_centrality", 1);
}

TEST(MatrixCallUndefinedOperand_graph, graph_kuratowski_subgraph) {
    expect_undefined_operand_propagates("graph_kuratowski_subgraph", 1);
}

TEST(MatrixCallUndefinedOperand_graph, graph_laplacian) {
    expect_undefined_operand_propagates("graph_laplacian", 1);
}

TEST(MatrixCallUndefinedOperand_graph, graph_louvain) {
    expect_undefined_operand_propagates("graph_louvain", 1);
}

TEST(MatrixCallUndefinedOperand_graph, graph_max_weight_matching) {
    expect_undefined_operand_propagates("graph_max_weight_matching", 1);
}

TEST(MatrixCallUndefinedOperand_graph, graph_maximum_matching) {
    expect_undefined_operand_propagates("graph_maximum_matching", 1);
}

TEST(MatrixCallUndefinedOperand_graph, graph_min_arborescence) {
    expect_undefined_operand_propagates("graph_min_arborescence", 2);
}

TEST(MatrixCallUndefinedOperand_graph, graph_mst_kruskal) {
    expect_undefined_operand_propagates("graph_mst_kruskal", 1);
}

TEST(MatrixCallUndefinedOperand_graph, graph_mst_prim) {
    expect_undefined_operand_propagates("graph_mst_prim", 1);
}

TEST(MatrixCallUndefinedOperand_graph, graph_normalised_laplacian) {
    expect_undefined_operand_propagates("graph_normalised_laplacian", 1);
}

TEST(MatrixCallUndefinedOperand_graph, graph_pagerank) {
    expect_undefined_operand_propagates("graph_pagerank", 1);
}

TEST(MatrixCallUndefinedOperand_graph, graph_planar_embedding) {
    expect_undefined_operand_propagates("graph_planar_embedding", 1);
}

TEST(MatrixCallUndefinedOperand_graph, graph_scc) {
    expect_undefined_operand_propagates("graph_scc", 1);
}

TEST(MatrixCallUndefinedOperand_graph, graph_topological_sort) {
    expect_undefined_operand_propagates("graph_topological_sort", 1);
}

TEST(MatrixCallUndefinedOperand_graph, graph_transitive_closure) {
    expect_undefined_operand_propagates("graph_transitive_closure", 1);
}

TEST(MatrixCallUndefinedOperand_graph, graph_tsp_heuristic) {
    expect_undefined_operand_propagates("graph_tsp_heuristic", 1);
}
