// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Odin Loch
//
// GENERATED by scripts/gen_matrix_call_tests.py from matrix_calls_manifest.json.
// Do not edit: run the two scripts. CI regenerates both and fails on a dirty
// tree, so a handler cannot land without its dispatch tests.

#include "matrix_call_test_support.hpp"

using namespace ms::interp::testing;

TEST(MatrixCallRegistration_cfd, cfd_advection1d) {
    expect_registered("cfd_advection1d");
}

TEST(MatrixCallRegistration_cfd, cfd_advection2d) {
    expect_registered("cfd_advection2d");
}

TEST(MatrixCallRegistration_cfd, cfd_advection3d) {
    expect_registered("cfd_advection3d");
}

TEST(MatrixCallRegistration_cfd, cfd_constant_velocity) {
    expect_registered("cfd_constant_velocity");
}

TEST(MatrixCallRegistration_cfd, cfd_grid1d) {
    expect_registered("cfd_grid1d");
}

TEST(MatrixCallRegistration_cfd, cfd_grid2d) {
    expect_registered("cfd_grid2d");
}

TEST(MatrixCallRegistration_cfd, cfd_grid3d) {
    expect_registered("cfd_grid3d");
}

TEST(MatrixCallRegistration_cfd, cfd_run_advection) {
    expect_registered("cfd_run_advection");
}

TEST(MatrixCallRegistration_cfd, cfd_run_advection_2d) {
    expect_registered("cfd_run_advection_2d");
}

TEST(MatrixCallRegistration_cfd, cfd_run_advection_3d) {
    expect_registered("cfd_run_advection_3d");
}

TEST(MatrixCallRegistration_cfd, cfd_square_pulse) {
    expect_registered("cfd_square_pulse");
}

TEST(MatrixCallRegistration_cfd, cfd_square_pulse_2d) {
    expect_registered("cfd_square_pulse_2d");
}

TEST(MatrixCallRegistration_cfd, cfd_square_pulse_3d) {
    expect_registered("cfd_square_pulse_3d");
}

TEST(MatrixCallRegistration_cfd, cfd_upwind_step_1d) {
    expect_registered("cfd_upwind_step_1d");
}

TEST(MatrixCallRegistration_cfd, cfd_upwind_step_2d) {
    expect_registered("cfd_upwind_step_2d");
}

TEST(MatrixCallRegistration_cfd, cfd_upwind_step_3d) {
    expect_registered("cfd_upwind_step_3d");
}

// accepts 4
TEST(MatrixCallArity_cfd, cfd_advection1d_rejects_5) {
    expect_arity_rejected("cfd_advection1d", 5,
                          "assign",
                          "unsupported matrix call");
}

// accepts 6
TEST(MatrixCallArity_cfd, cfd_advection2d_rejects_7) {
    expect_arity_rejected("cfd_advection2d", 7,
                          "assign",
                          "unsupported matrix call");
}

// accepts 8
TEST(MatrixCallArity_cfd, cfd_advection3d_rejects_9) {
    expect_arity_rejected("cfd_advection3d", 9,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_cfd, cfd_constant_velocity_rejects_3) {
    expect_arity_rejected("cfd_constant_velocity", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3
TEST(MatrixCallArity_cfd, cfd_grid1d_rejects_4) {
    expect_arity_rejected("cfd_grid1d", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 6
TEST(MatrixCallArity_cfd, cfd_grid2d_rejects_7) {
    expect_arity_rejected("cfd_grid2d", 7,
                          "assign",
                          "unsupported matrix call");
}

// accepts 9
TEST(MatrixCallArity_cfd, cfd_grid3d_rejects_10) {
    expect_arity_rejected("cfd_grid3d", 10,
                          "assign",
                          "unsupported matrix call");
}

// accepts 5
TEST(MatrixCallArity_cfd, cfd_run_advection_rejects_6) {
    expect_arity_rejected("cfd_run_advection", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 6
TEST(MatrixCallArity_cfd, cfd_run_advection_2d_rejects_7) {
    expect_arity_rejected("cfd_run_advection_2d", 7,
                          "assign",
                          "unsupported matrix call");
}

// accepts 7
TEST(MatrixCallArity_cfd, cfd_run_advection_3d_rejects_8) {
    expect_arity_rejected("cfd_run_advection_3d", 8,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3, 4
TEST(MatrixCallArity_cfd, cfd_square_pulse_rejects_5) {
    expect_arity_rejected("cfd_square_pulse", 5,
                          "assign",
                          "unsupported matrix call");
}

// accepts 5, 6
TEST(MatrixCallArity_cfd, cfd_square_pulse_2d_rejects_7) {
    expect_arity_rejected("cfd_square_pulse_2d", 7,
                          "assign",
                          "unsupported matrix call");
}

// accepts 7, 8
TEST(MatrixCallArity_cfd, cfd_square_pulse_3d_rejects_9) {
    expect_arity_rejected("cfd_square_pulse_3d", 9,
                          "assign",
                          "unsupported matrix call");
}

// accepts 4, 5
TEST(MatrixCallArity_cfd, cfd_upwind_step_1d_rejects_6) {
    expect_arity_rejected("cfd_upwind_step_1d", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 5, 6, 7, 8
TEST(MatrixCallArity_cfd, cfd_upwind_step_2d_rejects_9) {
    expect_arity_rejected("cfd_upwind_step_2d", 9,
                          "assign",
                          "unsupported matrix call");
}

// accepts 6, 9
TEST(MatrixCallArity_cfd, cfd_upwind_step_3d_rejects_10) {
    expect_arity_rejected("cfd_upwind_step_3d", 10,
                          "assign",
                          "unsupported matrix call");
}

TEST(MatrixCallUndefinedOperand_cfd, cfd_run_advection) {
    expect_undefined_operand_propagates("cfd_run_advection", 5);
}

TEST(MatrixCallUndefinedOperand_cfd, cfd_run_advection_2d) {
    expect_undefined_operand_propagates("cfd_run_advection_2d", 6);
}

TEST(MatrixCallUndefinedOperand_cfd, cfd_run_advection_3d) {
    expect_undefined_operand_propagates("cfd_run_advection_3d", 7);
}

TEST(MatrixCallUndefinedOperand_cfd, cfd_square_pulse) {
    expect_undefined_operand_propagates("cfd_square_pulse", 3);
}

TEST(MatrixCallUndefinedOperand_cfd, cfd_square_pulse_2d) {
    expect_undefined_operand_propagates("cfd_square_pulse_2d", 5);
}

TEST(MatrixCallUndefinedOperand_cfd, cfd_square_pulse_3d) {
    expect_undefined_operand_propagates("cfd_square_pulse_3d", 7);
}

TEST(MatrixCallUndefinedOperand_cfd, cfd_upwind_step_1d) {
    expect_undefined_operand_propagates("cfd_upwind_step_1d", 4);
}

TEST(MatrixCallUndefinedOperand_cfd, cfd_upwind_step_2d) {
    expect_undefined_operand_propagates("cfd_upwind_step_2d", 5);
}

TEST(MatrixCallUndefinedOperand_cfd, cfd_upwind_step_3d) {
    expect_undefined_operand_propagates("cfd_upwind_step_3d", 6);
}

TEST(MatrixCallBadOperandAt_cfd, cfd_run_advection_arg1) {
    expect_bad_operand_at("cfd_run_advection", 5, 1);
}

TEST(MatrixCallBadOperandAt_cfd, cfd_run_advection_2d_arg1) {
    expect_bad_operand_at("cfd_run_advection_2d", 6, 1);
}

TEST(MatrixCallBadOperandAt_cfd, cfd_run_advection_3d_arg1) {
    expect_bad_operand_at("cfd_run_advection_3d", 7, 1);
}

TEST(MatrixCallBadOperandAt_cfd, cfd_upwind_step_1d_arg1) {
    expect_bad_operand_at("cfd_upwind_step_1d", 5, 1);
}

TEST(MatrixCallBadOperandAt_cfd, cfd_upwind_step_2d_arg1) {
    expect_bad_operand_at("cfd_upwind_step_2d", 8, 1);
}

TEST(MatrixCallBadOperandAt_cfd, cfd_upwind_step_3d_arg1) {
    expect_bad_operand_at("cfd_upwind_step_3d", 9, 1);
}
