// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Odin Loch
//
// GENERATED by scripts/gen_matrix_call_tests.py from matrix_calls_manifest.json.
// Do not edit: run the two scripts. CI regenerates both and fails on a dirty
// tree, so a handler cannot land without its dispatch tests.

#include "matrix_call_test_support.hpp"

using namespace ms::interp::testing;

TEST(MatrixCallRegistration_numthy, numthy_continued_fraction) {
    expect_registered("numthy_continued_fraction");
}

TEST(MatrixCallRegistration_numthy, numthy_convergents) {
    expect_registered("numthy_convergents");
}

TEST(MatrixCallRegistration_numthy, numthy_cornacchia) {
    expect_registered("numthy_cornacchia");
}

TEST(MatrixCallRegistration_numthy, numthy_factor_exp) {
    expect_registered("numthy_factor_exp");
}

TEST(MatrixCallRegistration_numthy, numthy_farey) {
    expect_registered("numthy_farey");
}

TEST(MatrixCallRegistration_numthy, numthy_lucas_sequence) {
    expect_registered("numthy_lucas_sequence");
}

TEST(MatrixCallRegistration_numthy, numthy_pell_solve) {
    expect_registered("numthy_pell_solve");
}

TEST(MatrixCallRegistration_numthy, numthy_primes) {
    expect_registered("numthy_primes");
}

TEST(MatrixCallRegistration_numthy, numthy_quadratic_residues) {
    expect_registered("numthy_quadratic_residues");
}

TEST(MatrixCallRegistration_numthy, numthy_stern_brocot) {
    expect_registered("numthy_stern_brocot");
}

// accepts 2
TEST(MatrixCallArity_numthy, numthy_continued_fraction_rejects_3) {
    expect_arity_rejected("numthy_continued_fraction", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_numthy, numthy_convergents_rejects_2) {
    expect_arity_rejected("numthy_convergents", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_numthy, numthy_cornacchia_rejects_3) {
    expect_arity_rejected("numthy_cornacchia", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_numthy, numthy_factor_exp_rejects_2) {
    expect_arity_rejected("numthy_factor_exp", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_numthy, numthy_farey_rejects_2) {
    expect_arity_rejected("numthy_farey", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3
TEST(MatrixCallArity_numthy, numthy_lucas_sequence_rejects_4) {
    expect_arity_rejected("numthy_lucas_sequence", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_numthy, numthy_pell_solve_rejects_2) {
    expect_arity_rejected("numthy_pell_solve", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_numthy, numthy_primes_rejects_3) {
    expect_arity_rejected("numthy_primes", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_numthy, numthy_quadratic_residues_rejects_2) {
    expect_arity_rejected("numthy_quadratic_residues", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_numthy, numthy_stern_brocot_rejects_2) {
    expect_arity_rejected("numthy_stern_brocot", 2,
                          "assign",
                          "unsupported matrix call");
}

TEST(MatrixCallUndefinedOperand_numthy, numthy_convergents) {
    expect_undefined_operand_propagates("numthy_convergents", 1);
}
