// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Odin Loch
//
// GENERATED by scripts/gen_matrix_call_tests.py from matrix_calls_manifest.json.
// Do not edit: run the two scripts. CI regenerates both and fails on a dirty
// tree, so a handler cannot land without its dispatch tests.

#include "matrix_call_test_support.hpp"

using namespace ms::interp::testing;

TEST(MatrixCallRegistration_ode, ode_adams_bashforth2) {
    expect_registered("ode_adams_bashforth2");
}

TEST(MatrixCallRegistration_ode, ode_backward_euler) {
    expect_registered("ode_backward_euler");
}

TEST(MatrixCallRegistration_ode, ode_bdf2) {
    expect_registered("ode_bdf2");
}

TEST(MatrixCallRegistration_ode, ode_euler) {
    expect_registered("ode_euler");
}

TEST(MatrixCallRegistration_ode, ode_midpoint) {
    expect_registered("ode_midpoint");
}

TEST(MatrixCallRegistration_ode, ode_rk2) {
    expect_registered("ode_rk2");
}

TEST(MatrixCallRegistration_ode, ode_rk4) {
    expect_registered("ode_rk4");
}

TEST(MatrixCallRegistration_ode, ode_rosenbrock23) {
    expect_registered("ode_rosenbrock23");
}

TEST(MatrixCallRegistration_ode, ode_trapezoidal) {
    expect_registered("ode_trapezoidal");
}

// accepts 5
TEST(MatrixCallArity_ode, ode_adams_bashforth2_rejects_6) {
    expect_arity_rejected("ode_adams_bashforth2", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 5
TEST(MatrixCallArity_ode, ode_backward_euler_rejects_6) {
    expect_arity_rejected("ode_backward_euler", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 5
TEST(MatrixCallArity_ode, ode_bdf2_rejects_6) {
    expect_arity_rejected("ode_bdf2", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 5
TEST(MatrixCallArity_ode, ode_euler_rejects_6) {
    expect_arity_rejected("ode_euler", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 5
TEST(MatrixCallArity_ode, ode_midpoint_rejects_6) {
    expect_arity_rejected("ode_midpoint", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 5
TEST(MatrixCallArity_ode, ode_rk2_rejects_6) {
    expect_arity_rejected("ode_rk2", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 5
TEST(MatrixCallArity_ode, ode_rk4_rejects_6) {
    expect_arity_rejected("ode_rk4", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 5
TEST(MatrixCallArity_ode, ode_rosenbrock23_rejects_6) {
    expect_arity_rejected("ode_rosenbrock23", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 5
TEST(MatrixCallArity_ode, ode_trapezoidal_rejects_6) {
    expect_arity_rejected("ode_trapezoidal", 6,
                          "assign",
                          "unsupported matrix call");
}
