// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Odin Loch
//
// GENERATED by scripts/gen_matrix_call_tests.py from matrix_calls_manifest.json.
// Do not edit: run the two scripts. CI regenerates both and fails on a dirty
// tree, so a handler cannot land without its dispatch tests.

#include "matrix_call_test_support.hpp"

using namespace ms::interp::testing;

TEST(MatrixCallRegistration_frameworks, cellai_boltzmann_weights) {
    expect_registered("cellai_boltzmann_weights");
}

TEST(MatrixCallRegistration_frameworks, cellai_cell_to_cypha_features) {
    expect_registered("cellai_cell_to_cypha_features");
}

TEST(MatrixCallRegistration_frameworks, cellai_hebbian_update) {
    expect_registered("cellai_hebbian_update");
}

TEST(MatrixCallRegistration_frameworks, cellmemory_long_term_state) {
    expect_registered("cellmemory_long_term_state");
}

TEST(MatrixCallRegistration_frameworks, cellmemory_recall) {
    expect_registered("cellmemory_recall");
}

TEST(MatrixCallRegistration_frameworks, gria_ca_step) {
    expect_registered("gria_ca_step");
}

TEST(MatrixCallRegistration_frameworks, gria_divergence_trajectory) {
    expect_registered("gria_divergence_trajectory");
}

TEST(MatrixCallRegistration_frameworks, gria_gf2n_generate_field) {
    expect_registered("gria_gf2n_generate_field");
}

TEST(MatrixCallRegistration_frameworks, izaac_decrypt) {
    expect_registered("izaac_decrypt");
}

TEST(MatrixCallRegistration_frameworks, izaac_encrypt) {
    expect_registered("izaac_encrypt");
}

TEST(MatrixCallRegistration_frameworks, izaac_fuzz_mutate) {
    expect_registered("izaac_fuzz_mutate");
}

TEST(MatrixCallRegistration_frameworks, izaac_rand_matrix) {
    expect_registered("izaac_rand_matrix");
}

TEST(MatrixCallRegistration_frameworks, izaac_randn_matrix) {
    expect_registered("izaac_randn_matrix");
}

TEST(MatrixCallRegistration_frameworks, izaac_vrf_keygen) {
    expect_registered("izaac_vrf_keygen");
}

TEST(MatrixCallRegistration_frameworks, izaac_vrf_prove) {
    expect_registered("izaac_vrf_prove");
}

// accepts 1, 2
TEST(MatrixCallArity_frameworks, cellai_boltzmann_weights_rejects_3) {
    expect_arity_rejected("cellai_boltzmann_weights", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1, 2
TEST(MatrixCallArity_frameworks, cellai_cell_to_cypha_features_rejects_3) {
    expect_arity_rejected("cellai_cell_to_cypha_features", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 4
TEST(MatrixCallArity_frameworks, cellai_hebbian_update_rejects_5) {
    expect_arity_rejected("cellai_hebbian_update", 5,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_frameworks, cellmemory_long_term_state_rejects_2) {
    expect_arity_rejected("cellmemory_long_term_state", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_frameworks, cellmemory_recall_rejects_3) {
    expect_arity_rejected("cellmemory_recall", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_frameworks, gria_ca_step_rejects_3) {
    expect_arity_rejected("gria_ca_step", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 4
TEST(MatrixCallArity_frameworks, gria_divergence_trajectory_rejects_5) {
    expect_arity_rejected("gria_divergence_trajectory", 5,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_frameworks, gria_gf2n_generate_field_rejects_2) {
    expect_arity_rejected("gria_gf2n_generate_field", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_frameworks, izaac_decrypt_rejects_3) {
    expect_arity_rejected("izaac_decrypt", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_frameworks, izaac_encrypt_rejects_3) {
    expect_arity_rejected("izaac_encrypt", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1, 2
TEST(MatrixCallArity_frameworks, izaac_fuzz_mutate_rejects_3) {
    expect_arity_rejected("izaac_fuzz_mutate", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_frameworks, izaac_rand_matrix_rejects_3) {
    expect_arity_rejected("izaac_rand_matrix", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_frameworks, izaac_randn_matrix_rejects_3) {
    expect_arity_rejected("izaac_randn_matrix", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 0
TEST(MatrixCallArity_frameworks, izaac_vrf_keygen_rejects_1) {
    expect_arity_rejected("izaac_vrf_keygen", 1,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_frameworks, izaac_vrf_prove_rejects_3) {
    expect_arity_rejected("izaac_vrf_prove", 3,
                          "assign",
                          "unsupported matrix call");
}

TEST(MatrixCallUndefinedOperand_frameworks, cellai_hebbian_update) {
    expect_undefined_operand_propagates("cellai_hebbian_update", 4);
}

TEST(MatrixCallUndefinedOperand_frameworks, gria_ca_step) {
    expect_undefined_operand_propagates("gria_ca_step", 2);
}

TEST(MatrixCallUndefinedOperand_frameworks, gria_divergence_trajectory) {
    expect_undefined_operand_propagates("gria_divergence_trajectory", 4);
}

TEST(MatrixCallUndefinedOperand_frameworks, izaac_decrypt) {
    expect_undefined_operand_propagates("izaac_decrypt", 2);
}

TEST(MatrixCallUndefinedOperand_frameworks, izaac_encrypt) {
    expect_undefined_operand_propagates("izaac_encrypt", 2);
}

TEST(MatrixCallUndefinedOperand_frameworks, izaac_fuzz_mutate) {
    expect_undefined_operand_propagates("izaac_fuzz_mutate", 1);
}

TEST(MatrixCallUndefinedOperand_frameworks, izaac_vrf_prove) {
    expect_undefined_operand_propagates("izaac_vrf_prove", 2);
}
