// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Odin Loch
//
// GENERATED by scripts/gen_matrix_call_tests.py from matrix_calls_manifest.json.
// Do not edit: run the two scripts. CI regenerates both and fails on a dirty
// tree, so a handler cannot land without its dispatch tests.

#include "matrix_call_test_support.hpp"

using namespace ms::interp::testing;

TEST(MatrixCallRegistration_signal, signal_autocorr) {
    expect_registered("signal_autocorr");
}

TEST(MatrixCallRegistration_signal, signal_coherence) {
    expect_registered("signal_coherence");
}

TEST(MatrixCallRegistration_signal, signal_conv2) {
    expect_registered("signal_conv2");
}

TEST(MatrixCallRegistration_signal, signal_deconv) {
    expect_registered("signal_deconv");
}

TEST(MatrixCallRegistration_signal, signal_envelope) {
    expect_registered("signal_envelope");
}

TEST(MatrixCallRegistration_signal, signal_firwin) {
    expect_registered("signal_firwin");
}

TEST(MatrixCallRegistration_signal, signal_firwin_highpass) {
    expect_registered("signal_firwin_highpass");
}

TEST(MatrixCallRegistration_signal, signal_hilbert) {
    expect_registered("signal_hilbert");
}

TEST(MatrixCallRegistration_signal, signal_instantaneous_phase) {
    expect_registered("signal_instantaneous_phase");
}

TEST(MatrixCallRegistration_signal, signal_lms) {
    expect_registered("signal_lms");
}

TEST(MatrixCallRegistration_signal, signal_lms_weights) {
    expect_registered("signal_lms_weights");
}

TEST(MatrixCallRegistration_signal, signal_resample) {
    expect_registered("signal_resample");
}

TEST(MatrixCallRegistration_signal, signal_savgol) {
    expect_registered("signal_savgol");
}

TEST(MatrixCallRegistration_signal, signal_sosfilt) {
    expect_registered("signal_sosfilt");
}

TEST(MatrixCallRegistration_signal, signal_unwrap) {
    expect_registered("signal_unwrap");
}

TEST(MatrixCallRegistration_signal, signal_xcorr) {
    expect_registered("signal_xcorr");
}

TEST(MatrixCallRegistration_signal, signal_xcov) {
    expect_registered("signal_xcov");
}

// accepts 2
TEST(MatrixCallArity_signal, signal_autocorr_rejects_3) {
    expect_arity_rejected("signal_autocorr", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 4
TEST(MatrixCallArity_signal, signal_coherence_rejects_5) {
    expect_arity_rejected("signal_coherence", 5,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_signal, signal_conv2_rejects_3) {
    expect_arity_rejected("signal_conv2", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_signal, signal_deconv_rejects_3) {
    expect_arity_rejected("signal_deconv", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_signal, signal_envelope_rejects_2) {
    expect_arity_rejected("signal_envelope", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2, 3
TEST(MatrixCallArity_signal, signal_firwin_rejects_4) {
    expect_arity_rejected("signal_firwin", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2, 3
TEST(MatrixCallArity_signal, signal_firwin_highpass_rejects_4) {
    expect_arity_rejected("signal_firwin_highpass", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_signal, signal_hilbert_rejects_2) {
    expect_arity_rejected("signal_hilbert", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_signal, signal_instantaneous_phase_rejects_2) {
    expect_arity_rejected("signal_instantaneous_phase", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 4
TEST(MatrixCallArity_signal, signal_lms_rejects_5) {
    expect_arity_rejected("signal_lms", 5,
                          "assign",
                          "unsupported matrix call");
}

// accepts 4
TEST(MatrixCallArity_signal, signal_lms_weights_rejects_5) {
    expect_arity_rejected("signal_lms_weights", 5,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3
TEST(MatrixCallArity_signal, signal_resample_rejects_4) {
    expect_arity_rejected("signal_resample", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3
TEST(MatrixCallArity_signal, signal_savgol_rejects_4) {
    expect_arity_rejected("signal_savgol", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_signal, signal_sosfilt_rejects_3) {
    expect_arity_rejected("signal_sosfilt", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_signal, signal_unwrap_rejects_2) {
    expect_arity_rejected("signal_unwrap", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3
TEST(MatrixCallArity_signal, signal_xcorr_rejects_4) {
    expect_arity_rejected("signal_xcorr", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3
TEST(MatrixCallArity_signal, signal_xcov_rejects_4) {
    expect_arity_rejected("signal_xcov", 4,
                          "assign",
                          "unsupported matrix call");
}

TEST(MatrixCallUndefinedOperand_signal, signal_autocorr) {
    expect_undefined_operand_propagates("signal_autocorr", 2);
}

TEST(MatrixCallUndefinedOperand_signal, signal_coherence) {
    expect_undefined_operand_propagates("signal_coherence", 4);
}

TEST(MatrixCallUndefinedOperand_signal, signal_conv2) {
    expect_undefined_operand_propagates("signal_conv2", 2);
}

TEST(MatrixCallUndefinedOperand_signal, signal_deconv) {
    expect_undefined_operand_propagates("signal_deconv", 2);
}

TEST(MatrixCallUndefinedOperand_signal, signal_envelope) {
    expect_undefined_operand_propagates("signal_envelope", 1);
}

TEST(MatrixCallUndefinedOperand_signal, signal_hilbert) {
    expect_undefined_operand_propagates("signal_hilbert", 1);
}

TEST(MatrixCallUndefinedOperand_signal, signal_instantaneous_phase) {
    expect_undefined_operand_propagates("signal_instantaneous_phase", 1);
}

TEST(MatrixCallUndefinedOperand_signal, signal_lms) {
    expect_undefined_operand_propagates("signal_lms", 4);
}

TEST(MatrixCallUndefinedOperand_signal, signal_lms_weights) {
    expect_undefined_operand_propagates("signal_lms_weights", 4);
}

TEST(MatrixCallUndefinedOperand_signal, signal_resample) {
    expect_undefined_operand_propagates("signal_resample", 3);
}

TEST(MatrixCallUndefinedOperand_signal, signal_savgol) {
    expect_undefined_operand_propagates("signal_savgol", 3);
}

TEST(MatrixCallUndefinedOperand_signal, signal_sosfilt) {
    expect_undefined_operand_propagates("signal_sosfilt", 2);
}

TEST(MatrixCallUndefinedOperand_signal, signal_unwrap) {
    expect_undefined_operand_propagates("signal_unwrap", 1);
}

TEST(MatrixCallUndefinedOperand_signal, signal_xcorr) {
    expect_undefined_operand_propagates("signal_xcorr", 3);
}

TEST(MatrixCallUndefinedOperand_signal, signal_xcov) {
    expect_undefined_operand_propagates("signal_xcov", 3);
}
