// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Odin Loch
//
// GENERATED by scripts/gen_matrix_call_tests.py from matrix_calls_manifest.json.
// Do not edit: run the two scripts. CI regenerates both and fails on a dirty
// tree, so a handler cannot land without its dispatch tests.

#include "matrix_call_test_support.hpp"

using namespace ms::interp::testing;

TEST(MatrixCallRegistration_repl, golomb_rice_decode_vec) {
    expect_registered("golomb_rice_decode_vec");
}

TEST(MatrixCallRegistration_repl, golomb_rice_encode_vec) {
    expect_registered("golomb_rice_encode_vec");
}

TEST(MatrixCallRegistration_repl, gray2rgb) {
    expect_registered("gray2rgb");
}

TEST(MatrixCallRegistration_repl, harris) {
    expect_registered("harris");
}

TEST(MatrixCallRegistration_repl, hough_circles) {
    expect_registered("hough_circles");
}

TEST(MatrixCallRegistration_repl, hough_lines) {
    expect_registered("hough_lines");
}

TEST(MatrixCallRegistration_repl, hsv2rgb) {
    expect_registered("hsv2rgb");
}

TEST(MatrixCallRegistration_repl, idst2) {
    expect_registered("idst2");
}

TEST(MatrixCallRegistration_repl, imadjust) {
    expect_registered("imadjust");
}

TEST(MatrixCallRegistration_repl, imbothat) {
    expect_registered("imbothat");
}

TEST(MatrixCallRegistration_repl, imclose) {
    expect_registered("imclose");
}

TEST(MatrixCallRegistration_repl, imcrop) {
    expect_registered("imcrop");
}

TEST(MatrixCallRegistration_repl, imdilate) {
    expect_registered("imdilate");
}

TEST(MatrixCallRegistration_repl, imerode) {
    expect_registered("imerode");
}

TEST(MatrixCallRegistration_repl, imfilter) {
    expect_registered("imfilter");
}

TEST(MatrixCallRegistration_repl, imflip) {
    expect_registered("imflip");
}

TEST(MatrixCallRegistration_repl, imgaussfilt) {
    expect_registered("imgaussfilt");
}

TEST(MatrixCallRegistration_repl, imgradient_morph) {
    expect_registered("imgradient_morph");
}

TEST(MatrixCallRegistration_repl, imhist) {
    expect_registered("imhist");
}

TEST(MatrixCallRegistration_repl, imopen) {
    expect_registered("imopen");
}

TEST(MatrixCallRegistration_repl, impad) {
    expect_registered("impad");
}

TEST(MatrixCallRegistration_repl, imresize) {
    expect_registered("imresize");
}

TEST(MatrixCallRegistration_repl, imrotate90) {
    expect_registered("imrotate90");
}

TEST(MatrixCallRegistration_repl, imtophat) {
    expect_registered("imtophat");
}

TEST(MatrixCallRegistration_repl, iradon) {
    expect_registered("iradon");
}

TEST(MatrixCallRegistration_repl, kruskal_wallis) {
    expect_registered("kruskal_wallis");
}

TEST(MatrixCallRegistration_repl, label_components) {
    expect_registered("label_components");
}

TEST(MatrixCallRegistration_repl, laplacian_of_gaussian) {
    expect_registered("laplacian_of_gaussian");
}

TEST(MatrixCallRegistration_repl, lsq) {
    expect_registered("lsq");
}

TEST(MatrixCallRegistration_repl, lz77_decode_vec) {
    expect_registered("lz77_decode_vec");
}

TEST(MatrixCallRegistration_repl, lz77_encode_vec) {
    expect_registered("lz77_encode_vec");
}

TEST(MatrixCallRegistration_repl, lzw_decode_vec) {
    expect_registered("lzw_decode_vec");
}

TEST(MatrixCallRegistration_repl, lzw_encode_vec) {
    expect_registered("lzw_encode_vec");
}

TEST(MatrixCallRegistration_repl, medfilt2) {
    expect_registered("medfilt2");
}

TEST(MatrixCallRegistration_repl, mpc_split) {
    expect_registered("mpc_split");
}

TEST(MatrixCallRegistration_repl, mtf_decode_vec) {
    expect_registered("mtf_decode_vec");
}

TEST(MatrixCallRegistration_repl, mtf_encode_vec) {
    expect_registered("mtf_encode_vec");
}

// accepts 3
TEST(MatrixCallArity_repl, golomb_rice_decode_vec_rejects_4) {
    expect_arity_rejected("golomb_rice_decode_vec", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_repl, golomb_rice_encode_vec_rejects_3) {
    expect_arity_rejected("golomb_rice_encode_vec", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_repl, gray2rgb_rejects_2) {
    expect_arity_rejected("gray2rgb", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1, 2, 3
TEST(MatrixCallArity_repl, harris_rejects_4) {
    expect_arity_rejected("harris", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1, 3
TEST(MatrixCallArity_repl, hough_circles_rejects_4) {
    expect_arity_rejected("hough_circles", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1, 2, 5
TEST(MatrixCallArity_repl, hough_lines_rejects_6) {
    expect_arity_rejected("hough_lines", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_repl, hsv2rgb_rejects_2) {
    expect_arity_rejected("hsv2rgb", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_repl, idst2_rejects_2) {
    expect_arity_rejected("idst2", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3, 5
TEST(MatrixCallArity_repl, imadjust_rejects_6) {
    expect_arity_rejected("imadjust", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1, 2
TEST(MatrixCallArity_repl, imbothat_rejects_3) {
    expect_arity_rejected("imbothat", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1, 2
TEST(MatrixCallArity_repl, imclose_rejects_3) {
    expect_arity_rejected("imclose", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 5
TEST(MatrixCallArity_repl, imcrop_rejects_6) {
    expect_arity_rejected("imcrop", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1, 2
TEST(MatrixCallArity_repl, imdilate_rejects_3) {
    expect_arity_rejected("imdilate", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1, 2
TEST(MatrixCallArity_repl, imerode_rejects_3) {
    expect_arity_rejected("imerode", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_repl, imfilter_rejects_3) {
    expect_arity_rejected("imfilter", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_repl, imflip_rejects_3) {
    expect_arity_rejected("imflip", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_repl, imgaussfilt_rejects_3) {
    expect_arity_rejected("imgaussfilt", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1, 2
TEST(MatrixCallArity_repl, imgradient_morph_rejects_3) {
    expect_arity_rejected("imgradient_morph", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1, 2
TEST(MatrixCallArity_repl, imhist_rejects_3) {
    expect_arity_rejected("imhist", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1, 2
TEST(MatrixCallArity_repl, imopen_rejects_3) {
    expect_arity_rejected("imopen", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2, 3
TEST(MatrixCallArity_repl, impad_rejects_4) {
    expect_arity_rejected("impad", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3
TEST(MatrixCallArity_repl, imresize_rejects_4) {
    expect_arity_rejected("imresize", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_repl, imrotate90_rejects_2) {
    expect_arity_rejected("imrotate90", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1, 2
TEST(MatrixCallArity_repl, imtophat_rejects_3) {
    expect_arity_rejected("imtophat", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_repl, iradon_rejects_3) {
    expect_arity_rejected("iradon", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_repl, kruskal_wallis_rejects_2) {
    expect_arity_rejected("kruskal_wallis", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_repl, label_components_rejects_2) {
    expect_arity_rejected("label_components", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_repl, laplacian_of_gaussian_rejects_3) {
    expect_arity_rejected("laplacian_of_gaussian", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_repl, lsq_rejects_3) {
    expect_arity_rejected("lsq", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_repl, lz77_decode_vec_rejects_2) {
    expect_arity_rejected("lz77_decode_vec", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_repl, lz77_encode_vec_rejects_2) {
    expect_arity_rejected("lz77_encode_vec", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_repl, lzw_decode_vec_rejects_2) {
    expect_arity_rejected("lzw_decode_vec", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_repl, lzw_encode_vec_rejects_2) {
    expect_arity_rejected("lzw_encode_vec", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_repl, medfilt2_rejects_3) {
    expect_arity_rejected("medfilt2", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3
TEST(MatrixCallArity_repl, mpc_split_rejects_4) {
    expect_arity_rejected("mpc_split", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_repl, mtf_decode_vec_rejects_2) {
    expect_arity_rejected("mtf_decode_vec", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_repl, mtf_encode_vec_rejects_2) {
    expect_arity_rejected("mtf_encode_vec", 2,
                          "assign",
                          "unsupported matrix call");
}

TEST(MatrixCallUndefinedOperand_repl, golomb_rice_decode_vec) {
    expect_undefined_operand_propagates("golomb_rice_decode_vec", 3);
}

TEST(MatrixCallUndefinedOperand_repl, golomb_rice_encode_vec) {
    expect_undefined_operand_propagates("golomb_rice_encode_vec", 2);
}

TEST(MatrixCallUndefinedOperand_repl, gray2rgb) {
    expect_undefined_operand_propagates("gray2rgb", 1);
}

TEST(MatrixCallUndefinedOperand_repl, harris) {
    expect_undefined_operand_propagates("harris", 1);
}

TEST(MatrixCallUndefinedOperand_repl, hough_circles) {
    expect_undefined_operand_propagates("hough_circles", 1);
}

TEST(MatrixCallUndefinedOperand_repl, hough_lines) {
    expect_undefined_operand_propagates("hough_lines", 1);
}

TEST(MatrixCallUndefinedOperand_repl, hsv2rgb) {
    expect_undefined_operand_propagates("hsv2rgb", 1);
}

TEST(MatrixCallUndefinedOperand_repl, idst2) {
    expect_undefined_operand_propagates("idst2", 1);
}

TEST(MatrixCallUndefinedOperand_repl, imadjust) {
    expect_undefined_operand_propagates("imadjust", 3);
}

TEST(MatrixCallUndefinedOperand_repl, imbothat) {
    expect_undefined_operand_propagates("imbothat", 1);
}

TEST(MatrixCallUndefinedOperand_repl, imclose) {
    expect_undefined_operand_propagates("imclose", 1);
}

TEST(MatrixCallUndefinedOperand_repl, imcrop) {
    expect_undefined_operand_propagates("imcrop", 5);
}

TEST(MatrixCallUndefinedOperand_repl, imdilate) {
    expect_undefined_operand_propagates("imdilate", 1);
}

TEST(MatrixCallUndefinedOperand_repl, imerode) {
    expect_undefined_operand_propagates("imerode", 1);
}

TEST(MatrixCallUndefinedOperand_repl, imfilter) {
    expect_undefined_operand_propagates("imfilter", 2);
}

TEST(MatrixCallUndefinedOperand_repl, imflip) {
    expect_undefined_operand_propagates("imflip", 2);
}

TEST(MatrixCallUndefinedOperand_repl, imgaussfilt) {
    expect_undefined_operand_propagates("imgaussfilt", 2);
}

TEST(MatrixCallUndefinedOperand_repl, imgradient_morph) {
    expect_undefined_operand_propagates("imgradient_morph", 1);
}

TEST(MatrixCallUndefinedOperand_repl, imhist) {
    expect_undefined_operand_propagates("imhist", 1);
}

TEST(MatrixCallUndefinedOperand_repl, imopen) {
    expect_undefined_operand_propagates("imopen", 1);
}

TEST(MatrixCallUndefinedOperand_repl, impad) {
    expect_undefined_operand_propagates("impad", 2);
}

TEST(MatrixCallUndefinedOperand_repl, imresize) {
    expect_undefined_operand_propagates("imresize", 3);
}

TEST(MatrixCallUndefinedOperand_repl, imrotate90) {
    expect_undefined_operand_propagates("imrotate90", 1);
}

TEST(MatrixCallUndefinedOperand_repl, imtophat) {
    expect_undefined_operand_propagates("imtophat", 1);
}

TEST(MatrixCallUndefinedOperand_repl, iradon) {
    expect_undefined_operand_propagates("iradon", 2);
}

TEST(MatrixCallUndefinedOperand_repl, kruskal_wallis) {
    expect_undefined_operand_propagates("kruskal_wallis", 1);
}

TEST(MatrixCallUndefinedOperand_repl, label_components) {
    expect_undefined_operand_propagates("label_components", 1);
}

TEST(MatrixCallUndefinedOperand_repl, laplacian_of_gaussian) {
    expect_undefined_operand_propagates("laplacian_of_gaussian", 2);
}

TEST(MatrixCallUndefinedOperand_repl, lsq) {
    expect_undefined_operand_propagates("lsq", 2);
}

TEST(MatrixCallUndefinedOperand_repl, lz77_decode_vec) {
    expect_undefined_operand_propagates("lz77_decode_vec", 1);
}

TEST(MatrixCallUndefinedOperand_repl, lz77_encode_vec) {
    expect_undefined_operand_propagates("lz77_encode_vec", 1);
}

TEST(MatrixCallUndefinedOperand_repl, lzw_decode_vec) {
    expect_undefined_operand_propagates("lzw_decode_vec", 1);
}

TEST(MatrixCallUndefinedOperand_repl, lzw_encode_vec) {
    expect_undefined_operand_propagates("lzw_encode_vec", 1);
}

TEST(MatrixCallUndefinedOperand_repl, medfilt2) {
    expect_undefined_operand_propagates("medfilt2", 2);
}

TEST(MatrixCallUndefinedOperand_repl, mtf_decode_vec) {
    expect_undefined_operand_propagates("mtf_decode_vec", 1);
}

TEST(MatrixCallUndefinedOperand_repl, mtf_encode_vec) {
    expect_undefined_operand_propagates("mtf_encode_vec", 1);
}

TEST(MatrixCallBadOperandAt_repl, imfilter_arg1) {
    expect_bad_operand_at("imfilter", 2, 1);
}

TEST(MatrixCallBadOperandAt_repl, iradon_arg1) {
    expect_bad_operand_at("iradon", 2, 1);
}

TEST(MatrixCallBadOperandAt_repl, lsq_arg1) {
    expect_bad_operand_at("lsq", 2, 1);
}
