// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Odin Loch
//
// GENERATED by scripts/gen_matrix_call_tests.py from matrix_calls_manifest.json.
// Do not edit: run the two scripts. CI regenerates both and fails on a dirty
// tree, so a handler cannot land without its dispatch tests.

#include "matrix_call_test_support.hpp"

using namespace ms::interp::testing;

TEST(MatrixCallRegistration_topo, topo_alpha_complex) {
    expect_registered("topo_alpha_complex");
}

TEST(MatrixCallRegistration_topo, topo_betti_curve) {
    expect_registered("topo_betti_curve");
}

TEST(MatrixCallRegistration_topo, topo_cech_complex) {
    expect_registered("topo_cech_complex");
}

TEST(MatrixCallRegistration_topo, topo_pairwise_distances) {
    expect_registered("topo_pairwise_distances");
}

TEST(MatrixCallRegistration_topo, topo_persistence_landscape) {
    expect_registered("topo_persistence_landscape");
}

TEST(MatrixCallRegistration_topo, topo_select_landmarks) {
    expect_registered("topo_select_landmarks");
}

TEST(MatrixCallRegistration_topo, topo_simplicial_betti) {
    expect_registered("topo_simplicial_betti");
}

TEST(MatrixCallRegistration_topo, topo_simplicial_counts) {
    expect_registered("topo_simplicial_counts");
}

TEST(MatrixCallRegistration_topo, topo_vietoris_rips) {
    expect_registered("topo_vietoris_rips");
}

TEST(MatrixCallRegistration_topo, topo_witness_complex) {
    expect_registered("topo_witness_complex");
}

// accepts 2, 3
TEST(MatrixCallArity_topo, topo_alpha_complex_rejects_4) {
    expect_arity_rejected("topo_alpha_complex", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3
TEST(MatrixCallArity_topo, topo_betti_curve_rejects_4) {
    expect_arity_rejected("topo_betti_curve", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2, 3
TEST(MatrixCallArity_topo, topo_cech_complex_rejects_4) {
    expect_arity_rejected("topo_cech_complex", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_topo, topo_pairwise_distances_rejects_2) {
    expect_arity_rejected("topo_pairwise_distances", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3, 5
TEST(MatrixCallArity_topo, topo_persistence_landscape_rejects_6) {
    expect_arity_rejected("topo_persistence_landscape", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2, 3
TEST(MatrixCallArity_topo, topo_select_landmarks_rejects_4) {
    expect_arity_rejected("topo_select_landmarks", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_topo, topo_simplicial_betti_rejects_2) {
    expect_arity_rejected("topo_simplicial_betti", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_topo, topo_simplicial_counts_rejects_2) {
    expect_arity_rejected("topo_simplicial_counts", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2, 3
TEST(MatrixCallArity_topo, topo_vietoris_rips_rejects_4) {
    expect_arity_rejected("topo_vietoris_rips", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3, 4
TEST(MatrixCallArity_topo, topo_witness_complex_rejects_5) {
    expect_arity_rejected("topo_witness_complex", 5,
                          "assign",
                          "unsupported matrix call");
}

TEST(MatrixCallUndefinedOperand_topo, topo_alpha_complex) {
    expect_undefined_operand_propagates("topo_alpha_complex", 2);
}

TEST(MatrixCallUndefinedOperand_topo, topo_betti_curve) {
    expect_undefined_operand_propagates("topo_betti_curve", 3);
}

TEST(MatrixCallUndefinedOperand_topo, topo_cech_complex) {
    expect_undefined_operand_propagates("topo_cech_complex", 2);
}

TEST(MatrixCallUndefinedOperand_topo, topo_pairwise_distances) {
    expect_undefined_operand_propagates("topo_pairwise_distances", 1);
}

TEST(MatrixCallUndefinedOperand_topo, topo_persistence_landscape) {
    expect_undefined_operand_propagates("topo_persistence_landscape", 3);
}

TEST(MatrixCallUndefinedOperand_topo, topo_select_landmarks) {
    expect_undefined_operand_propagates("topo_select_landmarks", 2);
}

TEST(MatrixCallUndefinedOperand_topo, topo_simplicial_betti) {
    expect_undefined_operand_propagates("topo_simplicial_betti", 1);
}

TEST(MatrixCallUndefinedOperand_topo, topo_simplicial_counts) {
    expect_undefined_operand_propagates("topo_simplicial_counts", 1);
}

TEST(MatrixCallUndefinedOperand_topo, topo_vietoris_rips) {
    expect_undefined_operand_propagates("topo_vietoris_rips", 2);
}

TEST(MatrixCallUndefinedOperand_topo, topo_witness_complex) {
    expect_undefined_operand_propagates("topo_witness_complex", 3);
}
