// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Odin Loch
//
// GENERATED by scripts/gen_matrix_call_tests.py from matrix_calls_manifest.json.
// Do not edit: run the two scripts. CI regenerates both and fails on a dirty
// tree, so a handler cannot land without its dispatch tests.

#include "matrix_call_test_support.hpp"

using namespace ms::interp::testing;

TEST(MatrixCallRegistration_core, mat_col) {
    expect_registered("mat_col");
}

TEST(MatrixCallRegistration_core, mat_reshape) {
    expect_registered("mat_reshape");
}

TEST(MatrixCallRegistration_core, mat_row) {
    expect_registered("mat_row");
}

TEST(MatrixCallRegistration_core, mat_submatrix) {
    expect_registered("mat_submatrix");
}

TEST(MatrixCallRegistration_core, sparse_add) {
    expect_registered("sparse_add");
}

TEST(MatrixCallRegistration_core, sparse_from_coo) {
    expect_registered("sparse_from_coo");
}

TEST(MatrixCallRegistration_core, sparse_spmv) {
    expect_registered("sparse_spmv");
}

TEST(MatrixCallRegistration_core, sparse_to_dense) {
    expect_registered("sparse_to_dense");
}

// accepts 2
TEST(MatrixCallArity_core, mat_col_rejects_3) {
    expect_arity_rejected("mat_col", 3,
                          "mat_col",
                          "expected mat_col(A, j)");
}

// accepts 3
TEST(MatrixCallArity_core, mat_reshape_rejects_4) {
    expect_arity_rejected("mat_reshape", 4,
                          "mat_reshape",
                          "expected mat_reshape(A, rows, cols)");
}

// accepts 2
TEST(MatrixCallArity_core, mat_row_rejects_3) {
    expect_arity_rejected("mat_row", 3,
                          "mat_row",
                          "expected mat_row(A, i)");
}

// accepts 5
TEST(MatrixCallArity_core, mat_submatrix_rejects_6) {
    expect_arity_rejected("mat_submatrix", 6,
                          "mat_submatrix",
                          "expected mat_submatrix(A, r0, c0, rows, cols)");
}

// accepts 2
TEST(MatrixCallArity_core, sparse_add_rejects_3) {
    expect_arity_rejected("sparse_add", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 5
TEST(MatrixCallArity_core, sparse_from_coo_rejects_6) {
    expect_arity_rejected("sparse_from_coo", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_core, sparse_spmv_rejects_3) {
    expect_arity_rejected("sparse_spmv", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_core, sparse_to_dense_rejects_2) {
    expect_arity_rejected("sparse_to_dense", 2,
                          "assign",
                          "unsupported matrix call");
}

TEST(MatrixCallUndefinedOperand_core, mat_col) {
    expect_undefined_operand_propagates("mat_col", 2);
}

TEST(MatrixCallUndefinedOperand_core, mat_reshape) {
    expect_undefined_operand_propagates("mat_reshape", 3);
}

TEST(MatrixCallUndefinedOperand_core, mat_row) {
    expect_undefined_operand_propagates("mat_row", 2);
}

TEST(MatrixCallUndefinedOperand_core, mat_submatrix) {
    expect_undefined_operand_propagates("mat_submatrix", 5);
}

TEST(MatrixCallUndefinedOperand_core, sparse_add) {
    expect_undefined_operand_propagates("sparse_add", 2);
}

TEST(MatrixCallUndefinedOperand_core, sparse_spmv) {
    expect_undefined_operand_propagates("sparse_spmv", 2);
}

TEST(MatrixCallUndefinedOperand_core, sparse_to_dense) {
    expect_undefined_operand_propagates("sparse_to_dense", 1);
}
