// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Odin Loch
//
// GENERATED by scripts/gen_matrix_call_tests.py from matrix_calls_manifest.json.
// Do not edit: run the two scripts. CI regenerates both and fails on a dirty
// tree, so a handler cannot land without its dispatch tests.

#include "matrix_call_test_support.hpp"

using namespace ms::interp::testing;

TEST(MatrixCallRegistration_poly, poly_cheb_expand) {
    expect_registered("poly_cheb_expand");
}

TEST(MatrixCallRegistration_poly, poly_deriv) {
    expect_registered("poly_deriv");
}

TEST(MatrixCallRegistration_poly, poly_div_quot) {
    expect_registered("poly_div_quot");
}

TEST(MatrixCallRegistration_poly, poly_eval_at) {
    expect_registered("poly_eval_at");
}

TEST(MatrixCallRegistration_poly, poly_factor) {
    expect_registered("poly_factor");
}

TEST(MatrixCallRegistration_poly, poly_factor_rational) {
    expect_registered("poly_factor_rational");
}

TEST(MatrixCallRegistration_poly, poly_fit) {
    expect_registered("poly_fit");
}

TEST(MatrixCallRegistration_poly, poly_gcd) {
    expect_registered("poly_gcd");
}

TEST(MatrixCallRegistration_poly, poly_interp_hermite) {
    expect_registered("poly_interp_hermite");
}

TEST(MatrixCallRegistration_poly, poly_interp_newton) {
    expect_registered("poly_interp_newton");
}

TEST(MatrixCallRegistration_poly, poly_lagrange) {
    expect_registered("poly_lagrange");
}

TEST(MatrixCallRegistration_poly, poly_lcm) {
    expect_registered("poly_lcm");
}

TEST(MatrixCallRegistration_poly, poly_mod) {
    expect_registered("poly_mod");
}

TEST(MatrixCallRegistration_poly, poly_monic) {
    expect_registered("poly_monic");
}

TEST(MatrixCallRegistration_poly, poly_partial_fractions) {
    expect_registered("poly_partial_fractions");
}

TEST(MatrixCallRegistration_poly, poly_rational_roots) {
    expect_registered("poly_rational_roots");
}

TEST(MatrixCallRegistration_poly, poly_reverse) {
    expect_registered("poly_reverse");
}

TEST(MatrixCallRegistration_poly, poly_roots) {
    expect_registered("poly_roots");
}

TEST(MatrixCallRegistration_poly, poly_squarefree) {
    expect_registered("poly_squarefree");
}

TEST(MatrixCallRegistration_poly, poly_sylvester) {
    expect_registered("poly_sylvester");
}

// accepts 4
TEST(MatrixCallArity_poly, poly_cheb_expand_rejects_5) {
    expect_arity_rejected("poly_cheb_expand", 5,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_poly, poly_deriv_rejects_2) {
    expect_arity_rejected("poly_deriv", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_poly, poly_div_quot_rejects_3) {
    expect_arity_rejected("poly_div_quot", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_poly, poly_eval_at_rejects_3) {
    expect_arity_rejected("poly_eval_at", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_poly, poly_factor_rejects_2) {
    expect_arity_rejected("poly_factor", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_poly, poly_factor_rational_rejects_2) {
    expect_arity_rejected("poly_factor_rational", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3
TEST(MatrixCallArity_poly, poly_fit_rejects_4) {
    expect_arity_rejected("poly_fit", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_poly, poly_gcd_rejects_3) {
    expect_arity_rejected("poly_gcd", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3
TEST(MatrixCallArity_poly, poly_interp_hermite_rejects_4) {
    expect_arity_rejected("poly_interp_hermite", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_poly, poly_interp_newton_rejects_3) {
    expect_arity_rejected("poly_interp_newton", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_poly, poly_lagrange_rejects_3) {
    expect_arity_rejected("poly_lagrange", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_poly, poly_lcm_rejects_3) {
    expect_arity_rejected("poly_lcm", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_poly, poly_mod_rejects_3) {
    expect_arity_rejected("poly_mod", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_poly, poly_monic_rejects_2) {
    expect_arity_rejected("poly_monic", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_poly, poly_partial_fractions_rejects_3) {
    expect_arity_rejected("poly_partial_fractions", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_poly, poly_rational_roots_rejects_2) {
    expect_arity_rejected("poly_rational_roots", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_poly, poly_reverse_rejects_2) {
    expect_arity_rejected("poly_reverse", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_poly, poly_roots_rejects_2) {
    expect_arity_rejected("poly_roots", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_poly, poly_squarefree_rejects_2) {
    expect_arity_rejected("poly_squarefree", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_poly, poly_sylvester_rejects_3) {
    expect_arity_rejected("poly_sylvester", 3,
                          "assign",
                          "unsupported matrix call");
}

TEST(MatrixCallUndefinedOperand_poly, poly_cheb_expand) {
    expect_undefined_operand_propagates("poly_cheb_expand", 4);
}

TEST(MatrixCallUndefinedOperand_poly, poly_deriv) {
    expect_undefined_operand_propagates("poly_deriv", 1);
}

TEST(MatrixCallUndefinedOperand_poly, poly_div_quot) {
    expect_undefined_operand_propagates("poly_div_quot", 2);
}

TEST(MatrixCallUndefinedOperand_poly, poly_eval_at) {
    expect_undefined_operand_propagates("poly_eval_at", 2);
}

TEST(MatrixCallUndefinedOperand_poly, poly_factor) {
    expect_undefined_operand_propagates("poly_factor", 1);
}

TEST(MatrixCallUndefinedOperand_poly, poly_factor_rational) {
    expect_undefined_operand_propagates("poly_factor_rational", 1);
}

TEST(MatrixCallUndefinedOperand_poly, poly_fit) {
    expect_undefined_operand_propagates("poly_fit", 3);
}

TEST(MatrixCallUndefinedOperand_poly, poly_gcd) {
    expect_undefined_operand_propagates("poly_gcd", 2);
}

TEST(MatrixCallUndefinedOperand_poly, poly_interp_hermite) {
    expect_undefined_operand_propagates("poly_interp_hermite", 3);
}

TEST(MatrixCallUndefinedOperand_poly, poly_interp_newton) {
    expect_undefined_operand_propagates("poly_interp_newton", 2);
}

TEST(MatrixCallUndefinedOperand_poly, poly_lagrange) {
    expect_undefined_operand_propagates("poly_lagrange", 2);
}

TEST(MatrixCallUndefinedOperand_poly, poly_lcm) {
    expect_undefined_operand_propagates("poly_lcm", 2);
}

TEST(MatrixCallUndefinedOperand_poly, poly_mod) {
    expect_undefined_operand_propagates("poly_mod", 2);
}

TEST(MatrixCallUndefinedOperand_poly, poly_monic) {
    expect_undefined_operand_propagates("poly_monic", 1);
}

TEST(MatrixCallUndefinedOperand_poly, poly_partial_fractions) {
    expect_undefined_operand_propagates("poly_partial_fractions", 2);
}

TEST(MatrixCallUndefinedOperand_poly, poly_rational_roots) {
    expect_undefined_operand_propagates("poly_rational_roots", 1);
}

TEST(MatrixCallUndefinedOperand_poly, poly_reverse) {
    expect_undefined_operand_propagates("poly_reverse", 1);
}

TEST(MatrixCallUndefinedOperand_poly, poly_roots) {
    expect_undefined_operand_propagates("poly_roots", 1);
}

TEST(MatrixCallUndefinedOperand_poly, poly_squarefree) {
    expect_undefined_operand_propagates("poly_squarefree", 1);
}

TEST(MatrixCallUndefinedOperand_poly, poly_sylvester) {
    expect_undefined_operand_propagates("poly_sylvester", 2);
}

TEST(MatrixCallBadOperandAt_poly, poly_div_quot_arg1) {
    expect_bad_operand_at("poly_div_quot", 2, 1);
}

TEST(MatrixCallBadOperandAt_poly, poly_eval_at_arg1) {
    expect_bad_operand_at("poly_eval_at", 2, 1);
}

TEST(MatrixCallBadOperandAt_poly, poly_fit_arg1) {
    expect_bad_operand_at("poly_fit", 3, 1);
}

TEST(MatrixCallBadOperandAt_poly, poly_gcd_arg1) {
    expect_bad_operand_at("poly_gcd", 2, 1);
}

TEST(MatrixCallBadOperandAt_poly, poly_interp_hermite_arg1) {
    expect_bad_operand_at("poly_interp_hermite", 3, 1);
}

TEST(MatrixCallBadOperandAt_poly, poly_interp_hermite_arg2) {
    expect_bad_operand_at("poly_interp_hermite", 3, 2);
}

TEST(MatrixCallBadOperandAt_poly, poly_interp_newton_arg1) {
    expect_bad_operand_at("poly_interp_newton", 2, 1);
}

TEST(MatrixCallBadOperandAt_poly, poly_lagrange_arg1) {
    expect_bad_operand_at("poly_lagrange", 2, 1);
}

TEST(MatrixCallBadOperandAt_poly, poly_lcm_arg1) {
    expect_bad_operand_at("poly_lcm", 2, 1);
}

TEST(MatrixCallBadOperandAt_poly, poly_mod_arg1) {
    expect_bad_operand_at("poly_mod", 2, 1);
}

TEST(MatrixCallBadOperandAt_poly, poly_partial_fractions_arg1) {
    expect_bad_operand_at("poly_partial_fractions", 2, 1);
}

TEST(MatrixCallBadOperandAt_poly, poly_sylvester_arg1) {
    expect_bad_operand_at("poly_sylvester", 2, 1);
}
