// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Odin Loch
//
// GENERATED by scripts/gen_matrix_call_tests.py from matrix_calls_manifest.json.
// Do not edit: run the two scripts. CI regenerates both and fails on a dirty
// tree, so a handler cannot land without its dispatch tests.

#include "matrix_call_test_support.hpp"

using namespace ms::interp::testing;

TEST(MatrixCallRegistration_control, control_bode) {
    expect_registered("control_bode");
}

TEST(MatrixCallRegistration_control, control_c2d) {
    expect_registered("control_c2d");
}

TEST(MatrixCallRegistration_control, control_c2d_b) {
    expect_registered("control_c2d_b");
}

TEST(MatrixCallRegistration_control, control_c2d_euler) {
    expect_registered("control_c2d_euler");
}

TEST(MatrixCallRegistration_control, control_c2d_tf) {
    expect_registered("control_c2d_tf");
}

TEST(MatrixCallRegistration_control, control_c2d_tf_tustin) {
    expect_registered("control_c2d_tf_tustin");
}

TEST(MatrixCallRegistration_control, control_c2d_tustin) {
    expect_registered("control_c2d_tustin");
}

TEST(MatrixCallRegistration_control, control_ctrb) {
    expect_registered("control_ctrb");
}

TEST(MatrixCallRegistration_control, control_ctrb_gram) {
    expect_registered("control_ctrb_gram");
}

TEST(MatrixCallRegistration_control, control_d2c) {
    expect_registered("control_d2c");
}

TEST(MatrixCallRegistration_control, control_d2c_euler) {
    expect_registered("control_d2c_euler");
}

TEST(MatrixCallRegistration_control, control_d2c_tf) {
    expect_registered("control_d2c_tf");
}

TEST(MatrixCallRegistration_control, control_d2c_tf_tustin) {
    expect_registered("control_d2c_tf_tustin");
}

TEST(MatrixCallRegistration_control, control_d2c_tustin) {
    expect_registered("control_d2c_tustin");
}

TEST(MatrixCallRegistration_control, control_feedback) {
    expect_registered("control_feedback");
}

TEST(MatrixCallRegistration_control, control_impulse_response) {
    expect_registered("control_impulse_response");
}

TEST(MatrixCallRegistration_control, control_kalman_predict) {
    expect_registered("control_kalman_predict");
}

TEST(MatrixCallRegistration_control, control_kalman_predict_cov) {
    expect_registered("control_kalman_predict_cov");
}

TEST(MatrixCallRegistration_control, control_kalman_update) {
    expect_registered("control_kalman_update");
}

TEST(MatrixCallRegistration_control, control_kalman_update_cov) {
    expect_registered("control_kalman_update_cov");
}

TEST(MatrixCallRegistration_control, control_obsv) {
    expect_registered("control_obsv");
}

TEST(MatrixCallRegistration_control, control_obsv_gram) {
    expect_registered("control_obsv_gram");
}

TEST(MatrixCallRegistration_control, control_parallel) {
    expect_registered("control_parallel");
}

TEST(MatrixCallRegistration_control, control_series) {
    expect_registered("control_series");
}

TEST(MatrixCallRegistration_control, control_ss2tf) {
    expect_registered("control_ss2tf");
}

TEST(MatrixCallRegistration_control, control_step_response) {
    expect_registered("control_step_response");
}

TEST(MatrixCallRegistration_control, control_tf2ss) {
    expect_registered("control_tf2ss");
}

// accepts 3
TEST(MatrixCallArity_control, control_bode_rejects_4) {
    expect_arity_rejected("control_bode", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 5
TEST(MatrixCallArity_control, control_c2d_rejects_6) {
    expect_arity_rejected("control_c2d", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 5
TEST(MatrixCallArity_control, control_c2d_b_rejects_6) {
    expect_arity_rejected("control_c2d_b", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 5
TEST(MatrixCallArity_control, control_c2d_euler_rejects_6) {
    expect_arity_rejected("control_c2d_euler", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3
TEST(MatrixCallArity_control, control_c2d_tf_rejects_4) {
    expect_arity_rejected("control_c2d_tf", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3
TEST(MatrixCallArity_control, control_c2d_tf_tustin_rejects_4) {
    expect_arity_rejected("control_c2d_tf_tustin", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 5
TEST(MatrixCallArity_control, control_c2d_tustin_rejects_6) {
    expect_arity_rejected("control_c2d_tustin", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_control, control_ctrb_rejects_3) {
    expect_arity_rejected("control_ctrb", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_control, control_ctrb_gram_rejects_3) {
    expect_arity_rejected("control_ctrb_gram", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 5
TEST(MatrixCallArity_control, control_d2c_rejects_6) {
    expect_arity_rejected("control_d2c", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 5
TEST(MatrixCallArity_control, control_d2c_euler_rejects_6) {
    expect_arity_rejected("control_d2c_euler", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3
TEST(MatrixCallArity_control, control_d2c_tf_rejects_4) {
    expect_arity_rejected("control_d2c_tf", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3
TEST(MatrixCallArity_control, control_d2c_tf_tustin_rejects_4) {
    expect_arity_rejected("control_d2c_tf_tustin", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 5
TEST(MatrixCallArity_control, control_d2c_tustin_rejects_6) {
    expect_arity_rejected("control_d2c_tustin", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 4, 5
TEST(MatrixCallArity_control, control_feedback_rejects_6) {
    expect_arity_rejected("control_feedback", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2, 3, 4
TEST(MatrixCallArity_control, control_impulse_response_rejects_5) {
    expect_arity_rejected("control_impulse_response", 5,
                          "assign",
                          "unsupported matrix call");
}

// accepts 4
TEST(MatrixCallArity_control, control_kalman_predict_rejects_5) {
    expect_arity_rejected("control_kalman_predict", 5,
                          "assign",
                          "unsupported matrix call");
}

// accepts 4
TEST(MatrixCallArity_control, control_kalman_predict_cov_rejects_5) {
    expect_arity_rejected("control_kalman_predict_cov", 5,
                          "assign",
                          "unsupported matrix call");
}

// accepts 5
TEST(MatrixCallArity_control, control_kalman_update_rejects_6) {
    expect_arity_rejected("control_kalman_update", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 5
TEST(MatrixCallArity_control, control_kalman_update_cov_rejects_6) {
    expect_arity_rejected("control_kalman_update_cov", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_control, control_obsv_rejects_3) {
    expect_arity_rejected("control_obsv", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_control, control_obsv_gram_rejects_3) {
    expect_arity_rejected("control_obsv_gram", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 4
TEST(MatrixCallArity_control, control_parallel_rejects_5) {
    expect_arity_rejected("control_parallel", 5,
                          "assign",
                          "unsupported matrix call");
}

// accepts 4
TEST(MatrixCallArity_control, control_series_rejects_5) {
    expect_arity_rejected("control_series", 5,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_control, control_ss2tf_rejects_2) {
    expect_arity_rejected("control_ss2tf", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2, 3, 4
TEST(MatrixCallArity_control, control_step_response_rejects_5) {
    expect_arity_rejected("control_step_response", 5,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_control, control_tf2ss_rejects_3) {
    expect_arity_rejected("control_tf2ss", 3,
                          "assign",
                          "unsupported matrix call");
}

TEST(MatrixCallUndefinedOperand_control, control_bode) {
    expect_undefined_operand_propagates("control_bode", 3);
}

TEST(MatrixCallUndefinedOperand_control, control_c2d) {
    expect_undefined_operand_propagates("control_c2d", 5);
}

TEST(MatrixCallUndefinedOperand_control, control_c2d_b) {
    expect_undefined_operand_propagates("control_c2d_b", 5);
}

TEST(MatrixCallUndefinedOperand_control, control_c2d_euler) {
    expect_undefined_operand_propagates("control_c2d_euler", 5);
}

TEST(MatrixCallUndefinedOperand_control, control_c2d_tf) {
    expect_undefined_operand_propagates("control_c2d_tf", 3);
}

TEST(MatrixCallUndefinedOperand_control, control_c2d_tf_tustin) {
    expect_undefined_operand_propagates("control_c2d_tf_tustin", 3);
}

TEST(MatrixCallUndefinedOperand_control, control_c2d_tustin) {
    expect_undefined_operand_propagates("control_c2d_tustin", 5);
}

TEST(MatrixCallUndefinedOperand_control, control_ctrb) {
    expect_undefined_operand_propagates("control_ctrb", 2);
}

TEST(MatrixCallUndefinedOperand_control, control_ctrb_gram) {
    expect_undefined_operand_propagates("control_ctrb_gram", 2);
}

TEST(MatrixCallUndefinedOperand_control, control_d2c) {
    expect_undefined_operand_propagates("control_d2c", 5);
}

TEST(MatrixCallUndefinedOperand_control, control_d2c_euler) {
    expect_undefined_operand_propagates("control_d2c_euler", 5);
}

TEST(MatrixCallUndefinedOperand_control, control_d2c_tf) {
    expect_undefined_operand_propagates("control_d2c_tf", 3);
}

TEST(MatrixCallUndefinedOperand_control, control_d2c_tf_tustin) {
    expect_undefined_operand_propagates("control_d2c_tf_tustin", 3);
}

TEST(MatrixCallUndefinedOperand_control, control_d2c_tustin) {
    expect_undefined_operand_propagates("control_d2c_tustin", 5);
}

TEST(MatrixCallUndefinedOperand_control, control_feedback) {
    expect_undefined_operand_propagates("control_feedback", 4);
}

TEST(MatrixCallUndefinedOperand_control, control_impulse_response) {
    expect_undefined_operand_propagates("control_impulse_response", 2);
}

TEST(MatrixCallUndefinedOperand_control, control_kalman_predict) {
    expect_undefined_operand_propagates("control_kalman_predict", 4);
}

TEST(MatrixCallUndefinedOperand_control, control_kalman_predict_cov) {
    expect_undefined_operand_propagates("control_kalman_predict_cov", 4);
}

TEST(MatrixCallUndefinedOperand_control, control_kalman_update) {
    expect_undefined_operand_propagates("control_kalman_update", 5);
}

TEST(MatrixCallUndefinedOperand_control, control_kalman_update_cov) {
    expect_undefined_operand_propagates("control_kalman_update_cov", 5);
}

TEST(MatrixCallUndefinedOperand_control, control_obsv) {
    expect_undefined_operand_propagates("control_obsv", 2);
}

TEST(MatrixCallUndefinedOperand_control, control_obsv_gram) {
    expect_undefined_operand_propagates("control_obsv_gram", 2);
}

TEST(MatrixCallUndefinedOperand_control, control_parallel) {
    expect_undefined_operand_propagates("control_parallel", 4);
}

TEST(MatrixCallUndefinedOperand_control, control_series) {
    expect_undefined_operand_propagates("control_series", 4);
}

TEST(MatrixCallUndefinedOperand_control, control_ss2tf) {
    expect_undefined_operand_propagates("control_ss2tf", 1);
}

TEST(MatrixCallUndefinedOperand_control, control_step_response) {
    expect_undefined_operand_propagates("control_step_response", 2);
}

TEST(MatrixCallUndefinedOperand_control, control_tf2ss) {
    expect_undefined_operand_propagates("control_tf2ss", 2);
}

TEST(MatrixCallBadOperandAt_control, control_bode_arg1) {
    expect_bad_operand_at("control_bode", 3, 1);
}

TEST(MatrixCallBadOperandAt_control, control_c2d_arg1) {
    expect_bad_operand_at("control_c2d", 5, 1);
}

TEST(MatrixCallBadOperandAt_control, control_c2d_arg2) {
    expect_bad_operand_at("control_c2d", 5, 2);
}

TEST(MatrixCallBadOperandAt_control, control_c2d_arg3) {
    expect_bad_operand_at("control_c2d", 5, 3);
}

TEST(MatrixCallBadOperandAt_control, control_c2d_b_arg1) {
    expect_bad_operand_at("control_c2d_b", 5, 1);
}

TEST(MatrixCallBadOperandAt_control, control_c2d_b_arg2) {
    expect_bad_operand_at("control_c2d_b", 5, 2);
}

TEST(MatrixCallBadOperandAt_control, control_c2d_b_arg3) {
    expect_bad_operand_at("control_c2d_b", 5, 3);
}

TEST(MatrixCallBadOperandAt_control, control_c2d_euler_arg1) {
    expect_bad_operand_at("control_c2d_euler", 5, 1);
}

TEST(MatrixCallBadOperandAt_control, control_c2d_euler_arg2) {
    expect_bad_operand_at("control_c2d_euler", 5, 2);
}

TEST(MatrixCallBadOperandAt_control, control_c2d_euler_arg3) {
    expect_bad_operand_at("control_c2d_euler", 5, 3);
}

TEST(MatrixCallBadOperandAt_control, control_c2d_tf_arg1) {
    expect_bad_operand_at("control_c2d_tf", 3, 1);
}

TEST(MatrixCallBadOperandAt_control, control_c2d_tf_tustin_arg1) {
    expect_bad_operand_at("control_c2d_tf_tustin", 3, 1);
}

TEST(MatrixCallBadOperandAt_control, control_c2d_tustin_arg1) {
    expect_bad_operand_at("control_c2d_tustin", 5, 1);
}

TEST(MatrixCallBadOperandAt_control, control_c2d_tustin_arg2) {
    expect_bad_operand_at("control_c2d_tustin", 5, 2);
}

TEST(MatrixCallBadOperandAt_control, control_c2d_tustin_arg3) {
    expect_bad_operand_at("control_c2d_tustin", 5, 3);
}

TEST(MatrixCallBadOperandAt_control, control_ctrb_arg1) {
    expect_bad_operand_at("control_ctrb", 2, 1);
}

TEST(MatrixCallBadOperandAt_control, control_ctrb_gram_arg1) {
    expect_bad_operand_at("control_ctrb_gram", 2, 1);
}

TEST(MatrixCallBadOperandAt_control, control_d2c_arg1) {
    expect_bad_operand_at("control_d2c", 5, 1);
}

TEST(MatrixCallBadOperandAt_control, control_d2c_arg2) {
    expect_bad_operand_at("control_d2c", 5, 2);
}

TEST(MatrixCallBadOperandAt_control, control_d2c_arg3) {
    expect_bad_operand_at("control_d2c", 5, 3);
}

TEST(MatrixCallBadOperandAt_control, control_d2c_euler_arg1) {
    expect_bad_operand_at("control_d2c_euler", 5, 1);
}

TEST(MatrixCallBadOperandAt_control, control_d2c_euler_arg2) {
    expect_bad_operand_at("control_d2c_euler", 5, 2);
}

TEST(MatrixCallBadOperandAt_control, control_d2c_euler_arg3) {
    expect_bad_operand_at("control_d2c_euler", 5, 3);
}

TEST(MatrixCallBadOperandAt_control, control_d2c_tf_arg1) {
    expect_bad_operand_at("control_d2c_tf", 3, 1);
}

TEST(MatrixCallBadOperandAt_control, control_d2c_tf_tustin_arg1) {
    expect_bad_operand_at("control_d2c_tf_tustin", 3, 1);
}

TEST(MatrixCallBadOperandAt_control, control_d2c_tustin_arg1) {
    expect_bad_operand_at("control_d2c_tustin", 5, 1);
}

TEST(MatrixCallBadOperandAt_control, control_d2c_tustin_arg2) {
    expect_bad_operand_at("control_d2c_tustin", 5, 2);
}

TEST(MatrixCallBadOperandAt_control, control_d2c_tustin_arg3) {
    expect_bad_operand_at("control_d2c_tustin", 5, 3);
}

TEST(MatrixCallBadOperandAt_control, control_feedback_arg1) {
    expect_bad_operand_at("control_feedback", 5, 1);
}

TEST(MatrixCallBadOperandAt_control, control_feedback_arg2) {
    expect_bad_operand_at("control_feedback", 5, 2);
}

TEST(MatrixCallBadOperandAt_control, control_feedback_arg3) {
    expect_bad_operand_at("control_feedback", 5, 3);
}

TEST(MatrixCallBadOperandAt_control, control_impulse_response_arg1) {
    expect_bad_operand_at("control_impulse_response", 4, 1);
}

TEST(MatrixCallBadOperandAt_control, control_kalman_predict_arg1) {
    expect_bad_operand_at("control_kalman_predict", 4, 1);
}

TEST(MatrixCallBadOperandAt_control, control_kalman_predict_arg2) {
    expect_bad_operand_at("control_kalman_predict", 4, 2);
}

TEST(MatrixCallBadOperandAt_control, control_kalman_predict_arg3) {
    expect_bad_operand_at("control_kalman_predict", 4, 3);
}

TEST(MatrixCallBadOperandAt_control, control_kalman_predict_cov_arg1) {
    expect_bad_operand_at("control_kalman_predict_cov", 4, 1);
}

TEST(MatrixCallBadOperandAt_control, control_kalman_predict_cov_arg2) {
    expect_bad_operand_at("control_kalman_predict_cov", 4, 2);
}

TEST(MatrixCallBadOperandAt_control, control_kalman_predict_cov_arg3) {
    expect_bad_operand_at("control_kalman_predict_cov", 4, 3);
}

TEST(MatrixCallBadOperandAt_control, control_kalman_update_arg1) {
    expect_bad_operand_at("control_kalman_update", 5, 1);
}

TEST(MatrixCallBadOperandAt_control, control_kalman_update_arg2) {
    expect_bad_operand_at("control_kalman_update", 5, 2);
}

TEST(MatrixCallBadOperandAt_control, control_kalman_update_arg3) {
    expect_bad_operand_at("control_kalman_update", 5, 3);
}

TEST(MatrixCallBadOperandAt_control, control_kalman_update_arg4) {
    expect_bad_operand_at("control_kalman_update", 5, 4);
}

TEST(MatrixCallBadOperandAt_control, control_kalman_update_cov_arg1) {
    expect_bad_operand_at("control_kalman_update_cov", 5, 1);
}

TEST(MatrixCallBadOperandAt_control, control_kalman_update_cov_arg2) {
    expect_bad_operand_at("control_kalman_update_cov", 5, 2);
}

TEST(MatrixCallBadOperandAt_control, control_kalman_update_cov_arg3) {
    expect_bad_operand_at("control_kalman_update_cov", 5, 3);
}

TEST(MatrixCallBadOperandAt_control, control_kalman_update_cov_arg4) {
    expect_bad_operand_at("control_kalman_update_cov", 5, 4);
}

TEST(MatrixCallBadOperandAt_control, control_obsv_arg1) {
    expect_bad_operand_at("control_obsv", 2, 1);
}

TEST(MatrixCallBadOperandAt_control, control_obsv_gram_arg1) {
    expect_bad_operand_at("control_obsv_gram", 2, 1);
}

TEST(MatrixCallBadOperandAt_control, control_parallel_arg1) {
    expect_bad_operand_at("control_parallel", 4, 1);
}

TEST(MatrixCallBadOperandAt_control, control_parallel_arg2) {
    expect_bad_operand_at("control_parallel", 4, 2);
}

TEST(MatrixCallBadOperandAt_control, control_parallel_arg3) {
    expect_bad_operand_at("control_parallel", 4, 3);
}

TEST(MatrixCallBadOperandAt_control, control_series_arg1) {
    expect_bad_operand_at("control_series", 4, 1);
}

TEST(MatrixCallBadOperandAt_control, control_series_arg2) {
    expect_bad_operand_at("control_series", 4, 2);
}

TEST(MatrixCallBadOperandAt_control, control_series_arg3) {
    expect_bad_operand_at("control_series", 4, 3);
}

TEST(MatrixCallBadOperandAt_control, control_step_response_arg1) {
    expect_bad_operand_at("control_step_response", 4, 1);
}

TEST(MatrixCallBadOperandAt_control, control_tf2ss_arg1) {
    expect_bad_operand_at("control_tf2ss", 2, 1);
}
