// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Odin Loch
//
// GENERATED by scripts/gen_matrix_call_tests.py from matrix_calls_manifest.json.
// Do not edit: run the two scripts. CI regenerates both and fails on a dirty
// tree, so a handler cannot land without its dispatch tests.

#include "matrix_call_test_support.hpp"

using namespace ms::interp::testing;

TEST(MatrixCallRegistration_stats, stats_arfit) {
    expect_registered("stats_arfit");
}

TEST(MatrixCallRegistration_stats, stats_bartlett) {
    expect_registered("stats_bartlett");
}

TEST(MatrixCallRegistration_stats, stats_bootstrap_ci) {
    expect_registered("stats_bootstrap_ci");
}

TEST(MatrixCallRegistration_stats, stats_fligner) {
    expect_registered("stats_fligner");
}

TEST(MatrixCallRegistration_stats, stats_friedman) {
    expect_registered("stats_friedman");
}

TEST(MatrixCallRegistration_stats, stats_jarque_bera) {
    expect_registered("stats_jarque_bera");
}

TEST(MatrixCallRegistration_stats, stats_kde) {
    expect_registered("stats_kde");
}

TEST(MatrixCallRegistration_stats, stats_ks_2sample) {
    expect_registered("stats_ks_2sample");
}

TEST(MatrixCallRegistration_stats, stats_levene) {
    expect_registered("stats_levene");
}

TEST(MatrixCallRegistration_stats, stats_linear_regression) {
    expect_registered("stats_linear_regression");
}

TEST(MatrixCallRegistration_stats, stats_ljung_box) {
    expect_registered("stats_ljung_box");
}

TEST(MatrixCallRegistration_stats, stats_mann_whitney_u) {
    expect_registered("stats_mann_whitney_u");
}

TEST(MatrixCallRegistration_stats, stats_multiple_regression) {
    expect_registered("stats_multiple_regression");
}

TEST(MatrixCallRegistration_stats, stats_one_way_anova) {
    expect_registered("stats_one_way_anova");
}

TEST(MatrixCallRegistration_stats, stats_pacf) {
    expect_registered("stats_pacf");
}

TEST(MatrixCallRegistration_stats, stats_shapiro_wilk) {
    expect_registered("stats_shapiro_wilk");
}

TEST(MatrixCallRegistration_stats, stats_wilcoxon_signed_rank) {
    expect_registered("stats_wilcoxon_signed_rank");
}

// accepts 2
TEST(MatrixCallArity_stats, stats_arfit_rejects_3) {
    expect_arity_rejected("stats_arfit", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_stats, stats_bartlett_rejects_2) {
    expect_arity_rejected("stats_bartlett", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_stats, stats_bootstrap_ci_rejects_2) {
    expect_arity_rejected("stats_bootstrap_ci", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_stats, stats_fligner_rejects_2) {
    expect_arity_rejected("stats_fligner", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_stats, stats_friedman_rejects_2) {
    expect_arity_rejected("stats_friedman", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_stats, stats_jarque_bera_rejects_2) {
    expect_arity_rejected("stats_jarque_bera", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3, 4
TEST(MatrixCallArity_stats, stats_kde_rejects_5) {
    expect_arity_rejected("stats_kde", 5,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_stats, stats_ks_2sample_rejects_3) {
    expect_arity_rejected("stats_ks_2sample", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_stats, stats_levene_rejects_2) {
    expect_arity_rejected("stats_levene", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_stats, stats_linear_regression_rejects_3) {
    expect_arity_rejected("stats_linear_regression", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_stats, stats_ljung_box_rejects_3) {
    expect_arity_rejected("stats_ljung_box", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_stats, stats_mann_whitney_u_rejects_3) {
    expect_arity_rejected("stats_mann_whitney_u", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_stats, stats_multiple_regression_rejects_3) {
    expect_arity_rejected("stats_multiple_regression", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_stats, stats_one_way_anova_rejects_2) {
    expect_arity_rejected("stats_one_way_anova", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_stats, stats_pacf_rejects_3) {
    expect_arity_rejected("stats_pacf", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_stats, stats_shapiro_wilk_rejects_2) {
    expect_arity_rejected("stats_shapiro_wilk", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_stats, stats_wilcoxon_signed_rank_rejects_3) {
    expect_arity_rejected("stats_wilcoxon_signed_rank", 3,
                          "assign",
                          "unsupported matrix call");
}

TEST(MatrixCallUndefinedOperand_stats, stats_arfit) {
    expect_undefined_operand_propagates("stats_arfit", 2);
}

TEST(MatrixCallUndefinedOperand_stats, stats_bartlett) {
    expect_undefined_operand_propagates("stats_bartlett", 1);
}

TEST(MatrixCallUndefinedOperand_stats, stats_bootstrap_ci) {
    expect_undefined_operand_propagates("stats_bootstrap_ci", 1);
}

TEST(MatrixCallUndefinedOperand_stats, stats_fligner) {
    expect_undefined_operand_propagates("stats_fligner", 1);
}

TEST(MatrixCallUndefinedOperand_stats, stats_friedman) {
    expect_undefined_operand_propagates("stats_friedman", 1);
}

TEST(MatrixCallUndefinedOperand_stats, stats_jarque_bera) {
    expect_undefined_operand_propagates("stats_jarque_bera", 1);
}

TEST(MatrixCallUndefinedOperand_stats, stats_kde) {
    expect_undefined_operand_propagates("stats_kde", 3);
}

TEST(MatrixCallUndefinedOperand_stats, stats_ks_2sample) {
    expect_undefined_operand_propagates("stats_ks_2sample", 2);
}

TEST(MatrixCallUndefinedOperand_stats, stats_levene) {
    expect_undefined_operand_propagates("stats_levene", 1);
}

TEST(MatrixCallUndefinedOperand_stats, stats_linear_regression) {
    expect_undefined_operand_propagates("stats_linear_regression", 2);
}

TEST(MatrixCallUndefinedOperand_stats, stats_ljung_box) {
    expect_undefined_operand_propagates("stats_ljung_box", 2);
}

TEST(MatrixCallUndefinedOperand_stats, stats_mann_whitney_u) {
    expect_undefined_operand_propagates("stats_mann_whitney_u", 2);
}

TEST(MatrixCallUndefinedOperand_stats, stats_multiple_regression) {
    expect_undefined_operand_propagates("stats_multiple_regression", 2);
}

TEST(MatrixCallUndefinedOperand_stats, stats_one_way_anova) {
    expect_undefined_operand_propagates("stats_one_way_anova", 1);
}

TEST(MatrixCallUndefinedOperand_stats, stats_pacf) {
    expect_undefined_operand_propagates("stats_pacf", 2);
}

TEST(MatrixCallUndefinedOperand_stats, stats_shapiro_wilk) {
    expect_undefined_operand_propagates("stats_shapiro_wilk", 1);
}

TEST(MatrixCallUndefinedOperand_stats, stats_wilcoxon_signed_rank) {
    expect_undefined_operand_propagates("stats_wilcoxon_signed_rank", 2);
}

TEST(MatrixCallBadOperandAt_stats, stats_kde_arg1) {
    expect_bad_operand_at("stats_kde", 4, 1);
}

TEST(MatrixCallBadOperandAt_stats, stats_ks_2sample_arg1) {
    expect_bad_operand_at("stats_ks_2sample", 2, 1);
}

TEST(MatrixCallBadOperandAt_stats, stats_linear_regression_arg1) {
    expect_bad_operand_at("stats_linear_regression", 2, 1);
}

TEST(MatrixCallBadOperandAt_stats, stats_mann_whitney_u_arg1) {
    expect_bad_operand_at("stats_mann_whitney_u", 2, 1);
}

TEST(MatrixCallBadOperandAt_stats, stats_multiple_regression_arg1) {
    expect_bad_operand_at("stats_multiple_regression", 2, 1);
}

TEST(MatrixCallBadOperandAt_stats, stats_wilcoxon_signed_rank_arg1) {
    expect_bad_operand_at("stats_wilcoxon_signed_rank", 2, 1);
}
