// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Odin Loch
//
// GENERATED by scripts/gen_matrix_call_tests.py from matrix_calls_manifest.json.
// Do not edit: run the two scripts. CI regenerates both and fails on a dirty
// tree, so a handler cannot land without its dispatch tests.

#include "matrix_call_test_support.hpp"

using namespace ms::interp::testing;

TEST(MatrixCallRegistration_fem, assemble_stiffness_2d) {
    expect_registered("assemble_stiffness_2d");
}

TEST(MatrixCallRegistration_fem, assemble_stiffness_3d) {
    expect_registered("assemble_stiffness_3d");
}

TEST(MatrixCallRegistration_fem, fem_apply_dirichlet) {
    expect_registered("fem_apply_dirichlet");
}

TEST(MatrixCallRegistration_fem, fem_lagrange_deriv) {
    expect_registered("fem_lagrange_deriv");
}

TEST(MatrixCallRegistration_fem, fem_lagrange_eval) {
    expect_registered("fem_lagrange_eval");
}

TEST(MatrixCallRegistration_fem, fem_load_1d) {
    expect_registered("fem_load_1d");
}

TEST(MatrixCallRegistration_fem, fem_load_2d) {
    expect_registered("fem_load_2d");
}

TEST(MatrixCallRegistration_fem, fem_load_3d) {
    expect_registered("fem_load_3d");
}

TEST(MatrixCallRegistration_fem, fem_mesh1d) {
    expect_registered("fem_mesh1d");
}

TEST(MatrixCallRegistration_fem, fem_mesh2d) {
    expect_registered("fem_mesh2d");
}

TEST(MatrixCallRegistration_fem, fem_mesh2d_rectangular) {
    expect_registered("fem_mesh2d_rectangular");
}

TEST(MatrixCallRegistration_fem, fem_mesh3d) {
    expect_registered("fem_mesh3d");
}

TEST(MatrixCallRegistration_fem, fem_mesh3d_box) {
    expect_registered("fem_mesh3d_box");
}

TEST(MatrixCallRegistration_fem, fem_poisson1d) {
    expect_registered("fem_poisson1d");
}

TEST(MatrixCallRegistration_fem, fem_poisson2d) {
    expect_registered("fem_poisson2d");
}

TEST(MatrixCallRegistration_fem, fem_poisson3d) {
    expect_registered("fem_poisson3d");
}

TEST(MatrixCallRegistration_fem, fem_solve) {
    expect_registered("fem_solve");
}

TEST(MatrixCallRegistration_fem, fem_solve_3d) {
    expect_registered("fem_solve_3d");
}

TEST(MatrixCallRegistration_fem, fem_stiffness_1d) {
    expect_registered("fem_stiffness_1d");
}

TEST(MatrixCallRegistration_fem, fem_stiffness_2d) {
    expect_registered("fem_stiffness_2d");
}

TEST(MatrixCallRegistration_fem, fem_stiffness_3d) {
    expect_registered("fem_stiffness_3d");
}

// accepts 1
TEST(MatrixCallArity_fem, assemble_stiffness_2d_rejects_2) {
    expect_arity_rejected("assemble_stiffness_2d", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_fem, assemble_stiffness_3d_rejects_2) {
    expect_arity_rejected("assemble_stiffness_3d", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 4
TEST(MatrixCallArity_fem, fem_apply_dirichlet_rejects_5) {
    expect_arity_rejected("fem_apply_dirichlet", 5,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_fem, fem_lagrange_deriv_rejects_2) {
    expect_arity_rejected("fem_lagrange_deriv", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_fem, fem_lagrange_eval_rejects_2) {
    expect_arity_rejected("fem_lagrange_eval", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_fem, fem_load_1d_rejects_3) {
    expect_arity_rejected("fem_load_1d", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_fem, fem_load_2d_rejects_3) {
    expect_arity_rejected("fem_load_2d", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_fem, fem_load_3d_rejects_3) {
    expect_arity_rejected("fem_load_3d", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3
TEST(MatrixCallArity_fem, fem_mesh1d_rejects_4) {
    expect_arity_rejected("fem_mesh1d", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 6
TEST(MatrixCallArity_fem, fem_mesh2d_rejects_7) {
    expect_arity_rejected("fem_mesh2d", 7,
                          "assign",
                          "unsupported matrix call");
}

// accepts 6
TEST(MatrixCallArity_fem, fem_mesh2d_rectangular_rejects_7) {
    expect_arity_rejected("fem_mesh2d_rectangular", 7,
                          "assign",
                          "unsupported matrix call");
}

// accepts 9
TEST(MatrixCallArity_fem, fem_mesh3d_rejects_10) {
    expect_arity_rejected("fem_mesh3d", 10,
                          "assign",
                          "unsupported matrix call");
}

// accepts 9
TEST(MatrixCallArity_fem, fem_mesh3d_box_rejects_10) {
    expect_arity_rejected("fem_mesh3d_box", 10,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_fem, fem_poisson1d_rejects_2) {
    expect_arity_rejected("fem_poisson1d", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_fem, fem_poisson2d_rejects_3) {
    expect_arity_rejected("fem_poisson2d", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3
TEST(MatrixCallArity_fem, fem_poisson3d_rejects_4) {
    expect_arity_rejected("fem_poisson3d", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_fem, fem_solve_rejects_3) {
    expect_arity_rejected("fem_solve", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_fem, fem_solve_3d_rejects_3) {
    expect_arity_rejected("fem_solve_3d", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_fem, fem_stiffness_1d_rejects_2) {
    expect_arity_rejected("fem_stiffness_1d", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_fem, fem_stiffness_2d_rejects_2) {
    expect_arity_rejected("fem_stiffness_2d", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_fem, fem_stiffness_3d_rejects_2) {
    expect_arity_rejected("fem_stiffness_3d", 2,
                          "assign",
                          "unsupported matrix call");
}

TEST(MatrixCallUndefinedOperand_fem, assemble_stiffness_2d) {
    expect_undefined_operand_propagates("assemble_stiffness_2d", 1);
}

TEST(MatrixCallUndefinedOperand_fem, assemble_stiffness_3d) {
    expect_undefined_operand_propagates("assemble_stiffness_3d", 1);
}

TEST(MatrixCallUndefinedOperand_fem, fem_apply_dirichlet) {
    expect_undefined_operand_propagates("fem_apply_dirichlet", 4);
}

TEST(MatrixCallUndefinedOperand_fem, fem_load_1d) {
    expect_undefined_operand_propagates("fem_load_1d", 2);
}

TEST(MatrixCallUndefinedOperand_fem, fem_load_2d) {
    expect_undefined_operand_propagates("fem_load_2d", 2);
}

TEST(MatrixCallUndefinedOperand_fem, fem_load_3d) {
    expect_undefined_operand_propagates("fem_load_3d", 2);
}

TEST(MatrixCallUndefinedOperand_fem, fem_solve) {
    expect_undefined_operand_propagates("fem_solve", 2);
}

TEST(MatrixCallUndefinedOperand_fem, fem_solve_3d) {
    expect_undefined_operand_propagates("fem_solve_3d", 2);
}

TEST(MatrixCallUndefinedOperand_fem, fem_stiffness_1d) {
    expect_undefined_operand_propagates("fem_stiffness_1d", 1);
}

TEST(MatrixCallUndefinedOperand_fem, fem_stiffness_2d) {
    expect_undefined_operand_propagates("fem_stiffness_2d", 1);
}

TEST(MatrixCallUndefinedOperand_fem, fem_stiffness_3d) {
    expect_undefined_operand_propagates("fem_stiffness_3d", 1);
}
