// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Odin Loch
//
// GENERATED by scripts/gen_matrix_call_tests.py from matrix_calls_manifest.json.
// Do not edit: run the two scripts. CI regenerates both and fails on a dirty
// tree, so a handler cannot land without its dispatch tests.

#include "matrix_call_test_support.hpp"

using namespace ms::interp::testing;

TEST(MatrixCallRegistration_distributed, dist_bicgstab) {
    expect_registered("dist_bicgstab");
}

TEST(MatrixCallRegistration_distributed, dist_cg) {
    expect_registered("dist_cg");
}

TEST(MatrixCallRegistration_distributed, dist_gmres) {
    expect_registered("dist_gmres");
}

TEST(MatrixCallRegistration_distributed, dist_jacobi) {
    expect_registered("dist_jacobi");
}

TEST(MatrixCallRegistration_distributed, dist_lsmr) {
    expect_registered("dist_lsmr");
}

TEST(MatrixCallRegistration_distributed, dist_lsqr) {
    expect_registered("dist_lsqr");
}

TEST(MatrixCallRegistration_distributed, dist_matmul) {
    expect_registered("dist_matmul");
}

TEST(MatrixCallRegistration_distributed, dist_minres) {
    expect_registered("dist_minres");
}

TEST(MatrixCallRegistration_distributed, dist_qmr) {
    expect_registered("dist_qmr");
}

TEST(MatrixCallRegistration_distributed, dist_solve) {
    expect_registered("dist_solve");
}

TEST(MatrixCallRegistration_distributed, dist_tfqmr) {
    expect_registered("dist_tfqmr");
}

// accepts 2
TEST(MatrixCallArity_distributed, dist_bicgstab_rejects_3) {
    expect_arity_rejected("dist_bicgstab", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_distributed, dist_cg_rejects_3) {
    expect_arity_rejected("dist_cg", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_distributed, dist_gmres_rejects_3) {
    expect_arity_rejected("dist_gmres", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_distributed, dist_jacobi_rejects_3) {
    expect_arity_rejected("dist_jacobi", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_distributed, dist_lsmr_rejects_3) {
    expect_arity_rejected("dist_lsmr", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_distributed, dist_lsqr_rejects_3) {
    expect_arity_rejected("dist_lsqr", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_distributed, dist_matmul_rejects_3) {
    expect_arity_rejected("dist_matmul", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_distributed, dist_minres_rejects_3) {
    expect_arity_rejected("dist_minres", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_distributed, dist_qmr_rejects_3) {
    expect_arity_rejected("dist_qmr", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_distributed, dist_solve_rejects_3) {
    expect_arity_rejected("dist_solve", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_distributed, dist_tfqmr_rejects_3) {
    expect_arity_rejected("dist_tfqmr", 3,
                          "assign",
                          "unsupported matrix call");
}

TEST(MatrixCallUndefinedOperand_distributed, dist_bicgstab) {
    expect_undefined_operand_propagates("dist_bicgstab", 2);
}

TEST(MatrixCallUndefinedOperand_distributed, dist_cg) {
    expect_undefined_operand_propagates("dist_cg", 2);
}

TEST(MatrixCallUndefinedOperand_distributed, dist_gmres) {
    expect_undefined_operand_propagates("dist_gmres", 2);
}

TEST(MatrixCallUndefinedOperand_distributed, dist_jacobi) {
    expect_undefined_operand_propagates("dist_jacobi", 2);
}

TEST(MatrixCallUndefinedOperand_distributed, dist_lsmr) {
    expect_undefined_operand_propagates("dist_lsmr", 2);
}

TEST(MatrixCallUndefinedOperand_distributed, dist_lsqr) {
    expect_undefined_operand_propagates("dist_lsqr", 2);
}

TEST(MatrixCallUndefinedOperand_distributed, dist_matmul) {
    expect_undefined_operand_propagates("dist_matmul", 2);
}

TEST(MatrixCallUndefinedOperand_distributed, dist_minres) {
    expect_undefined_operand_propagates("dist_minres", 2);
}

TEST(MatrixCallUndefinedOperand_distributed, dist_qmr) {
    expect_undefined_operand_propagates("dist_qmr", 2);
}

TEST(MatrixCallUndefinedOperand_distributed, dist_solve) {
    expect_undefined_operand_propagates("dist_solve", 2);
}

TEST(MatrixCallUndefinedOperand_distributed, dist_tfqmr) {
    expect_undefined_operand_propagates("dist_tfqmr", 2);
}

TEST(MatrixCallBadOperandAt_distributed, dist_bicgstab_arg1) {
    expect_bad_operand_at("dist_bicgstab", 2, 1);
}

TEST(MatrixCallBadOperandAt_distributed, dist_cg_arg1) {
    expect_bad_operand_at("dist_cg", 2, 1);
}

TEST(MatrixCallBadOperandAt_distributed, dist_gmres_arg1) {
    expect_bad_operand_at("dist_gmres", 2, 1);
}

TEST(MatrixCallBadOperandAt_distributed, dist_jacobi_arg1) {
    expect_bad_operand_at("dist_jacobi", 2, 1);
}

TEST(MatrixCallBadOperandAt_distributed, dist_lsmr_arg1) {
    expect_bad_operand_at("dist_lsmr", 2, 1);
}

TEST(MatrixCallBadOperandAt_distributed, dist_lsqr_arg1) {
    expect_bad_operand_at("dist_lsqr", 2, 1);
}

TEST(MatrixCallBadOperandAt_distributed, dist_matmul_arg1) {
    expect_bad_operand_at("dist_matmul", 2, 1);
}

TEST(MatrixCallBadOperandAt_distributed, dist_minres_arg1) {
    expect_bad_operand_at("dist_minres", 2, 1);
}

TEST(MatrixCallBadOperandAt_distributed, dist_qmr_arg1) {
    expect_bad_operand_at("dist_qmr", 2, 1);
}

TEST(MatrixCallBadOperandAt_distributed, dist_solve_arg1) {
    expect_bad_operand_at("dist_solve", 2, 1);
}

TEST(MatrixCallBadOperandAt_distributed, dist_tfqmr_arg1) {
    expect_bad_operand_at("dist_tfqmr", 2, 1);
}
