// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Odin Loch
//
// GENERATED by scripts/gen_matrix_call_tests.py from matrix_calls_manifest.json.
// Do not edit: run the two scripts. CI regenerates both and fails on a dirty
// tree, so a handler cannot land without its dispatch tests.

#include "matrix_call_test_support.hpp"

using namespace ms::interp::testing;

TEST(MatrixCallRegistration_diffgeo, diffgeo_geodesic_euclidean) {
    expect_registered("diffgeo_geodesic_euclidean");
}

TEST(MatrixCallRegistration_diffgeo, diffgeo_surface_normal_sphere) {
    expect_registered("diffgeo_surface_normal_sphere");
}

// accepts 5
TEST(MatrixCallArity_diffgeo, diffgeo_geodesic_euclidean_rejects_6) {
    expect_arity_rejected("diffgeo_geodesic_euclidean", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_diffgeo, diffgeo_surface_normal_sphere_rejects_3) {
    expect_arity_rejected("diffgeo_surface_normal_sphere", 3,
                          "assign",
                          "unsupported matrix call");
}
