// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Odin Loch
//
// GENERATED by scripts/gen_matrix_call_tests.py from matrix_calls_manifest.json.
// Do not edit: run the two scripts. CI regenerates both and fails on a dirty
// tree, so a handler cannot land without its dispatch tests.

#include "matrix_call_test_support.hpp"

using namespace ms::interp::testing;

TEST(MatrixCallRegistration_fft, dft_magnitude) {
    expect_registered("dft_magnitude");
}

TEST(MatrixCallRegistration_fft, fft_dct2) {
    expect_registered("fft_dct2");
}

TEST(MatrixCallRegistration_fft, fft_dft) {
    expect_registered("fft_dft");
}

TEST(MatrixCallRegistration_fft, fft_dst2) {
    expect_registered("fft_dst2");
}

TEST(MatrixCallRegistration_fft, fft_fft2) {
    expect_registered("fft_fft2");
}

TEST(MatrixCallRegistration_fft, fft_goertzel) {
    expect_registered("fft_goertzel");
}

TEST(MatrixCallRegistration_fft, fft_idct2) {
    expect_registered("fft_idct2");
}

TEST(MatrixCallRegistration_fft, fft_ifft) {
    expect_registered("fft_ifft");
}

TEST(MatrixCallRegistration_fft, fft_rfft) {
    expect_registered("fft_rfft");
}

TEST(MatrixCallRegistration_fft, fftfreq) {
    expect_registered("fftfreq");
}

TEST(MatrixCallRegistration_fft, fftshift) {
    expect_registered("fftshift");
}

TEST(MatrixCallRegistration_fft, ifft2) {
    expect_registered("ifft2");
}

TEST(MatrixCallRegistration_fft, ifftshift) {
    expect_registered("ifftshift");
}

TEST(MatrixCallRegistration_fft, rfftfreq) {
    expect_registered("rfftfreq");
}

// accepts 1
TEST(MatrixCallArity_fft, dft_magnitude_rejects_2) {
    expect_arity_rejected("dft_magnitude", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_fft, fft_dct2_rejects_2) {
    expect_arity_rejected("fft_dct2", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_fft, fft_dft_rejects_2) {
    expect_arity_rejected("fft_dft", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_fft, fft_dst2_rejects_2) {
    expect_arity_rejected("fft_dst2", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_fft, fft_fft2_rejects_2) {
    expect_arity_rejected("fft_fft2", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3
TEST(MatrixCallArity_fft, fft_goertzel_rejects_4) {
    expect_arity_rejected("fft_goertzel", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_fft, fft_idct2_rejects_2) {
    expect_arity_rejected("fft_idct2", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_fft, fft_ifft_rejects_2) {
    expect_arity_rejected("fft_ifft", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_fft, fft_rfft_rejects_2) {
    expect_arity_rejected("fft_rfft", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1, 2
TEST(MatrixCallArity_fft, fftfreq_rejects_3) {
    expect_arity_rejected("fftfreq", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_fft, fftshift_rejects_2) {
    expect_arity_rejected("fftshift", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_fft, ifft2_rejects_2) {
    expect_arity_rejected("ifft2", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_fft, ifftshift_rejects_2) {
    expect_arity_rejected("ifftshift", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1, 2
TEST(MatrixCallArity_fft, rfftfreq_rejects_3) {
    expect_arity_rejected("rfftfreq", 3,
                          "assign",
                          "unsupported matrix call");
}

TEST(MatrixCallUndefinedOperand_fft, dft_magnitude) {
    expect_undefined_operand_propagates("dft_magnitude", 1);
}

TEST(MatrixCallUndefinedOperand_fft, fft_dct2) {
    expect_undefined_operand_propagates("fft_dct2", 1);
}

TEST(MatrixCallUndefinedOperand_fft, fft_dft) {
    expect_undefined_operand_propagates("fft_dft", 1);
}

TEST(MatrixCallUndefinedOperand_fft, fft_dst2) {
    expect_undefined_operand_propagates("fft_dst2", 1);
}

TEST(MatrixCallUndefinedOperand_fft, fft_fft2) {
    expect_undefined_operand_propagates("fft_fft2", 1);
}

TEST(MatrixCallUndefinedOperand_fft, fft_goertzel) {
    expect_undefined_operand_propagates("fft_goertzel", 3);
}

TEST(MatrixCallUndefinedOperand_fft, fft_idct2) {
    expect_undefined_operand_propagates("fft_idct2", 1);
}

TEST(MatrixCallUndefinedOperand_fft, fft_ifft) {
    expect_undefined_operand_propagates("fft_ifft", 1);
}

TEST(MatrixCallUndefinedOperand_fft, fft_rfft) {
    expect_undefined_operand_propagates("fft_rfft", 1);
}

TEST(MatrixCallUndefinedOperand_fft, fftshift) {
    expect_undefined_operand_propagates("fftshift", 1);
}

TEST(MatrixCallUndefinedOperand_fft, ifft2) {
    expect_undefined_operand_propagates("ifft2", 1);
}

TEST(MatrixCallUndefinedOperand_fft, ifftshift) {
    expect_undefined_operand_propagates("ifftshift", 1);
}
