// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Odin Loch
//
// GENERATED by scripts/gen_matrix_call_tests.py from matrix_calls_manifest.json.
// Do not edit: run the two scripts. CI regenerates both and fails on a dirty
// tree, so a handler cannot land without its dispatch tests.

#include "matrix_call_test_support.hpp"

using namespace ms::interp::testing;

TEST(MatrixCallRegistration_compress, ans_decode_vec) {
    expect_registered("ans_decode_vec");
}

TEST(MatrixCallRegistration_compress, ans_encode_vec) {
    expect_registered("ans_encode_vec");
}

TEST(MatrixCallRegistration_compress, arithmetic_decode_vec) {
    expect_registered("arithmetic_decode_vec");
}

TEST(MatrixCallRegistration_compress, arithmetic_encode_vec) {
    expect_registered("arithmetic_encode_vec");
}

TEST(MatrixCallRegistration_compress, bwt_decode_vec) {
    expect_registered("bwt_decode_vec");
}

TEST(MatrixCallRegistration_compress, bwt_encode_vec) {
    expect_registered("bwt_encode_vec");
}

TEST(MatrixCallRegistration_compress, bzip2_compress_vec) {
    expect_registered("bzip2_compress_vec");
}

TEST(MatrixCallRegistration_compress, bzip2_decompress_vec) {
    expect_registered("bzip2_decompress_vec");
}

TEST(MatrixCallRegistration_compress, compress_bits_to_bytes) {
    expect_registered("compress_bits_to_bytes");
}

TEST(MatrixCallRegistration_compress, compress_bytes_to_bits) {
    expect_registered("compress_bytes_to_bits");
}

TEST(MatrixCallRegistration_compress, delta_decode_vec) {
    expect_registered("delta_decode_vec");
}

TEST(MatrixCallRegistration_compress, delta_encode_vec) {
    expect_registered("delta_encode_vec");
}

TEST(MatrixCallRegistration_compress, huffman_decode_vec) {
    expect_registered("huffman_decode_vec");
}

TEST(MatrixCallRegistration_compress, huffman_encode_vec) {
    expect_registered("huffman_encode_vec");
}

TEST(MatrixCallRegistration_compress, rle_decode_vec) {
    expect_registered("rle_decode_vec");
}

TEST(MatrixCallRegistration_compress, rle_encode_vec) {
    expect_registered("rle_encode_vec");
}

TEST(MatrixCallRegistration_compress, run_length_decode_vec) {
    expect_registered("run_length_decode_vec");
}

TEST(MatrixCallRegistration_compress, run_length_encode_vec) {
    expect_registered("run_length_encode_vec");
}

TEST(MatrixCallRegistration_compress, wavelet_compress_vec) {
    expect_registered("wavelet_compress_vec");
}

TEST(MatrixCallRegistration_compress, wavelet_decompress_vec) {
    expect_registered("wavelet_decompress_vec");
}

// accepts 2
TEST(MatrixCallArity_compress, ans_decode_vec_rejects_3) {
    expect_arity_rejected("ans_decode_vec", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_compress, ans_encode_vec_rejects_2) {
    expect_arity_rejected("ans_encode_vec", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_compress, arithmetic_decode_vec_rejects_3) {
    expect_arity_rejected("arithmetic_decode_vec", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_compress, arithmetic_encode_vec_rejects_2) {
    expect_arity_rejected("arithmetic_encode_vec", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_compress, bwt_decode_vec_rejects_3) {
    expect_arity_rejected("bwt_decode_vec", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_compress, bwt_encode_vec_rejects_2) {
    expect_arity_rejected("bwt_encode_vec", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_compress, bzip2_compress_vec_rejects_2) {
    expect_arity_rejected("bzip2_compress_vec", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_compress, bzip2_decompress_vec_rejects_2) {
    expect_arity_rejected("bzip2_decompress_vec", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_compress, compress_bits_to_bytes_rejects_2) {
    expect_arity_rejected("compress_bits_to_bytes", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_compress, compress_bytes_to_bits_rejects_2) {
    expect_arity_rejected("compress_bytes_to_bits", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_compress, delta_decode_vec_rejects_2) {
    expect_arity_rejected("delta_decode_vec", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_compress, delta_encode_vec_rejects_2) {
    expect_arity_rejected("delta_encode_vec", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_compress, huffman_decode_vec_rejects_3) {
    expect_arity_rejected("huffman_decode_vec", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_compress, huffman_encode_vec_rejects_2) {
    expect_arity_rejected("huffman_encode_vec", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_compress, rle_decode_vec_rejects_2) {
    expect_arity_rejected("rle_decode_vec", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_compress, rle_encode_vec_rejects_2) {
    expect_arity_rejected("rle_encode_vec", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_compress, run_length_decode_vec_rejects_2) {
    expect_arity_rejected("run_length_decode_vec", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_compress, run_length_encode_vec_rejects_2) {
    expect_arity_rejected("run_length_encode_vec", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1, 2
TEST(MatrixCallArity_compress, wavelet_compress_vec_rejects_3) {
    expect_arity_rejected("wavelet_compress_vec", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_compress, wavelet_decompress_vec_rejects_2) {
    expect_arity_rejected("wavelet_decompress_vec", 2,
                          "assign",
                          "unsupported matrix call");
}

TEST(MatrixCallUndefinedOperand_compress, ans_decode_vec) {
    expect_undefined_operand_propagates("ans_decode_vec", 2);
}

TEST(MatrixCallUndefinedOperand_compress, ans_encode_vec) {
    expect_undefined_operand_propagates("ans_encode_vec", 1);
}

TEST(MatrixCallUndefinedOperand_compress, arithmetic_decode_vec) {
    expect_undefined_operand_propagates("arithmetic_decode_vec", 2);
}

TEST(MatrixCallUndefinedOperand_compress, arithmetic_encode_vec) {
    expect_undefined_operand_propagates("arithmetic_encode_vec", 1);
}

TEST(MatrixCallUndefinedOperand_compress, bwt_decode_vec) {
    expect_undefined_operand_propagates("bwt_decode_vec", 2);
}

TEST(MatrixCallUndefinedOperand_compress, bwt_encode_vec) {
    expect_undefined_operand_propagates("bwt_encode_vec", 1);
}

TEST(MatrixCallUndefinedOperand_compress, bzip2_compress_vec) {
    expect_undefined_operand_propagates("bzip2_compress_vec", 1);
}

TEST(MatrixCallUndefinedOperand_compress, bzip2_decompress_vec) {
    expect_undefined_operand_propagates("bzip2_decompress_vec", 1);
}

TEST(MatrixCallUndefinedOperand_compress, compress_bits_to_bytes) {
    expect_undefined_operand_propagates("compress_bits_to_bytes", 1);
}

TEST(MatrixCallUndefinedOperand_compress, compress_bytes_to_bits) {
    expect_undefined_operand_propagates("compress_bytes_to_bits", 1);
}

TEST(MatrixCallUndefinedOperand_compress, delta_decode_vec) {
    expect_undefined_operand_propagates("delta_decode_vec", 1);
}

TEST(MatrixCallUndefinedOperand_compress, delta_encode_vec) {
    expect_undefined_operand_propagates("delta_encode_vec", 1);
}

TEST(MatrixCallUndefinedOperand_compress, huffman_decode_vec) {
    expect_undefined_operand_propagates("huffman_decode_vec", 2);
}

TEST(MatrixCallUndefinedOperand_compress, huffman_encode_vec) {
    expect_undefined_operand_propagates("huffman_encode_vec", 1);
}

TEST(MatrixCallUndefinedOperand_compress, rle_decode_vec) {
    expect_undefined_operand_propagates("rle_decode_vec", 1);
}

TEST(MatrixCallUndefinedOperand_compress, rle_encode_vec) {
    expect_undefined_operand_propagates("rle_encode_vec", 1);
}

TEST(MatrixCallUndefinedOperand_compress, run_length_decode_vec) {
    expect_undefined_operand_propagates("run_length_decode_vec", 1);
}

TEST(MatrixCallUndefinedOperand_compress, run_length_encode_vec) {
    expect_undefined_operand_propagates("run_length_encode_vec", 1);
}

TEST(MatrixCallUndefinedOperand_compress, wavelet_compress_vec) {
    expect_undefined_operand_propagates("wavelet_compress_vec", 1);
}

TEST(MatrixCallUndefinedOperand_compress, wavelet_decompress_vec) {
    expect_undefined_operand_propagates("wavelet_decompress_vec", 1);
}

TEST(MatrixCallBadOperandAt_compress, ans_decode_vec_arg1) {
    expect_bad_operand_at("ans_decode_vec", 2, 1);
}

TEST(MatrixCallBadOperandAt_compress, arithmetic_decode_vec_arg1) {
    expect_bad_operand_at("arithmetic_decode_vec", 2, 1);
}

TEST(MatrixCallBadOperandAt_compress, huffman_decode_vec_arg1) {
    expect_bad_operand_at("huffman_decode_vec", 2, 1);
}
