// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Odin Loch
//
// GENERATED by scripts/gen_matrix_call_tests.py from matrix_calls_manifest.json.
// Do not edit: run the two scripts. CI regenerates both and fails on a dirty
// tree, so a handler cannot land without its dispatch tests.

#include "matrix_call_test_support.hpp"

using namespace ms::interp::testing;

TEST(MatrixCallRegistration_image, adapthisteq) {
    expect_registered("adapthisteq");
}

TEST(MatrixCallRegistration_image, bilateral) {
    expect_registered("bilateral");
}

TEST(MatrixCallRegistration_image, boxfilter) {
    expect_registered("boxfilter");
}

TEST(MatrixCallRegistration_image, canny) {
    expect_registered("canny");
}

TEST(MatrixCallRegistration_image, histeq) {
    expect_registered("histeq");
}

TEST(MatrixCallRegistration_image, laplacian) {
    expect_registered("laplacian");
}

TEST(MatrixCallRegistration_image, prewitt) {
    expect_registered("prewitt");
}

TEST(MatrixCallRegistration_image, radon) {
    expect_registered("radon");
}

TEST(MatrixCallRegistration_image, rgb2gray) {
    expect_registered("rgb2gray");
}

TEST(MatrixCallRegistration_image, rgb2hsv) {
    expect_registered("rgb2hsv");
}

TEST(MatrixCallRegistration_image, roberts) {
    expect_registered("roberts");
}

TEST(MatrixCallRegistration_image, scharr) {
    expect_registered("scharr");
}

TEST(MatrixCallRegistration_image, sharpen) {
    expect_registered("sharpen");
}

TEST(MatrixCallRegistration_image, shi_tomasi) {
    expect_registered("shi_tomasi");
}

TEST(MatrixCallRegistration_image, slic) {
    expect_registered("slic");
}

TEST(MatrixCallRegistration_image, sobel) {
    expect_registered("sobel");
}

TEST(MatrixCallRegistration_image, sobel_x) {
    expect_registered("sobel_x");
}

TEST(MatrixCallRegistration_image, sobel_y) {
    expect_registered("sobel_y");
}

TEST(MatrixCallRegistration_image, threshold_binary) {
    expect_registered("threshold_binary");
}

TEST(MatrixCallRegistration_image, threshold_otsu) {
    expect_registered("threshold_otsu");
}

TEST(MatrixCallRegistration_image, watershed) {
    expect_registered("watershed");
}

// accepts 1
TEST(MatrixCallArity_image, adapthisteq_rejects_2) {
    expect_arity_rejected("adapthisteq", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3
TEST(MatrixCallArity_image, bilateral_rejects_4) {
    expect_arity_rejected("bilateral", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_image, boxfilter_rejects_3) {
    expect_arity_rejected("boxfilter", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3
TEST(MatrixCallArity_image, canny_rejects_4) {
    expect_arity_rejected("canny", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_image, histeq_rejects_2) {
    expect_arity_rejected("histeq", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_image, laplacian_rejects_2) {
    expect_arity_rejected("laplacian", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_image, prewitt_rejects_2) {
    expect_arity_rejected("prewitt", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_image, radon_rejects_3) {
    expect_arity_rejected("radon", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_image, rgb2gray_rejects_2) {
    expect_arity_rejected("rgb2gray", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_image, rgb2hsv_rejects_2) {
    expect_arity_rejected("rgb2hsv", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_image, roberts_rejects_2) {
    expect_arity_rejected("roberts", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_image, scharr_rejects_2) {
    expect_arity_rejected("scharr", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_image, sharpen_rejects_2) {
    expect_arity_rejected("sharpen", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2, 3
TEST(MatrixCallArity_image, shi_tomasi_rejects_4) {
    expect_arity_rejected("shi_tomasi", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2, 3
TEST(MatrixCallArity_image, slic_rejects_4) {
    expect_arity_rejected("slic", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_image, sobel_rejects_2) {
    expect_arity_rejected("sobel", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_image, sobel_x_rejects_2) {
    expect_arity_rejected("sobel_x", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_image, sobel_y_rejects_2) {
    expect_arity_rejected("sobel_y", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_image, threshold_binary_rejects_3) {
    expect_arity_rejected("threshold_binary", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_image, threshold_otsu_rejects_2) {
    expect_arity_rejected("threshold_otsu", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_image, watershed_rejects_3) {
    expect_arity_rejected("watershed", 3,
                          "assign",
                          "unsupported matrix call");
}

TEST(MatrixCallUndefinedOperand_image, adapthisteq) {
    expect_undefined_operand_propagates("adapthisteq", 1);
}

TEST(MatrixCallUndefinedOperand_image, bilateral) {
    expect_undefined_operand_propagates("bilateral", 3);
}

TEST(MatrixCallUndefinedOperand_image, boxfilter) {
    expect_undefined_operand_propagates("boxfilter", 2);
}

TEST(MatrixCallUndefinedOperand_image, canny) {
    expect_undefined_operand_propagates("canny", 3);
}

TEST(MatrixCallUndefinedOperand_image, histeq) {
    expect_undefined_operand_propagates("histeq", 1);
}

TEST(MatrixCallUndefinedOperand_image, laplacian) {
    expect_undefined_operand_propagates("laplacian", 1);
}

TEST(MatrixCallUndefinedOperand_image, prewitt) {
    expect_undefined_operand_propagates("prewitt", 1);
}

TEST(MatrixCallUndefinedOperand_image, radon) {
    expect_undefined_operand_propagates("radon", 2);
}

TEST(MatrixCallUndefinedOperand_image, rgb2gray) {
    expect_undefined_operand_propagates("rgb2gray", 1);
}

TEST(MatrixCallUndefinedOperand_image, rgb2hsv) {
    expect_undefined_operand_propagates("rgb2hsv", 1);
}

TEST(MatrixCallUndefinedOperand_image, roberts) {
    expect_undefined_operand_propagates("roberts", 1);
}

TEST(MatrixCallUndefinedOperand_image, scharr) {
    expect_undefined_operand_propagates("scharr", 1);
}

TEST(MatrixCallUndefinedOperand_image, sharpen) {
    expect_undefined_operand_propagates("sharpen", 1);
}

TEST(MatrixCallUndefinedOperand_image, shi_tomasi) {
    expect_undefined_operand_propagates("shi_tomasi", 2);
}

TEST(MatrixCallUndefinedOperand_image, slic) {
    expect_undefined_operand_propagates("slic", 2);
}

TEST(MatrixCallUndefinedOperand_image, sobel) {
    expect_undefined_operand_propagates("sobel", 1);
}

TEST(MatrixCallUndefinedOperand_image, sobel_x) {
    expect_undefined_operand_propagates("sobel_x", 1);
}

TEST(MatrixCallUndefinedOperand_image, sobel_y) {
    expect_undefined_operand_propagates("sobel_y", 1);
}

TEST(MatrixCallUndefinedOperand_image, threshold_binary) {
    expect_undefined_operand_propagates("threshold_binary", 2);
}

TEST(MatrixCallUndefinedOperand_image, threshold_otsu) {
    expect_undefined_operand_propagates("threshold_otsu", 1);
}

TEST(MatrixCallUndefinedOperand_image, watershed) {
    expect_undefined_operand_propagates("watershed", 2);
}

TEST(MatrixCallBadOperandAt_image, radon_arg1) {
    expect_bad_operand_at("radon", 2, 1);
}

TEST(MatrixCallBadOperandAt_image, watershed_arg1) {
    expect_bad_operand_at("watershed", 2, 1);
}
