// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Odin Loch
//
// GENERATED by scripts/gen_matrix_call_tests.py from matrix_calls_manifest.json.
// Do not edit: run the two scripts. CI regenerates both and fails on a dirty
// tree, so a handler cannot land without its dispatch tests.

#include "matrix_call_test_support.hpp"

using namespace ms::interp::testing;

TEST(MatrixCallRegistration_pde, pde_advection_1d) {
    expect_registered("pde_advection_1d");
}

TEST(MatrixCallRegistration_pde, pde_advection_1d_lax_wendroff) {
    expect_registered("pde_advection_1d_lax_wendroff");
}

TEST(MatrixCallRegistration_pde, pde_burgers_1d) {
    expect_registered("pde_burgers_1d");
}

TEST(MatrixCallRegistration_pde, pde_heat_1d) {
    expect_registered("pde_heat_1d");
}

TEST(MatrixCallRegistration_pde, pde_heat_1d_cn) {
    expect_registered("pde_heat_1d_cn");
}

TEST(MatrixCallRegistration_pde, pde_heat_2d) {
    expect_registered("pde_heat_2d");
}

TEST(MatrixCallRegistration_pde, pde_heat_2d_cn_adi) {
    expect_registered("pde_heat_2d_cn_adi");
}

TEST(MatrixCallRegistration_pde, pde_helmholtz_2d) {
    expect_registered("pde_helmholtz_2d");
}

TEST(MatrixCallRegistration_pde, pde_laplace_2d) {
    expect_registered("pde_laplace_2d");
}

TEST(MatrixCallRegistration_pde, pde_poisson_1d) {
    expect_registered("pde_poisson_1d");
}

TEST(MatrixCallRegistration_pde, pde_poisson_2d) {
    expect_registered("pde_poisson_2d");
}

TEST(MatrixCallRegistration_pde, pde_reaction_diffusion_1d) {
    expect_registered("pde_reaction_diffusion_1d");
}

TEST(MatrixCallRegistration_pde, pde_wave_1d) {
    expect_registered("pde_wave_1d");
}

TEST(MatrixCallRegistration_pde, pde_wave_2d) {
    expect_registered("pde_wave_2d");
}

// accepts 5
TEST(MatrixCallArity_pde, pde_advection_1d_rejects_6) {
    expect_arity_rejected("pde_advection_1d", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 5
TEST(MatrixCallArity_pde, pde_advection_1d_lax_wendroff_rejects_6) {
    expect_arity_rejected("pde_advection_1d_lax_wendroff", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 5
TEST(MatrixCallArity_pde, pde_burgers_1d_rejects_6) {
    expect_arity_rejected("pde_burgers_1d", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 5
TEST(MatrixCallArity_pde, pde_heat_1d_rejects_6) {
    expect_arity_rejected("pde_heat_1d", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 5
TEST(MatrixCallArity_pde, pde_heat_1d_cn_rejects_6) {
    expect_arity_rejected("pde_heat_1d_cn", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 6
TEST(MatrixCallArity_pde, pde_heat_2d_rejects_7) {
    expect_arity_rejected("pde_heat_2d", 7,
                          "assign",
                          "unsupported matrix call");
}

// accepts 6
TEST(MatrixCallArity_pde, pde_heat_2d_cn_adi_rejects_7) {
    expect_arity_rejected("pde_heat_2d_cn_adi", 7,
                          "assign",
                          "unsupported matrix call");
}

// accepts 4, 5
TEST(MatrixCallArity_pde, pde_helmholtz_2d_rejects_6) {
    expect_arity_rejected("pde_helmholtz_2d", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3
TEST(MatrixCallArity_pde, pde_laplace_2d_rejects_4) {
    expect_arity_rejected("pde_laplace_2d", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 4
TEST(MatrixCallArity_pde, pde_poisson_1d_rejects_5) {
    expect_arity_rejected("pde_poisson_1d", 5,
                          "assign",
                          "unsupported matrix call");
}

// accepts 5
TEST(MatrixCallArity_pde, pde_poisson_2d_rejects_6) {
    expect_arity_rejected("pde_poisson_2d", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 6
TEST(MatrixCallArity_pde, pde_reaction_diffusion_1d_rejects_7) {
    expect_arity_rejected("pde_reaction_diffusion_1d", 7,
                          "assign",
                          "unsupported matrix call");
}

// accepts 6
TEST(MatrixCallArity_pde, pde_wave_1d_rejects_7) {
    expect_arity_rejected("pde_wave_1d", 7,
                          "assign",
                          "unsupported matrix call");
}

// accepts 7
TEST(MatrixCallArity_pde, pde_wave_2d_rejects_8) {
    expect_arity_rejected("pde_wave_2d", 8,
                          "assign",
                          "unsupported matrix call");
}

TEST(MatrixCallUndefinedOperand_pde, pde_advection_1d) {
    expect_undefined_operand_propagates("pde_advection_1d", 5);
}

TEST(MatrixCallUndefinedOperand_pde, pde_advection_1d_lax_wendroff) {
    expect_undefined_operand_propagates("pde_advection_1d_lax_wendroff", 5);
}

TEST(MatrixCallUndefinedOperand_pde, pde_burgers_1d) {
    expect_undefined_operand_propagates("pde_burgers_1d", 5);
}

TEST(MatrixCallUndefinedOperand_pde, pde_heat_1d) {
    expect_undefined_operand_propagates("pde_heat_1d", 5);
}

TEST(MatrixCallUndefinedOperand_pde, pde_heat_1d_cn) {
    expect_undefined_operand_propagates("pde_heat_1d_cn", 5);
}

TEST(MatrixCallUndefinedOperand_pde, pde_heat_2d) {
    expect_undefined_operand_propagates("pde_heat_2d", 6);
}

TEST(MatrixCallUndefinedOperand_pde, pde_heat_2d_cn_adi) {
    expect_undefined_operand_propagates("pde_heat_2d_cn_adi", 6);
}

TEST(MatrixCallUndefinedOperand_pde, pde_helmholtz_2d) {
    expect_undefined_operand_propagates("pde_helmholtz_2d", 4);
}

TEST(MatrixCallUndefinedOperand_pde, pde_poisson_1d) {
    expect_undefined_operand_propagates("pde_poisson_1d", 4);
}

TEST(MatrixCallUndefinedOperand_pde, pde_poisson_2d) {
    expect_undefined_operand_propagates("pde_poisson_2d", 5);
}

TEST(MatrixCallUndefinedOperand_pde, pde_reaction_diffusion_1d) {
    expect_undefined_operand_propagates("pde_reaction_diffusion_1d", 6);
}

TEST(MatrixCallUndefinedOperand_pde, pde_wave_1d) {
    expect_undefined_operand_propagates("pde_wave_1d", 6);
}

TEST(MatrixCallUndefinedOperand_pde, pde_wave_2d) {
    expect_undefined_operand_propagates("pde_wave_2d", 7);
}

TEST(MatrixCallBadOperandAt_pde, pde_helmholtz_2d_arg4) {
    expect_bad_operand_at("pde_helmholtz_2d", 5, 4);
}

TEST(MatrixCallBadOperandAt_pde, pde_laplace_2d_arg2) {
    expect_bad_operand_at("pde_laplace_2d", 3, 2);
}

TEST(MatrixCallBadOperandAt_pde, pde_wave_1d_arg1) {
    expect_bad_operand_at("pde_wave_1d", 6, 1);
}

TEST(MatrixCallBadOperandAt_pde, pde_wave_2d_arg1) {
    expect_bad_operand_at("pde_wave_2d", 7, 1);
}
