// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Odin Loch
//
// GENERATED by scripts/gen_matrix_call_tests.py from matrix_calls_manifest.json.
// Do not edit: run the two scripts. CI regenerates both and fails on a dirty
// tree, so a handler cannot land without its dispatch tests.

#include "matrix_call_test_support.hpp"

using namespace ms::interp::testing;

TEST(MatrixCallRegistration_ml, ml_adaboost_fit) {
    expect_registered("ml_adaboost_fit");
}

TEST(MatrixCallRegistration_ml, ml_adaboost_predict) {
    expect_registered("ml_adaboost_predict");
}

TEST(MatrixCallRegistration_ml, ml_agglomerative_fit) {
    expect_registered("ml_agglomerative_fit");
}

TEST(MatrixCallRegistration_ml, ml_confusion_matrix) {
    expect_registered("ml_confusion_matrix");
}

TEST(MatrixCallRegistration_ml, ml_dbscan_fit) {
    expect_registered("ml_dbscan_fit");
}

TEST(MatrixCallRegistration_ml, ml_decision_tree_fit) {
    expect_registered("ml_decision_tree_fit");
}

TEST(MatrixCallRegistration_ml, ml_decision_tree_predict) {
    expect_registered("ml_decision_tree_predict");
}

TEST(MatrixCallRegistration_ml, ml_elastic_net_fit) {
    expect_registered("ml_elastic_net_fit");
}

TEST(MatrixCallRegistration_ml, ml_elastic_net_predict) {
    expect_registered("ml_elastic_net_predict");
}

TEST(MatrixCallRegistration_ml, ml_gmm_fit) {
    expect_registered("ml_gmm_fit");
}

TEST(MatrixCallRegistration_ml, ml_gmm_predict) {
    expect_registered("ml_gmm_predict");
}

TEST(MatrixCallRegistration_ml, ml_gmm_predict_proba) {
    expect_registered("ml_gmm_predict_proba");
}

TEST(MatrixCallRegistration_ml, ml_gradient_boosting_fit) {
    expect_registered("ml_gradient_boosting_fit");
}

TEST(MatrixCallRegistration_ml, ml_gradient_boosting_predict) {
    expect_registered("ml_gradient_boosting_predict");
}

TEST(MatrixCallRegistration_ml, ml_isolation_forest_fit) {
    expect_registered("ml_isolation_forest_fit");
}

TEST(MatrixCallRegistration_ml, ml_isolation_forest_score) {
    expect_registered("ml_isolation_forest_score");
}

TEST(MatrixCallRegistration_ml, ml_kmeans_fit) {
    expect_registered("ml_kmeans_fit");
}

TEST(MatrixCallRegistration_ml, ml_kmeans_predict) {
    expect_registered("ml_kmeans_predict");
}

TEST(MatrixCallRegistration_ml, ml_knn_fit) {
    expect_registered("ml_knn_fit");
}

TEST(MatrixCallRegistration_ml, ml_knn_predict) {
    expect_registered("ml_knn_predict");
}

TEST(MatrixCallRegistration_ml, ml_lasso_fit) {
    expect_registered("ml_lasso_fit");
}

TEST(MatrixCallRegistration_ml, ml_lasso_predict) {
    expect_registered("ml_lasso_predict");
}

TEST(MatrixCallRegistration_ml, ml_lda_fit) {
    expect_registered("ml_lda_fit");
}

TEST(MatrixCallRegistration_ml, ml_lda_predict) {
    expect_registered("ml_lda_predict");
}

TEST(MatrixCallRegistration_ml, ml_lda_transform) {
    expect_registered("ml_lda_transform");
}

TEST(MatrixCallRegistration_ml, ml_linear_fit) {
    expect_registered("ml_linear_fit");
}

TEST(MatrixCallRegistration_ml, ml_linear_predict) {
    expect_registered("ml_linear_predict");
}

TEST(MatrixCallRegistration_ml, ml_logistic_fit) {
    expect_registered("ml_logistic_fit");
}

TEST(MatrixCallRegistration_ml, ml_logistic_predict) {
    expect_registered("ml_logistic_predict");
}

TEST(MatrixCallRegistration_ml, ml_mat_transpose) {
    expect_registered("ml_mat_transpose");
}

TEST(MatrixCallRegistration_ml, ml_minmax_scaler_fit) {
    expect_registered("ml_minmax_scaler_fit");
}

TEST(MatrixCallRegistration_ml, ml_minmax_scaler_transform) {
    expect_registered("ml_minmax_scaler_transform");
}

TEST(MatrixCallRegistration_ml, ml_naive_bayes_fit) {
    expect_registered("ml_naive_bayes_fit");
}

TEST(MatrixCallRegistration_ml, ml_naive_bayes_predict) {
    expect_registered("ml_naive_bayes_predict");
}

TEST(MatrixCallRegistration_ml, ml_pca_fit) {
    expect_registered("ml_pca_fit");
}

TEST(MatrixCallRegistration_ml, ml_pca_fit_transform) {
    expect_registered("ml_pca_fit_transform");
}

TEST(MatrixCallRegistration_ml, ml_pca_transform) {
    expect_registered("ml_pca_transform");
}

TEST(MatrixCallRegistration_ml, ml_precision_recall_curve) {
    expect_registered("ml_precision_recall_curve");
}

TEST(MatrixCallRegistration_ml, ml_qda_fit) {
    expect_registered("ml_qda_fit");
}

TEST(MatrixCallRegistration_ml, ml_qda_predict) {
    expect_registered("ml_qda_predict");
}

TEST(MatrixCallRegistration_ml, ml_random_forest_fit) {
    expect_registered("ml_random_forest_fit");
}

TEST(MatrixCallRegistration_ml, ml_random_forest_predict) {
    expect_registered("ml_random_forest_predict");
}

TEST(MatrixCallRegistration_ml, ml_ridge_fit) {
    expect_registered("ml_ridge_fit");
}

TEST(MatrixCallRegistration_ml, ml_ridge_predict) {
    expect_registered("ml_ridge_predict");
}

TEST(MatrixCallRegistration_ml, ml_roc_curve) {
    expect_registered("ml_roc_curve");
}

TEST(MatrixCallRegistration_ml, ml_spectral_clustering) {
    expect_registered("ml_spectral_clustering");
}

TEST(MatrixCallRegistration_ml, ml_standard_scaler_fit) {
    expect_registered("ml_standard_scaler_fit");
}

TEST(MatrixCallRegistration_ml, ml_standard_scaler_transform) {
    expect_registered("ml_standard_scaler_transform");
}

TEST(MatrixCallRegistration_ml, ml_svm_fit) {
    expect_registered("ml_svm_fit");
}

TEST(MatrixCallRegistration_ml, ml_svm_predict) {
    expect_registered("ml_svm_predict");
}

TEST(MatrixCallRegistration_ml, ml_tsne_fit) {
    expect_registered("ml_tsne_fit");
}

// accepts 2, 3, 4
TEST(MatrixCallArity_ml, ml_adaboost_fit_rejects_5) {
    expect_arity_rejected("ml_adaboost_fit", 5,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_ml, ml_adaboost_predict_rejects_3) {
    expect_arity_rejected("ml_adaboost_predict", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1, 2, 3
TEST(MatrixCallArity_ml, ml_agglomerative_fit_rejects_4) {
    expect_arity_rejected("ml_agglomerative_fit", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2, 3
TEST(MatrixCallArity_ml, ml_confusion_matrix_rejects_4) {
    expect_arity_rejected("ml_confusion_matrix", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3
TEST(MatrixCallArity_ml, ml_dbscan_fit_rejects_4) {
    expect_arity_rejected("ml_dbscan_fit", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2, 3
TEST(MatrixCallArity_ml, ml_decision_tree_fit_rejects_4) {
    expect_arity_rejected("ml_decision_tree_fit", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_ml, ml_decision_tree_predict_rejects_3) {
    expect_arity_rejected("ml_decision_tree_predict", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 4
TEST(MatrixCallArity_ml, ml_elastic_net_fit_rejects_5) {
    expect_arity_rejected("ml_elastic_net_fit", 5,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_ml, ml_elastic_net_predict_rejects_3) {
    expect_arity_rejected("ml_elastic_net_predict", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1, 2
TEST(MatrixCallArity_ml, ml_gmm_fit_rejects_3) {
    expect_arity_rejected("ml_gmm_fit", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_ml, ml_gmm_predict_rejects_3) {
    expect_arity_rejected("ml_gmm_predict", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_ml, ml_gmm_predict_proba_rejects_3) {
    expect_arity_rejected("ml_gmm_predict_proba", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2, 3, 4, 5
TEST(MatrixCallArity_ml, ml_gradient_boosting_fit_rejects_6) {
    expect_arity_rejected("ml_gradient_boosting_fit", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_ml, ml_gradient_boosting_predict_rejects_3) {
    expect_arity_rejected("ml_gradient_boosting_predict", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1, 2, 3, 4
TEST(MatrixCallArity_ml, ml_isolation_forest_fit_rejects_5) {
    expect_arity_rejected("ml_isolation_forest_fit", 5,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_ml, ml_isolation_forest_score_rejects_3) {
    expect_arity_rejected("ml_isolation_forest_score", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_ml, ml_kmeans_fit_rejects_3) {
    expect_arity_rejected("ml_kmeans_fit", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_ml, ml_kmeans_predict_rejects_3) {
    expect_arity_rejected("ml_kmeans_predict", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3
TEST(MatrixCallArity_ml, ml_knn_fit_rejects_4) {
    expect_arity_rejected("ml_knn_fit", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_ml, ml_knn_predict_rejects_3) {
    expect_arity_rejected("ml_knn_predict", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3
TEST(MatrixCallArity_ml, ml_lasso_fit_rejects_4) {
    expect_arity_rejected("ml_lasso_fit", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_ml, ml_lasso_predict_rejects_3) {
    expect_arity_rejected("ml_lasso_predict", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2, 3
TEST(MatrixCallArity_ml, ml_lda_fit_rejects_4) {
    expect_arity_rejected("ml_lda_fit", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_ml, ml_lda_predict_rejects_3) {
    expect_arity_rejected("ml_lda_predict", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_ml, ml_lda_transform_rejects_3) {
    expect_arity_rejected("ml_lda_transform", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_ml, ml_linear_fit_rejects_3) {
    expect_arity_rejected("ml_linear_fit", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_ml, ml_linear_predict_rejects_3) {
    expect_arity_rejected("ml_linear_predict", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_ml, ml_logistic_fit_rejects_3) {
    expect_arity_rejected("ml_logistic_fit", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_ml, ml_logistic_predict_rejects_3) {
    expect_arity_rejected("ml_logistic_predict", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_ml, ml_mat_transpose_rejects_2) {
    expect_arity_rejected("ml_mat_transpose", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_ml, ml_minmax_scaler_fit_rejects_2) {
    expect_arity_rejected("ml_minmax_scaler_fit", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_ml, ml_minmax_scaler_transform_rejects_3) {
    expect_arity_rejected("ml_minmax_scaler_transform", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_ml, ml_naive_bayes_fit_rejects_3) {
    expect_arity_rejected("ml_naive_bayes_fit", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_ml, ml_naive_bayes_predict_rejects_3) {
    expect_arity_rejected("ml_naive_bayes_predict", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_ml, ml_pca_fit_rejects_3) {
    expect_arity_rejected("ml_pca_fit", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_ml, ml_pca_fit_transform_rejects_3) {
    expect_arity_rejected("ml_pca_fit_transform", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_ml, ml_pca_transform_rejects_3) {
    expect_arity_rejected("ml_pca_transform", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_ml, ml_precision_recall_curve_rejects_3) {
    expect_arity_rejected("ml_precision_recall_curve", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_ml, ml_qda_fit_rejects_3) {
    expect_arity_rejected("ml_qda_fit", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_ml, ml_qda_predict_rejects_3) {
    expect_arity_rejected("ml_qda_predict", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2, 3, 4
TEST(MatrixCallArity_ml, ml_random_forest_fit_rejects_5) {
    expect_arity_rejected("ml_random_forest_fit", 5,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_ml, ml_random_forest_predict_rejects_3) {
    expect_arity_rejected("ml_random_forest_predict", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3
TEST(MatrixCallArity_ml, ml_ridge_fit_rejects_4) {
    expect_arity_rejected("ml_ridge_fit", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_ml, ml_ridge_predict_rejects_3) {
    expect_arity_rejected("ml_ridge_predict", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_ml, ml_roc_curve_rejects_3) {
    expect_arity_rejected("ml_roc_curve", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2, 3, 4
TEST(MatrixCallArity_ml, ml_spectral_clustering_rejects_5) {
    expect_arity_rejected("ml_spectral_clustering", 5,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_ml, ml_standard_scaler_fit_rejects_2) {
    expect_arity_rejected("ml_standard_scaler_fit", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_ml, ml_standard_scaler_transform_rejects_3) {
    expect_arity_rejected("ml_standard_scaler_transform", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2, 3, 4
TEST(MatrixCallArity_ml, ml_svm_fit_rejects_5) {
    expect_arity_rejected("ml_svm_fit", 5,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_ml, ml_svm_predict_rejects_3) {
    expect_arity_rejected("ml_svm_predict", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1, 2, 3, 4
TEST(MatrixCallArity_ml, ml_tsne_fit_rejects_5) {
    expect_arity_rejected("ml_tsne_fit", 5,
                          "assign",
                          "unsupported matrix call");
}

TEST(MatrixCallUndefinedOperand_ml, ml_adaboost_fit) {
    expect_undefined_operand_propagates("ml_adaboost_fit", 2);
}

TEST(MatrixCallUndefinedOperand_ml, ml_adaboost_predict) {
    expect_undefined_operand_propagates("ml_adaboost_predict", 2);
}

TEST(MatrixCallUndefinedOperand_ml, ml_agglomerative_fit) {
    expect_undefined_operand_propagates("ml_agglomerative_fit", 1);
}

TEST(MatrixCallUndefinedOperand_ml, ml_confusion_matrix) {
    expect_undefined_operand_propagates("ml_confusion_matrix", 2);
}

TEST(MatrixCallUndefinedOperand_ml, ml_dbscan_fit) {
    expect_undefined_operand_propagates("ml_dbscan_fit", 3);
}

TEST(MatrixCallUndefinedOperand_ml, ml_decision_tree_fit) {
    expect_undefined_operand_propagates("ml_decision_tree_fit", 2);
}

TEST(MatrixCallUndefinedOperand_ml, ml_decision_tree_predict) {
    expect_undefined_operand_propagates("ml_decision_tree_predict", 2);
}

TEST(MatrixCallUndefinedOperand_ml, ml_elastic_net_fit) {
    expect_undefined_operand_propagates("ml_elastic_net_fit", 4);
}

TEST(MatrixCallUndefinedOperand_ml, ml_elastic_net_predict) {
    expect_undefined_operand_propagates("ml_elastic_net_predict", 2);
}

TEST(MatrixCallUndefinedOperand_ml, ml_gmm_fit) {
    expect_undefined_operand_propagates("ml_gmm_fit", 1);
}

TEST(MatrixCallUndefinedOperand_ml, ml_gmm_predict) {
    expect_undefined_operand_propagates("ml_gmm_predict", 2);
}

TEST(MatrixCallUndefinedOperand_ml, ml_gmm_predict_proba) {
    expect_undefined_operand_propagates("ml_gmm_predict_proba", 2);
}

TEST(MatrixCallUndefinedOperand_ml, ml_gradient_boosting_fit) {
    expect_undefined_operand_propagates("ml_gradient_boosting_fit", 2);
}

TEST(MatrixCallUndefinedOperand_ml, ml_gradient_boosting_predict) {
    expect_undefined_operand_propagates("ml_gradient_boosting_predict", 2);
}

TEST(MatrixCallUndefinedOperand_ml, ml_isolation_forest_fit) {
    expect_undefined_operand_propagates("ml_isolation_forest_fit", 1);
}

TEST(MatrixCallUndefinedOperand_ml, ml_isolation_forest_score) {
    expect_undefined_operand_propagates("ml_isolation_forest_score", 2);
}

TEST(MatrixCallUndefinedOperand_ml, ml_kmeans_fit) {
    expect_undefined_operand_propagates("ml_kmeans_fit", 2);
}

TEST(MatrixCallUndefinedOperand_ml, ml_kmeans_predict) {
    expect_undefined_operand_propagates("ml_kmeans_predict", 2);
}

TEST(MatrixCallUndefinedOperand_ml, ml_knn_fit) {
    expect_undefined_operand_propagates("ml_knn_fit", 3);
}

TEST(MatrixCallUndefinedOperand_ml, ml_knn_predict) {
    expect_undefined_operand_propagates("ml_knn_predict", 2);
}

TEST(MatrixCallUndefinedOperand_ml, ml_lasso_fit) {
    expect_undefined_operand_propagates("ml_lasso_fit", 3);
}

TEST(MatrixCallUndefinedOperand_ml, ml_lasso_predict) {
    expect_undefined_operand_propagates("ml_lasso_predict", 2);
}

TEST(MatrixCallUndefinedOperand_ml, ml_lda_fit) {
    expect_undefined_operand_propagates("ml_lda_fit", 2);
}

TEST(MatrixCallUndefinedOperand_ml, ml_lda_predict) {
    expect_undefined_operand_propagates("ml_lda_predict", 2);
}

TEST(MatrixCallUndefinedOperand_ml, ml_lda_transform) {
    expect_undefined_operand_propagates("ml_lda_transform", 2);
}

TEST(MatrixCallUndefinedOperand_ml, ml_linear_fit) {
    expect_undefined_operand_propagates("ml_linear_fit", 2);
}

TEST(MatrixCallUndefinedOperand_ml, ml_linear_predict) {
    expect_undefined_operand_propagates("ml_linear_predict", 2);
}

TEST(MatrixCallUndefinedOperand_ml, ml_logistic_fit) {
    expect_undefined_operand_propagates("ml_logistic_fit", 2);
}

TEST(MatrixCallUndefinedOperand_ml, ml_logistic_predict) {
    expect_undefined_operand_propagates("ml_logistic_predict", 2);
}

TEST(MatrixCallUndefinedOperand_ml, ml_mat_transpose) {
    expect_undefined_operand_propagates("ml_mat_transpose", 1);
}

TEST(MatrixCallUndefinedOperand_ml, ml_minmax_scaler_fit) {
    expect_undefined_operand_propagates("ml_minmax_scaler_fit", 1);
}

TEST(MatrixCallUndefinedOperand_ml, ml_minmax_scaler_transform) {
    expect_undefined_operand_propagates("ml_minmax_scaler_transform", 2);
}

TEST(MatrixCallUndefinedOperand_ml, ml_naive_bayes_fit) {
    expect_undefined_operand_propagates("ml_naive_bayes_fit", 2);
}

TEST(MatrixCallUndefinedOperand_ml, ml_naive_bayes_predict) {
    expect_undefined_operand_propagates("ml_naive_bayes_predict", 2);
}

TEST(MatrixCallUndefinedOperand_ml, ml_pca_fit) {
    expect_undefined_operand_propagates("ml_pca_fit", 2);
}

TEST(MatrixCallUndefinedOperand_ml, ml_pca_fit_transform) {
    expect_undefined_operand_propagates("ml_pca_fit_transform", 2);
}

TEST(MatrixCallUndefinedOperand_ml, ml_pca_transform) {
    expect_undefined_operand_propagates("ml_pca_transform", 2);
}

TEST(MatrixCallUndefinedOperand_ml, ml_precision_recall_curve) {
    expect_undefined_operand_propagates("ml_precision_recall_curve", 2);
}

TEST(MatrixCallUndefinedOperand_ml, ml_qda_fit) {
    expect_undefined_operand_propagates("ml_qda_fit", 2);
}

TEST(MatrixCallUndefinedOperand_ml, ml_qda_predict) {
    expect_undefined_operand_propagates("ml_qda_predict", 2);
}

TEST(MatrixCallUndefinedOperand_ml, ml_random_forest_fit) {
    expect_undefined_operand_propagates("ml_random_forest_fit", 2);
}

TEST(MatrixCallUndefinedOperand_ml, ml_random_forest_predict) {
    expect_undefined_operand_propagates("ml_random_forest_predict", 2);
}

TEST(MatrixCallUndefinedOperand_ml, ml_ridge_fit) {
    expect_undefined_operand_propagates("ml_ridge_fit", 3);
}

TEST(MatrixCallUndefinedOperand_ml, ml_ridge_predict) {
    expect_undefined_operand_propagates("ml_ridge_predict", 2);
}

TEST(MatrixCallUndefinedOperand_ml, ml_roc_curve) {
    expect_undefined_operand_propagates("ml_roc_curve", 2);
}

TEST(MatrixCallUndefinedOperand_ml, ml_spectral_clustering) {
    expect_undefined_operand_propagates("ml_spectral_clustering", 2);
}

TEST(MatrixCallUndefinedOperand_ml, ml_standard_scaler_fit) {
    expect_undefined_operand_propagates("ml_standard_scaler_fit", 1);
}

TEST(MatrixCallUndefinedOperand_ml, ml_standard_scaler_transform) {
    expect_undefined_operand_propagates("ml_standard_scaler_transform", 2);
}

TEST(MatrixCallUndefinedOperand_ml, ml_svm_fit) {
    expect_undefined_operand_propagates("ml_svm_fit", 2);
}

TEST(MatrixCallUndefinedOperand_ml, ml_svm_predict) {
    expect_undefined_operand_propagates("ml_svm_predict", 2);
}

TEST(MatrixCallUndefinedOperand_ml, ml_tsne_fit) {
    expect_undefined_operand_propagates("ml_tsne_fit", 1);
}

TEST(MatrixCallBadOperandAt_ml, ml_adaboost_fit_arg1) {
    expect_bad_operand_at("ml_adaboost_fit", 4, 1);
}

TEST(MatrixCallBadOperandAt_ml, ml_adaboost_predict_arg1) {
    expect_bad_operand_at("ml_adaboost_predict", 2, 1);
}

TEST(MatrixCallBadOperandAt_ml, ml_confusion_matrix_arg1) {
    expect_bad_operand_at("ml_confusion_matrix", 3, 1);
}

TEST(MatrixCallBadOperandAt_ml, ml_decision_tree_fit_arg1) {
    expect_bad_operand_at("ml_decision_tree_fit", 3, 1);
}

TEST(MatrixCallBadOperandAt_ml, ml_decision_tree_predict_arg1) {
    expect_bad_operand_at("ml_decision_tree_predict", 2, 1);
}

TEST(MatrixCallBadOperandAt_ml, ml_elastic_net_fit_arg1) {
    expect_bad_operand_at("ml_elastic_net_fit", 4, 1);
}

TEST(MatrixCallBadOperandAt_ml, ml_elastic_net_predict_arg1) {
    expect_bad_operand_at("ml_elastic_net_predict", 2, 1);
}

TEST(MatrixCallBadOperandAt_ml, ml_gmm_predict_arg1) {
    expect_bad_operand_at("ml_gmm_predict", 2, 1);
}

TEST(MatrixCallBadOperandAt_ml, ml_gmm_predict_proba_arg1) {
    expect_bad_operand_at("ml_gmm_predict_proba", 2, 1);
}

TEST(MatrixCallBadOperandAt_ml, ml_gradient_boosting_fit_arg1) {
    expect_bad_operand_at("ml_gradient_boosting_fit", 5, 1);
}

TEST(MatrixCallBadOperandAt_ml, ml_gradient_boosting_predict_arg1) {
    expect_bad_operand_at("ml_gradient_boosting_predict", 2, 1);
}

TEST(MatrixCallBadOperandAt_ml, ml_isolation_forest_score_arg1) {
    expect_bad_operand_at("ml_isolation_forest_score", 2, 1);
}

TEST(MatrixCallBadOperandAt_ml, ml_kmeans_predict_arg1) {
    expect_bad_operand_at("ml_kmeans_predict", 2, 1);
}

TEST(MatrixCallBadOperandAt_ml, ml_knn_fit_arg1) {
    expect_bad_operand_at("ml_knn_fit", 3, 1);
}

TEST(MatrixCallBadOperandAt_ml, ml_knn_predict_arg1) {
    expect_bad_operand_at("ml_knn_predict", 2, 1);
}

TEST(MatrixCallBadOperandAt_ml, ml_lasso_fit_arg1) {
    expect_bad_operand_at("ml_lasso_fit", 3, 1);
}

TEST(MatrixCallBadOperandAt_ml, ml_lasso_predict_arg1) {
    expect_bad_operand_at("ml_lasso_predict", 2, 1);
}

TEST(MatrixCallBadOperandAt_ml, ml_lda_fit_arg1) {
    expect_bad_operand_at("ml_lda_fit", 3, 1);
}

TEST(MatrixCallBadOperandAt_ml, ml_lda_predict_arg1) {
    expect_bad_operand_at("ml_lda_predict", 2, 1);
}

TEST(MatrixCallBadOperandAt_ml, ml_lda_transform_arg1) {
    expect_bad_operand_at("ml_lda_transform", 2, 1);
}

TEST(MatrixCallBadOperandAt_ml, ml_linear_fit_arg1) {
    expect_bad_operand_at("ml_linear_fit", 2, 1);
}

TEST(MatrixCallBadOperandAt_ml, ml_linear_predict_arg1) {
    expect_bad_operand_at("ml_linear_predict", 2, 1);
}

TEST(MatrixCallBadOperandAt_ml, ml_logistic_fit_arg1) {
    expect_bad_operand_at("ml_logistic_fit", 2, 1);
}

TEST(MatrixCallBadOperandAt_ml, ml_logistic_predict_arg1) {
    expect_bad_operand_at("ml_logistic_predict", 2, 1);
}

TEST(MatrixCallBadOperandAt_ml, ml_minmax_scaler_transform_arg1) {
    expect_bad_operand_at("ml_minmax_scaler_transform", 2, 1);
}

TEST(MatrixCallBadOperandAt_ml, ml_naive_bayes_fit_arg1) {
    expect_bad_operand_at("ml_naive_bayes_fit", 2, 1);
}

TEST(MatrixCallBadOperandAt_ml, ml_naive_bayes_predict_arg1) {
    expect_bad_operand_at("ml_naive_bayes_predict", 2, 1);
}

TEST(MatrixCallBadOperandAt_ml, ml_pca_transform_arg1) {
    expect_bad_operand_at("ml_pca_transform", 2, 1);
}

TEST(MatrixCallBadOperandAt_ml, ml_precision_recall_curve_arg1) {
    expect_bad_operand_at("ml_precision_recall_curve", 2, 1);
}

TEST(MatrixCallBadOperandAt_ml, ml_qda_fit_arg1) {
    expect_bad_operand_at("ml_qda_fit", 2, 1);
}

TEST(MatrixCallBadOperandAt_ml, ml_qda_predict_arg1) {
    expect_bad_operand_at("ml_qda_predict", 2, 1);
}

TEST(MatrixCallBadOperandAt_ml, ml_random_forest_fit_arg1) {
    expect_bad_operand_at("ml_random_forest_fit", 4, 1);
}

TEST(MatrixCallBadOperandAt_ml, ml_random_forest_predict_arg1) {
    expect_bad_operand_at("ml_random_forest_predict", 2, 1);
}

TEST(MatrixCallBadOperandAt_ml, ml_ridge_fit_arg1) {
    expect_bad_operand_at("ml_ridge_fit", 3, 1);
}

TEST(MatrixCallBadOperandAt_ml, ml_ridge_predict_arg1) {
    expect_bad_operand_at("ml_ridge_predict", 2, 1);
}

TEST(MatrixCallBadOperandAt_ml, ml_roc_curve_arg1) {
    expect_bad_operand_at("ml_roc_curve", 2, 1);
}

TEST(MatrixCallBadOperandAt_ml, ml_standard_scaler_transform_arg1) {
    expect_bad_operand_at("ml_standard_scaler_transform", 2, 1);
}

TEST(MatrixCallBadOperandAt_ml, ml_svm_fit_arg1) {
    expect_bad_operand_at("ml_svm_fit", 4, 1);
}

TEST(MatrixCallBadOperandAt_ml, ml_svm_predict_arg1) {
    expect_bad_operand_at("ml_svm_predict", 2, 1);
}
