// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Odin Loch
//
// GENERATED by scripts/gen_matrix_call_tests.py from matrix_calls_manifest.json.
// Do not edit: run the two scripts. CI regenerates both and fails on a dirty
// tree, so a handler cannot land without its dispatch tests.

#include "matrix_call_test_support.hpp"

using namespace ms::interp::testing;

TEST(MatrixCallRegistration_combo, combo_bracelets) {
    expect_registered("combo_bracelets");
}

TEST(MatrixCallRegistration_combo, combo_de_bruijn_sequence) {
    expect_registered("combo_de_bruijn_sequence");
}

TEST(MatrixCallRegistration_combo, combo_dyck_paths) {
    expect_registered("combo_dyck_paths");
}

TEST(MatrixCallRegistration_combo, combo_gray_code) {
    expect_registered("combo_gray_code");
}

TEST(MatrixCallRegistration_combo, combo_lyndon_words) {
    expect_registered("combo_lyndon_words");
}

TEST(MatrixCallRegistration_combo, combo_motzkin_paths) {
    expect_registered("combo_motzkin_paths");
}

TEST(MatrixCallRegistration_combo, combo_necklaces) {
    expect_registered("combo_necklaces");
}

TEST(MatrixCallRegistration_combo, combo_next_perm) {
    expect_registered("combo_next_perm");
}

TEST(MatrixCallRegistration_combo, combo_prev_perm) {
    expect_registered("combo_prev_perm");
}

TEST(MatrixCallRegistration_combo, combo_restricted_partitions) {
    expect_registered("combo_restricted_partitions");
}

TEST(MatrixCallRegistration_combo, combo_set_partitions) {
    expect_registered("combo_set_partitions");
}

TEST(MatrixCallRegistration_combo, combo_unrank_combination) {
    expect_registered("combo_unrank_combination");
}

TEST(MatrixCallRegistration_combo, combo_unrank_permutation) {
    expect_registered("combo_unrank_permutation");
}

// accepts 2
TEST(MatrixCallArity_combo, combo_bracelets_rejects_3) {
    expect_arity_rejected("combo_bracelets", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_combo, combo_de_bruijn_sequence_rejects_3) {
    expect_arity_rejected("combo_de_bruijn_sequence", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_combo, combo_dyck_paths_rejects_2) {
    expect_arity_rejected("combo_dyck_paths", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_combo, combo_gray_code_rejects_2) {
    expect_arity_rejected("combo_gray_code", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_combo, combo_lyndon_words_rejects_3) {
    expect_arity_rejected("combo_lyndon_words", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_combo, combo_motzkin_paths_rejects_2) {
    expect_arity_rejected("combo_motzkin_paths", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_combo, combo_necklaces_rejects_3) {
    expect_arity_rejected("combo_necklaces", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_combo, combo_next_perm_rejects_2) {
    expect_arity_rejected("combo_next_perm", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_combo, combo_prev_perm_rejects_2) {
    expect_arity_rejected("combo_prev_perm", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_combo, combo_restricted_partitions_rejects_3) {
    expect_arity_rejected("combo_restricted_partitions", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_combo, combo_set_partitions_rejects_2) {
    expect_arity_rejected("combo_set_partitions", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3
TEST(MatrixCallArity_combo, combo_unrank_combination_rejects_4) {
    expect_arity_rejected("combo_unrank_combination", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_combo, combo_unrank_permutation_rejects_3) {
    expect_arity_rejected("combo_unrank_permutation", 3,
                          "assign",
                          "unsupported matrix call");
}

TEST(MatrixCallUndefinedOperand_combo, combo_next_perm) {
    expect_undefined_operand_propagates("combo_next_perm", 1);
}

TEST(MatrixCallUndefinedOperand_combo, combo_prev_perm) {
    expect_undefined_operand_propagates("combo_prev_perm", 1);
}
