// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Odin Loch
//
// GENERATED by scripts/gen_matrix_call_tests.py from matrix_calls_manifest.json.
// Do not edit: run the two scripts. CI regenerates both and fails on a dirty
// tree, so a handler cannot land without its dispatch tests.

#include "matrix_call_test_support.hpp"

using namespace ms::interp::testing;

TEST(MatrixCallRegistration_geo, geo_bezier_deriv) {
    expect_registered("geo_bezier_deriv");
}

TEST(MatrixCallRegistration_geo, geo_bezier_eval) {
    expect_registered("geo_bezier_eval");
}

TEST(MatrixCallRegistration_geo, geo_bezier_subdivide) {
    expect_registered("geo_bezier_subdivide");
}

TEST(MatrixCallRegistration_geo, geo_bspline_eval) {
    expect_registered("geo_bspline_eval");
}

TEST(MatrixCallRegistration_geo, geo_catmull_rom) {
    expect_registered("geo_catmull_rom");
}

TEST(MatrixCallRegistration_geo, geo_convex_hull) {
    expect_registered("geo_convex_hull");
}

TEST(MatrixCallRegistration_geo, geo_convex_hull_3d) {
    expect_registered("geo_convex_hull_3d");
}

TEST(MatrixCallRegistration_geo, geo_delaunay_2d) {
    expect_registered("geo_delaunay_2d");
}

TEST(MatrixCallRegistration_geo, geo_hermite_curve) {
    expect_registered("geo_hermite_curve");
}

TEST(MatrixCallRegistration_geo, geo_kdtree_3d_knn) {
    expect_registered("geo_kdtree_3d_knn");
}

TEST(MatrixCallRegistration_geo, geo_kdtree_3d_range) {
    expect_registered("geo_kdtree_3d_range");
}

TEST(MatrixCallRegistration_geo, geo_kdtree_knn) {
    expect_registered("geo_kdtree_knn");
}

TEST(MatrixCallRegistration_geo, geo_kdtree_range) {
    expect_registered("geo_kdtree_range");
}

TEST(MatrixCallRegistration_geo, geo_lower_hull) {
    expect_registered("geo_lower_hull");
}

TEST(MatrixCallRegistration_geo, geo_min_bounding_rect) {
    expect_registered("geo_min_bounding_rect");
}

TEST(MatrixCallRegistration_geo, geo_triangulate_polygon) {
    expect_registered("geo_triangulate_polygon");
}

TEST(MatrixCallRegistration_geo, geo_upper_hull) {
    expect_registered("geo_upper_hull");
}

TEST(MatrixCallRegistration_geo, geo_voronoi) {
    expect_registered("geo_voronoi");
}

// accepts 2
TEST(MatrixCallArity_geo, geo_bezier_deriv_rejects_3) {
    expect_arity_rejected("geo_bezier_deriv", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_geo, geo_bezier_eval_rejects_3) {
    expect_arity_rejected("geo_bezier_eval", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_geo, geo_bezier_subdivide_rejects_3) {
    expect_arity_rejected("geo_bezier_subdivide", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 4
TEST(MatrixCallArity_geo, geo_bspline_eval_rejects_5) {
    expect_arity_rejected("geo_bspline_eval", 5,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_geo, geo_catmull_rom_rejects_3) {
    expect_arity_rejected("geo_catmull_rom", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_geo, geo_convex_hull_rejects_2) {
    expect_arity_rejected("geo_convex_hull", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_geo, geo_convex_hull_3d_rejects_2) {
    expect_arity_rejected("geo_convex_hull_3d", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_geo, geo_delaunay_2d_rejects_2) {
    expect_arity_rejected("geo_delaunay_2d", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 9
TEST(MatrixCallArity_geo, geo_hermite_curve_rejects_10) {
    expect_arity_rejected("geo_hermite_curve", 10,
                          "assign",
                          "unsupported matrix call");
}

// accepts 5
TEST(MatrixCallArity_geo, geo_kdtree_3d_knn_rejects_6) {
    expect_arity_rejected("geo_kdtree_3d_knn", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 5
TEST(MatrixCallArity_geo, geo_kdtree_3d_range_rejects_6) {
    expect_arity_rejected("geo_kdtree_3d_range", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 4
TEST(MatrixCallArity_geo, geo_kdtree_knn_rejects_5) {
    expect_arity_rejected("geo_kdtree_knn", 5,
                          "assign",
                          "unsupported matrix call");
}

// accepts 4
TEST(MatrixCallArity_geo, geo_kdtree_range_rejects_5) {
    expect_arity_rejected("geo_kdtree_range", 5,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_geo, geo_lower_hull_rejects_2) {
    expect_arity_rejected("geo_lower_hull", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_geo, geo_min_bounding_rect_rejects_2) {
    expect_arity_rejected("geo_min_bounding_rect", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_geo, geo_triangulate_polygon_rejects_2) {
    expect_arity_rejected("geo_triangulate_polygon", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_geo, geo_upper_hull_rejects_2) {
    expect_arity_rejected("geo_upper_hull", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_geo, geo_voronoi_rejects_2) {
    expect_arity_rejected("geo_voronoi", 2,
                          "assign",
                          "unsupported matrix call");
}

TEST(MatrixCallUndefinedOperand_geo, geo_bezier_deriv) {
    expect_undefined_operand_propagates("geo_bezier_deriv", 2);
}

TEST(MatrixCallUndefinedOperand_geo, geo_bezier_eval) {
    expect_undefined_operand_propagates("geo_bezier_eval", 2);
}

TEST(MatrixCallUndefinedOperand_geo, geo_bezier_subdivide) {
    expect_undefined_operand_propagates("geo_bezier_subdivide", 2);
}

TEST(MatrixCallUndefinedOperand_geo, geo_bspline_eval) {
    expect_undefined_operand_propagates("geo_bspline_eval", 4);
}

TEST(MatrixCallUndefinedOperand_geo, geo_catmull_rom) {
    expect_undefined_operand_propagates("geo_catmull_rom", 2);
}

TEST(MatrixCallUndefinedOperand_geo, geo_convex_hull) {
    expect_undefined_operand_propagates("geo_convex_hull", 1);
}

TEST(MatrixCallUndefinedOperand_geo, geo_convex_hull_3d) {
    expect_undefined_operand_propagates("geo_convex_hull_3d", 1);
}

TEST(MatrixCallUndefinedOperand_geo, geo_delaunay_2d) {
    expect_undefined_operand_propagates("geo_delaunay_2d", 1);
}

TEST(MatrixCallUndefinedOperand_geo, geo_kdtree_3d_knn) {
    expect_undefined_operand_propagates("geo_kdtree_3d_knn", 5);
}

TEST(MatrixCallUndefinedOperand_geo, geo_kdtree_3d_range) {
    expect_undefined_operand_propagates("geo_kdtree_3d_range", 5);
}

TEST(MatrixCallUndefinedOperand_geo, geo_kdtree_knn) {
    expect_undefined_operand_propagates("geo_kdtree_knn", 4);
}

TEST(MatrixCallUndefinedOperand_geo, geo_kdtree_range) {
    expect_undefined_operand_propagates("geo_kdtree_range", 4);
}

TEST(MatrixCallUndefinedOperand_geo, geo_lower_hull) {
    expect_undefined_operand_propagates("geo_lower_hull", 1);
}

TEST(MatrixCallUndefinedOperand_geo, geo_min_bounding_rect) {
    expect_undefined_operand_propagates("geo_min_bounding_rect", 1);
}

TEST(MatrixCallUndefinedOperand_geo, geo_triangulate_polygon) {
    expect_undefined_operand_propagates("geo_triangulate_polygon", 1);
}

TEST(MatrixCallUndefinedOperand_geo, geo_upper_hull) {
    expect_undefined_operand_propagates("geo_upper_hull", 1);
}

TEST(MatrixCallUndefinedOperand_geo, geo_voronoi) {
    expect_undefined_operand_propagates("geo_voronoi", 1);
}

TEST(MatrixCallBadOperandAt_geo, geo_bspline_eval_arg1) {
    expect_bad_operand_at("geo_bspline_eval", 4, 1);
}
