// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Odin Loch
//
// GENERATED by scripts/gen_matrix_call_tests.py from matrix_calls_manifest.json.
// Do not edit: run the two scripts. CI regenerates both and fails on a dirty
// tree, so a handler cannot land without its dispatch tests.

#include "matrix_call_test_support.hpp"

using namespace ms::interp::testing;

TEST(MatrixCallRegistration_tensorops, tensorops_einsum) {
    expect_registered("tensorops_einsum");
}

TEST(MatrixCallRegistration_tensorops, tensorops_matmul) {
    expect_registered("tensorops_matmul");
}

// accepts 2
TEST(MatrixCallArity_tensorops, tensorops_einsum_rejects_3) {
    expect_arity_rejected("tensorops_einsum", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_tensorops, tensorops_matmul_rejects_3) {
    expect_arity_rejected("tensorops_matmul", 3,
                          "assign",
                          "unsupported matrix call");
}

TEST(MatrixCallUndefinedOperand_tensorops, tensorops_einsum) {
    expect_undefined_operand_propagates("tensorops_einsum", 2);
}

TEST(MatrixCallUndefinedOperand_tensorops, tensorops_matmul) {
    expect_undefined_operand_propagates("tensorops_matmul", 2);
}
