// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Odin Loch
//
// GENERATED by scripts/gen_matrix_call_tests.py from matrix_calls_manifest.json.
// Do not edit: run the two scripts. CI regenerates both and fails on a dirty
// tree, so a handler cannot land without its dispatch tests.

#include "matrix_call_test_support.hpp"

using namespace ms::interp::testing;

TEST(MatrixCallRegistration_crypto, crypto_bytes_to_hex) {
    expect_registered("crypto_bytes_to_hex");
}

TEST(MatrixCallRegistration_crypto, crypto_from_hex) {
    expect_registered("crypto_from_hex");
}

// accepts 1
TEST(MatrixCallArity_crypto, crypto_bytes_to_hex_rejects_2) {
    expect_arity_rejected("crypto_bytes_to_hex", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_crypto, crypto_from_hex_rejects_2) {
    expect_arity_rejected("crypto_from_hex", 2,
                          "assign",
                          "unsupported matrix call");
}

TEST(MatrixCallUndefinedOperand_crypto, crypto_bytes_to_hex) {
    expect_undefined_operand_propagates("crypto_bytes_to_hex", 1);
}
