// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Odin Loch
//
// GENERATED by scripts/gen_matrix_call_tests.py from matrix_calls_manifest.json.
// Do not edit: run the two scripts. CI regenerates both and fails on a dirty
// tree, so a handler cannot land without its dispatch tests.

#include "matrix_call_test_support.hpp"

using namespace ms::interp::testing;

TEST(MatrixCallRegistration_finance, finance_bl_implied_returns) {
    expect_registered("finance_bl_implied_returns");
}

TEST(MatrixCallRegistration_finance, finance_bl_posterior_returns) {
    expect_registered("finance_bl_posterior_returns");
}

TEST(MatrixCallRegistration_finance, finance_bl_posterior_returns_default_omega) {
    expect_registered("finance_bl_posterior_returns_default_omega");
}

TEST(MatrixCallRegistration_finance, finance_efficient_frontier) {
    expect_registered("finance_efficient_frontier");
}

TEST(MatrixCallRegistration_finance, finance_max_sharpe) {
    expect_registered("finance_max_sharpe");
}

TEST(MatrixCallRegistration_finance, finance_merton_implied_asset_params) {
    expect_registered("finance_merton_implied_asset_params");
}

TEST(MatrixCallRegistration_finance, finance_min_variance_portfolio) {
    expect_registered("finance_min_variance_portfolio");
}

TEST(MatrixCallRegistration_finance, run_backtest) {
    expect_registered("run_backtest");
}

TEST(MatrixCallRegistration_finance, run_backtest_equity) {
    expect_registered("run_backtest_equity");
}

TEST(MatrixCallRegistration_finance, simulate_gbm_path) {
    expect_registered("simulate_gbm_path");
}

// accepts 3
TEST(MatrixCallArity_finance, finance_bl_implied_returns_rejects_4) {
    expect_arity_rejected("finance_bl_implied_returns", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 5
TEST(MatrixCallArity_finance, finance_bl_posterior_returns_rejects_6) {
    expect_arity_rejected("finance_bl_posterior_returns", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 5
TEST(MatrixCallArity_finance, finance_bl_posterior_returns_default_omega_rejects_6) {
    expect_arity_rejected("finance_bl_posterior_returns_default_omega", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3
TEST(MatrixCallArity_finance, finance_efficient_frontier_rejects_4) {
    expect_arity_rejected("finance_efficient_frontier", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3
TEST(MatrixCallArity_finance, finance_max_sharpe_rejects_4) {
    expect_arity_rejected("finance_max_sharpe", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 5
TEST(MatrixCallArity_finance, finance_merton_implied_asset_params_rejects_6) {
    expect_arity_rejected("finance_merton_implied_asset_params", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_finance, finance_min_variance_portfolio_rejects_2) {
    expect_arity_rejected("finance_min_variance_portfolio", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3
TEST(MatrixCallArity_finance, run_backtest_rejects_4) {
    expect_arity_rejected("run_backtest", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3
TEST(MatrixCallArity_finance, run_backtest_equity_rejects_4) {
    expect_arity_rejected("run_backtest_equity", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 5
TEST(MatrixCallArity_finance, simulate_gbm_path_rejects_6) {
    expect_arity_rejected("simulate_gbm_path", 6,
                          "assign",
                          "unsupported matrix call");
}

TEST(MatrixCallUndefinedOperand_finance, finance_bl_implied_returns) {
    expect_undefined_operand_propagates("finance_bl_implied_returns", 3);
}

TEST(MatrixCallUndefinedOperand_finance, finance_bl_posterior_returns) {
    expect_undefined_operand_propagates("finance_bl_posterior_returns", 5);
}

TEST(MatrixCallUndefinedOperand_finance, finance_bl_posterior_returns_default_omega) {
    expect_undefined_operand_propagates("finance_bl_posterior_returns_default_omega", 5);
}

TEST(MatrixCallUndefinedOperand_finance, finance_efficient_frontier) {
    expect_undefined_operand_propagates("finance_efficient_frontier", 3);
}

TEST(MatrixCallUndefinedOperand_finance, finance_max_sharpe) {
    expect_undefined_operand_propagates("finance_max_sharpe", 3);
}

TEST(MatrixCallUndefinedOperand_finance, finance_min_variance_portfolio) {
    expect_undefined_operand_propagates("finance_min_variance_portfolio", 1);
}

TEST(MatrixCallUndefinedOperand_finance, run_backtest) {
    expect_undefined_operand_propagates("run_backtest", 3);
}

TEST(MatrixCallUndefinedOperand_finance, run_backtest_equity) {
    expect_undefined_operand_propagates("run_backtest_equity", 3);
}
