// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Odin Loch
//
// GENERATED by scripts/gen_matrix_call_tests.py from matrix_calls_manifest.json.
// Do not edit: run the two scripts. CI regenerates both and fails on a dirty
// tree, so a handler cannot land without its dispatch tests.

#include "matrix_call_test_support.hpp"

using namespace ms::interp::testing;

TEST(MatrixCallRegistration_quantum, quantum_anticommutator) {
    expect_registered("quantum_anticommutator");
}

TEST(MatrixCallRegistration_quantum, quantum_coherent_state) {
    expect_registered("quantum_coherent_state");
}

TEST(MatrixCallRegistration_quantum, quantum_commutator) {
    expect_registered("quantum_commutator");
}

TEST(MatrixCallRegistration_quantum, quantum_dagger) {
    expect_registered("quantum_dagger");
}

TEST(MatrixCallRegistration_quantum, quantum_density_matrix) {
    expect_registered("quantum_density_matrix");
}

TEST(MatrixCallRegistration_quantum, quantum_eigenspectrum) {
    expect_registered("quantum_eigenspectrum");
}

TEST(MatrixCallRegistration_quantum, quantum_fock_state) {
    expect_registered("quantum_fock_state");
}

TEST(MatrixCallRegistration_quantum, quantum_ground_state) {
    expect_registered("quantum_ground_state");
}

TEST(MatrixCallRegistration_quantum, quantum_grover_search) {
    expect_registered("quantum_grover_search");
}

TEST(MatrixCallRegistration_quantum, quantum_hadamard) {
    expect_registered("quantum_hadamard");
}

TEST(MatrixCallRegistration_quantum, quantum_ket_basis) {
    expect_registered("quantum_ket_basis");
}

TEST(MatrixCallRegistration_quantum, quantum_ket_normalise) {
    expect_registered("quantum_ket_normalise");
}

TEST(MatrixCallRegistration_quantum, quantum_ket_superposition) {
    expect_registered("quantum_ket_superposition");
}

TEST(MatrixCallRegistration_quantum, quantum_ket_tensor_product) {
    expect_registered("quantum_ket_tensor_product");
}

TEST(MatrixCallRegistration_quantum, quantum_matmul_dm) {
    expect_registered("quantum_matmul_dm");
}

TEST(MatrixCallRegistration_quantum, quantum_op_apply) {
    expect_registered("quantum_op_apply");
}

TEST(MatrixCallRegistration_quantum, quantum_partial_trace) {
    expect_registered("quantum_partial_trace");
}

TEST(MatrixCallRegistration_quantum, quantum_schmidt_bases) {
    expect_registered("quantum_schmidt_bases");
}

TEST(MatrixCallRegistration_quantum, quantum_schmidt_decomposition) {
    expect_registered("quantum_schmidt_decomposition");
}

TEST(MatrixCallRegistration_quantum, quantum_schrodinger) {
    expect_registered("quantum_schrodinger");
}

TEST(MatrixCallRegistration_quantum, quantum_schrodinger_final) {
    expect_registered("quantum_schrodinger_final");
}

TEST(MatrixCallRegistration_quantum, quantum_time_evolve_psi) {
    expect_registered("quantum_time_evolve_psi");
}

// accepts 2
TEST(MatrixCallArity_quantum, quantum_anticommutator_rejects_3) {
    expect_arity_rejected("quantum_anticommutator", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3
TEST(MatrixCallArity_quantum, quantum_coherent_state_rejects_4) {
    expect_arity_rejected("quantum_coherent_state", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_quantum, quantum_commutator_rejects_3) {
    expect_arity_rejected("quantum_commutator", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_quantum, quantum_dagger_rejects_2) {
    expect_arity_rejected("quantum_dagger", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_quantum, quantum_density_matrix_rejects_2) {
    expect_arity_rejected("quantum_density_matrix", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_quantum, quantum_eigenspectrum_rejects_2) {
    expect_arity_rejected("quantum_eigenspectrum", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_quantum, quantum_fock_state_rejects_3) {
    expect_arity_rejected("quantum_fock_state", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_quantum, quantum_ground_state_rejects_2) {
    expect_arity_rejected("quantum_ground_state", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2, 3
TEST(MatrixCallArity_quantum, quantum_grover_search_rejects_4) {
    expect_arity_rejected("quantum_grover_search", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_quantum, quantum_hadamard_rejects_2) {
    expect_arity_rejected("quantum_hadamard", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_quantum, quantum_ket_basis_rejects_3) {
    expect_arity_rejected("quantum_ket_basis", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_quantum, quantum_ket_normalise_rejects_2) {
    expect_arity_rejected("quantum_ket_normalise", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 1
TEST(MatrixCallArity_quantum, quantum_ket_superposition_rejects_2) {
    expect_arity_rejected("quantum_ket_superposition", 2,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_quantum, quantum_ket_tensor_product_rejects_3) {
    expect_arity_rejected("quantum_ket_tensor_product", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_quantum, quantum_matmul_dm_rejects_3) {
    expect_arity_rejected("quantum_matmul_dm", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 2
TEST(MatrixCallArity_quantum, quantum_op_apply_rejects_3) {
    expect_arity_rejected("quantum_op_apply", 3,
                          "assign",
                          "unsupported matrix call");
}

// accepts 4
TEST(MatrixCallArity_quantum, quantum_partial_trace_rejects_5) {
    expect_arity_rejected("quantum_partial_trace", 5,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3
TEST(MatrixCallArity_quantum, quantum_schmidt_bases_rejects_4) {
    expect_arity_rejected("quantum_schmidt_bases", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3
TEST(MatrixCallArity_quantum, quantum_schmidt_decomposition_rejects_4) {
    expect_arity_rejected("quantum_schmidt_decomposition", 4,
                          "assign",
                          "unsupported matrix call");
}

// accepts 5
TEST(MatrixCallArity_quantum, quantum_schrodinger_rejects_6) {
    expect_arity_rejected("quantum_schrodinger", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 5
TEST(MatrixCallArity_quantum, quantum_schrodinger_final_rejects_6) {
    expect_arity_rejected("quantum_schrodinger_final", 6,
                          "assign",
                          "unsupported matrix call");
}

// accepts 3
TEST(MatrixCallArity_quantum, quantum_time_evolve_psi_rejects_4) {
    expect_arity_rejected("quantum_time_evolve_psi", 4,
                          "assign",
                          "unsupported matrix call");
}

TEST(MatrixCallUndefinedOperand_quantum, quantum_anticommutator) {
    expect_undefined_operand_propagates("quantum_anticommutator", 2);
}

TEST(MatrixCallUndefinedOperand_quantum, quantum_commutator) {
    expect_undefined_operand_propagates("quantum_commutator", 2);
}

TEST(MatrixCallUndefinedOperand_quantum, quantum_dagger) {
    expect_undefined_operand_propagates("quantum_dagger", 1);
}

TEST(MatrixCallUndefinedOperand_quantum, quantum_density_matrix) {
    expect_undefined_operand_propagates("quantum_density_matrix", 1);
}

TEST(MatrixCallUndefinedOperand_quantum, quantum_eigenspectrum) {
    expect_undefined_operand_propagates("quantum_eigenspectrum", 1);
}

TEST(MatrixCallUndefinedOperand_quantum, quantum_ground_state) {
    expect_undefined_operand_propagates("quantum_ground_state", 1);
}

TEST(MatrixCallUndefinedOperand_quantum, quantum_hadamard) {
    expect_undefined_operand_propagates("quantum_hadamard", 1);
}

TEST(MatrixCallUndefinedOperand_quantum, quantum_ket_normalise) {
    expect_undefined_operand_propagates("quantum_ket_normalise", 1);
}

TEST(MatrixCallUndefinedOperand_quantum, quantum_ket_superposition) {
    expect_undefined_operand_propagates("quantum_ket_superposition", 1);
}

TEST(MatrixCallUndefinedOperand_quantum, quantum_ket_tensor_product) {
    expect_undefined_operand_propagates("quantum_ket_tensor_product", 2);
}

TEST(MatrixCallUndefinedOperand_quantum, quantum_matmul_dm) {
    expect_undefined_operand_propagates("quantum_matmul_dm", 2);
}

TEST(MatrixCallUndefinedOperand_quantum, quantum_op_apply) {
    expect_undefined_operand_propagates("quantum_op_apply", 2);
}

TEST(MatrixCallUndefinedOperand_quantum, quantum_partial_trace) {
    expect_undefined_operand_propagates("quantum_partial_trace", 4);
}

TEST(MatrixCallUndefinedOperand_quantum, quantum_schmidt_bases) {
    expect_undefined_operand_propagates("quantum_schmidt_bases", 3);
}

TEST(MatrixCallUndefinedOperand_quantum, quantum_schmidt_decomposition) {
    expect_undefined_operand_propagates("quantum_schmidt_decomposition", 3);
}

TEST(MatrixCallUndefinedOperand_quantum, quantum_schrodinger) {
    expect_undefined_operand_propagates("quantum_schrodinger", 5);
}

TEST(MatrixCallUndefinedOperand_quantum, quantum_schrodinger_final) {
    expect_undefined_operand_propagates("quantum_schrodinger_final", 5);
}

TEST(MatrixCallUndefinedOperand_quantum, quantum_time_evolve_psi) {
    expect_undefined_operand_propagates("quantum_time_evolve_psi", 3);
}

TEST(MatrixCallBadOperandAt_quantum, quantum_anticommutator_arg1) {
    expect_bad_operand_at("quantum_anticommutator", 2, 1);
}

TEST(MatrixCallBadOperandAt_quantum, quantum_commutator_arg1) {
    expect_bad_operand_at("quantum_commutator", 2, 1);
}

TEST(MatrixCallBadOperandAt_quantum, quantum_grover_search_arg1) {
    expect_bad_operand_at("quantum_grover_search", 3, 1);
}

TEST(MatrixCallBadOperandAt_quantum, quantum_ket_tensor_product_arg1) {
    expect_bad_operand_at("quantum_ket_tensor_product", 2, 1);
}

TEST(MatrixCallBadOperandAt_quantum, quantum_matmul_dm_arg1) {
    expect_bad_operand_at("quantum_matmul_dm", 2, 1);
}

TEST(MatrixCallBadOperandAt_quantum, quantum_op_apply_arg1) {
    expect_bad_operand_at("quantum_op_apply", 2, 1);
}

TEST(MatrixCallBadOperandAt_quantum, quantum_schrodinger_arg1) {
    expect_bad_operand_at("quantum_schrodinger", 5, 1);
}

TEST(MatrixCallBadOperandAt_quantum, quantum_schrodinger_final_arg1) {
    expect_bad_operand_at("quantum_schrodinger_final", 5, 1);
}

TEST(MatrixCallBadOperandAt_quantum, quantum_time_evolve_psi_arg1) {
    expect_bad_operand_at("quantum_time_evolve_psi", 3, 1);
}
