// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Odin Loch
//
// GENERATED by scripts/gen_matrix_call_tests.py from matrix_calls_manifest.json.
// Do not edit: run the two scripts. CI regenerates both and fails on a dirty
// tree, so a handler cannot land without its dispatch tests.

#include "matrix_call_test_support.hpp"

using namespace ms::interp::testing;

TEST(MatrixCallRegistration_info, info_channel_capacity_input) {
    expect_registered("info_channel_capacity_input");
}

// accepts 1
TEST(MatrixCallArity_info, info_channel_capacity_input_rejects_2) {
    expect_arity_rejected("info_channel_capacity_input", 2,
                          "assign",
                          "unsupported matrix call");
}

TEST(MatrixCallUndefinedOperand_info, info_channel_capacity_input) {
    expect_undefined_operand_propagates("info_channel_capacity_input", 1);
}
